### ISSUE TITLE
Are import statements supported?

### ISSUE THREAD

**Issue by tcolgate** [dop251/goja#1]
I have an index.js with 
```
import utils from 'util'
```
and  a blank util.js

results in 

```
panic: SyntaxError: index.js: Line 7:1 Unexpected reserved word [recovered]
        panic: Panic at 3: SyntaxError: index.js: Line 7:1 Unexpected reserved word [recovered]
        panic: Panic at 3: SyntaxError: index.js: Line 7:1 Unexpected reserved word
```

I'm playing with trying to get hubot script running from  a Go application

I've included the load() function from goja/main.go, which seems to work with a simple ```load('util.js')```

**Comment by rickihastings** [comment]
Import statements are part of the ES6 standard, not ES5.1 so I'm assuming that this is not implemented yet.

**Comment by dop251** [comment]
Import statements are not implemented as they are not part of ES5.1 spec. It would be quite easy to replicate node's require() functionality, in fact I've already got a working code which just needs a few touches after which I may add it here.

Supporting import statements would require significantly more effort as it involves extending parser and compiler, there is no plan to add those any time soon, although I'm open to PRs.

**Comment by iam4x** [comment]
@dop251 This might be a funny idea, but maybe you could use Babeljs to transpile ES6 code into ES5 so it can be interpreted through Goja VM?

**Comment by dop251** [comment]
@iam4x It's not a funny idea at all, this is the recommended way to run ES 2016 code in goja. Unfortunately with imports this also requires some runtime support. I've created a new repo (https://github.com/dop251/goja_nodejs) for nodejs compatibility modules and added a basic support for require(). Give it a go, let me know if there is any problem.

**Comment by BrianLeishman** [comment]
> [@dop251](https://github.com/dop251) This might be a funny idea, but maybe you could use Babeljs to transpile ES6 code into ES5 so it can be interpreted through Goja VM?

Super old comment but esbuild now is a fantastic option that's actually written in Go as well so you could use that to transpile your js with imports

**Comment by yamada-sexta** [comment]
Is this implemented?
