### ISSUE TITLE
Can support go module mechanism?

### ISSUE THREAD

**Issue by saibing** [dop251/goja#106]
- add a go.mod file
- create a git tag

**Comment by dop251** [comment]
Why? Unless I misunderstand something you can import a non-module dependency in your module project just fine, it will lock on the current git revision.

In goja each commit is essentially a new release.

**Comment by dennwc** [comment]
It may still make sense to have a `go.mod` file, even though the library may be effectively locked to `v0` (no release tags).

The reason to add it is that it will list compatible library versions used by `goja` itself.

**Comment by PaluMacil** [comment]
@dop251 This commit hash approach means that every time someone wants to know how old a version they use might be, they would need to look at a long list of commit hashes and figure out what was implemented when. That's insanity, and it will get worse over time. When the es6 branch is merged in, it will mean someone trying to determine when that merge happened and then figuring out which hash to use. Someone can still use a hash with go.mod. That ability wouldn't go away. As dennwc said, it also gives you the opportunity to specify dependency versions even if you don't make release tags and keep going as-is.
