### ISSUE TITLE
Let Get return an error instead of panicking

### ISSUE THREAD

**Issue by gballet** [dop251/goja#118]
In Otto, the `Get` function returns both a `Value` and an `error`. In Goja, only a Value is returned and the underlying code is expected to `panic`.

We have a use case in which an object's properties are used as a facade for an RPC call, which can fail. We would like to get the same behavior as Otto, and be able to determine if an `error` has been raised.

I can do the conversion work and submit a PR, I just wonder if it would be merged or if you have issues with changing the signature of `Get` ?

**Comment by dop251** [comment]
I do have issues with changing the signature of Get() at this stage. Despite Readme saying the API is subject to change, in reality a lot of people are using goja now and I wouldn't want to break their code with such a fundamental change.

Besides I don't think this is the right thing to do. Errors in Get() is an edge case and you can easily write a wrapper function with recover() to achieve the required behaviour. And it's not just me who thinks this way, see https://godoc.org/syscall/js#Value.Get
