### ISSUE TITLE
Some way to reset an interrupted VM/runtime

### ISSUE THREAD

**Issue by na--** [dop251/goja#120]
In [k6](https://github.com/loadimpact/k6/) we heavily reuse goja VMs in our VUs (virtual users), since their initialization (due to core-js and sometimes huge user scripts) is quite costly in terms of CPU, time, and memory. We also schedule these VUs in a way that sometimes necessitates the interruption/abort of the JS execution midway through the script.

Internally in k6 we're mostly using [`context`](https://golang.org/pkg/context/)s with timeouts or cancel functions to implement these interruptions (including the stopping of any native Go functions, HTTP requests, etc. features we expose to the users' scripts), but since goja doesn't accept contexts, we've spawned a separate goroutine per runtime that calls [`Runtime.Interrupt()`](https://godoc.org/github.com/dop251/goja#Runtime.Interrupt) when its context expires.

The problem we have with this approach is that it has a race condition :disappointed:. Sometimes, we happen to `Interrupt()` the runtime in between iterations, when it's not actually running any JS code. This wouldn't have been an issue if we didn't want to reuse runtimes, but we do... And when such an interrupted runtime is reused to run JS code again, it immediately aborts because of this goja code: https://github.com/dop251/goja/blob/aaec0e7bde29c4e80d4088f2dc6e55b4be6fa502/vm.go#L286-L288

So, we occasionally end up with a dud iteration and a confusing error we show users (https://github.com/loadimpact/k6/issues/1283). And because the `Interrupt()` logic uses a very internal atomic we have no way to access from outside of the runtime, we have no way of resetting or "enabling" the runtime again: https://github.com/dop251/goja/blob/aaec0e7bde29c4e80d4088f2dc6e55b4be6fa502/vm.go#L309-L314

Here's a simple script that demonstrates this issue:
```go
package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"time"

	"github.com/dop251/goja"
)

var errInterrupted = errors.New("we are done")

func reuseTheVM(vm *goja.Runtime) error {
	// We want to iterate only for some limited duration
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Millisecond)
	defer cancel()

	go func() {
		// Interrupt the VM when the allotted time expires
		<-ctx.Done()
		log.Print("  Interrupting the script execution")
		vm.Interrupt(errInterrupted)
	}()

	for i := 0; ; i++ {
		log.Printf("  Running iteration %d in the VM...", i)
		_, err := vm.RunString(`
			var dummy = [];
			for (var i = 0; i < 500; i++) {
				dummy.push(i);
			};
		`)

		select {
		case <-ctx.Done(): // Our allotted time is over, exit
			if err == nil {
				// This is the danger
				log.Print("  WARNING: exiting without being interrupted!")
			} else if errInt, ok := err.(*goja.InterruptedError); ok && errInt.Value() == errInterrupted {
				log.Print("  Exiting after we were interupted, perfectly normal!")
			} else {
				panic(err) // unexpected error
			}
			return nil
		default:
			// We still have some time to do work
			if err != nil {
				return fmt.Errorf("The context is still not done, but the VM was interrupted by '%v'", err)
			}
		}
	}

}

func main() {
	vm := goja.New()
	for i := 0; ; i++ {
		log.Printf("Using the same VM for the %dth time...", i)
		if err := reuseTheVM(vm); err != nil {
			log.Fatal(err)
		}
	}
}

```

As you can see, it's going to be pretty tricky to fix this race condition without modifying goja in some way. So, would you accept the contribution of some new method that resets the runtime? We can submit a PR if that seems OK to you, or we'd appreciate if you have any other ideas for solving this issue.

**Comment by na--** [comment]
There are a couple of workarounds to this issue I can think of. 

The first one involves injecting a nasty synchronization point at the end of our users' JS functions, so that the script execution doesn't end before we know it, and we can know if we should call `vm.Interrupt(errInterrupted)` or not.

A more sane approach could be something like running an empty script to clear the VM state, though that also needs to be synchronized, to avoid another race condition...

**Comment by dop251** [comment]
I could add a method to reset the interrupt flag, but you still have to have some sort of synchronisation between the watchdog and the executing goroutines, to make sure that the watchdog doesn't trigger when the work has been done and the runtime is made available for re-use.

**Comment by na--** [comment]
hmm true, though in our case that would sort of take care of itself (after some planned refactoring anyway):
- we will make sure that we have called `Interrupt()` *and* that the JS execution has returned before we put the runtime back in the buffer pool of runtimes
- we will always call this new `Reset()` (or however you decide to call it) method when we get a runtime out of the buffer pool, before we start running any code in it

**Comment by na--** [comment]
Thanks! :bowing_man:
