### ISSUE TITLE
Are you going to support debug mode?

### ISSUE THREAD

**Issue by dspasibenko** [dop251/goja#121]
Very good project, thanks! Just curious, do you have any plans by supporting a debug mode of the script?

**Comment by dspasibenko** [comment]
Sorry for the misunderstanding. I meant to support some functionality and an interface on vm level for debugging script - to control the script execution, mainly interrupt execution at certain script place (breakpoint), providing context of the script variables, its stack, and an ability to continue the execution again. Debugging the script.

I am looking for an JS interpreter for Go, to use it for scripting in a business domain where having an ability to debug a script is essential. Found goja and otto. I mentioned that otto has debug mode and it provides some script execution context together with an ability to trap the script at certain points. The question is about the same functionality for goja. 

Thanks!

**Comment by dop251** [comment]
I see. No, I don't have such plans, sorry.
