### ISSUE TITLE
Custom Errors

### ISSUE THREAD

**Issue by Cretezy** [dop251/goja#122]
Hey, how would we implement different error types other than a TypeError and a GoError? Thanks, awesome project!

**Comment by dop251** [comment]
Hi @Cretezy, not sure what you mean. The way you would normally do it in ECMAScript 5, like this for example: http://jsbin.com/rolojuhuya/1/edit?js,console

**Comment by Cretezy** [comment]
Ah I see. One more question, how can I run a constructor? For example, I'm polyfilling `Promise`, but don't know how to create one. My solution currently is:

```go
  // Setup
  promiseConstructorGetter, err := vm.RunString("function __promiseConstructor(callback) { return new Promise(callback); }; __promiseConstructor")
  if err != nil {
    return nil, err
  }

  promiseConstructor := promiseConstructorGetter.Export().(func(call goja.FunctionCall) goja.Value)
  vm.Set("__promiseConstructor", nil)


  // Use
  promiseConstructor(goja.FunctionCall{
    This: this,
    Arguments: []goja.Value{
      runtime.Vm.ToValue(callback),
    },
  })
```

**Comment by dop251** [comment]
Your code should be written as this:
```go
// Setup
v, err := vm.RunString("(function(cb) { return new Promise(cb); })")
if err != nil {
	panic(err)
}
promiseConstructor, ok := goja.AssertFunction(v)
if !ok {
	panic("not a function")
}

// Use
p, err := promiseConstructor(this, runtime.Vm.ToValue(callback))
```

In fact I think the current `Export()` behaviour for functions is wrong, it should return `goja.Callable` instead of `goja.FunctionCall`. I know it's a breaking change but I kinda feel like I need to do this :)

The (slight) problem with your code is that if the function throws an exception you will get a panic.

Also, to simplify your code even further I could expose `*Runtime.builtin_new()` like this:

```go
func (r *Runtime) New(construct Value, args ...Value) (*Object, error)
```

**Comment by Cretezy** [comment]
Ah yes I didn't try putting the function in `() `.

I agree that a constructor method would be nice.

I have one more question: how good is the memory release? Does the GC take care of releasing all the memory properly, or is there any steps I can do the forcibly clear a vm after use?

**Comment by dop251** [comment]
You should not do anything special as long as you use `Run*()` methods and the result of `AssertFunction()`. During a normal run the VM stack is not cleared, however when the above methods finish it does get cleared. In your code BTW (where you use `FunctionCall`) it does not, that's another reason for not exposing it.

**Comment by Cretezy** [comment]
I mean as the overall runtime. I'm used to releasing V8's isolates to clear out the memory fully. I tried profiling but it was hard to test if the GC was acting properly and releasing runtimes correctly. Have you done any testing related to this, or know any way to test?

**Comment by dop251** [comment]
Run a soak test and do memory profiling. Runtimes should be garbage-collected as long as you are no longer referencing them.
