### ISSUE TITLE
TypeError if set prototype of a function in some situations

### ISSUE THREAD

**Issue by lujjjh** [dop251/goja#131]
A reproducible example:

```go
package main

import (
	"fmt"

	"github.com/dop251/goja"
)

const code = `
"use strict";
function A() {}
A.__proto__ = Object;
// void A.prototype;
A.prototype = {};
`

func main() {
	fmt.Println(goja.New().RunString(code))
}

// <nil> TypeError at <eval>:6:15(11)
```

Since a function's `prototype` is lazy initialized at [`getPropStr`](https://github.com/dop251/goja/blob/ebfbf88ae3f7b4d3929fad07fdaf3001cbcf209a/func.go#L42), the code above does not trigger an initialization.

When executing `A.prototype = {};`, goja would [throw a TypeError with empty message](https://github.com/dop251/goja/blob/ebfbf88ae3f7b4d3929fad07fdaf3001cbcf209a/object.go#L260) as it detects `A.__proto__.prototype` is not writable. Uncommenting `// void A.prototype;` can avoid this.

I fixed the issue temporarily by moving `addPrototype` to `Runtime#newFunc`. Maybe there would be a better solution?

**Comment by dop251** [comment]
Hi @lujjjh,

Thanks for reporting this. There is a better solution and I am going to push it shortly.
