### ISSUE TITLE
Misbehavior of ToValue() on map type with methods

### ISSUE THREAD

**Issue by Julio-Guerra** [dop251/goja#134]
I found an issue while trying to enumerate the keys of an object that I created with `ToValue()` from a map type having helper methods.

As an example, let's use `http.Header` type which is a Go map type with methods.
When converting a `http.Header` value using `ToValue()`, this line of code in `ToValue()` https://github.com/dop251/goja/blob/master/runtime.go#L1067 prevents from making it a `objectGoMapReflect` and ends up as a `objectGoReflect`.

But the its key enumeration only happens on methods and not on the map keys.

Here is a test example that demonstrates the issue:
```
	func TestMapTypeBinding(t *testing.T) {
		headers := http.Header{
			"k0": []string{},
			"k1": []string{"v1"},
			"k2": []string{"v21", "v22"},
			"k3": []string{"v3"},
		}
		vm := goja.New()
		vm.Set("headers", headers)
		v, err := vm.RunString(`Object.keys(headers)`)
		require.NoError(t, err)
		result := v.Export()
		require.Equal(t, []interface{}{"k0", "k1", "k2", "k3"}, result)
	})
```

Failing with:
> Expected :[]interface {}{"k0", "k1", "k2", "k3"}
> Actual   :[]interface {}{"Add", "Del", "Get", "Set", "Write", "WriteSubset"}

I'd be happy to provide a fix, but I'd like to understand first in which case it should be methods only as suggested by the current implementation.

**Comment by dop251** [comment]
Otherwise it would create an ambiguity between the methods and the map keys. For example, if headers contained "Add", in Javascript there would be no way to distinguish it from the method.

There are only two solutions to avoid such ambiguity: to hide the methods or to hide the keys. I chose the latter because a) if you define methods on a map it's usually because you want to use them and b) if you need to use both in this case, you still can by wrapping it in a custom struct and adding Set() and Get() methods, like this:

```go
type M map[string]interface{}

func (m M) Test() bool {
	return true
}

type Wrapper struct {
	M
}

func (w Wrapper) Set(k string, v interface{}) {
	w.M[k] = v
}

func (w Wrapper) Get(k string) interface{} {
	return w.M[k]
}

func main() {
	m := make(M)
	wrapper := Wrapper{m}
	wrapper.Set("a", true)
	fmt.Println(wrapper.Test(), wrapper.Get("a"))
}
``` 
... whereas in the opposite scenario there would be no way to access the methods.

I understand this is not super intuitive, if you have a better solution let me know.

**Comment by Julio-Guerra** [comment]
I just tried with 
```
type myWrapper struct{ http.Header }

func (w myWrapper) Get(k string) interface{} {
	return w.Header.Get(k)
}

func (w myWrapper) Set(k string, v interface{}) {
	w.Header.Set(k, v.(string))
}
```

But still got:
```
[]interface {}{"Header", "Add", "Del", "Get", "Set", "Write", "WriteSubset"}
```

> I understand this is not super intuitive, if you have a better solution let me know.
What about having the union of both?

**Comment by dop251** [comment]
> But still got:
> 
> ```go
> []interface {}{"Header", "Add", "Del", "Get", "Set", "Write", "WriteSubset"}
> ```
> 

Doesn't that solve your problem? You can access the headers using Get() and Set() methods and also use other methods, like Add() and Del().

> > I understand this is not super intuitive, if you have a better solution let me know.
> 
> What about having the union of both?

This is not possible without creating a very confusing and potentially dangerous behaviour.

**Comment by dop251** [comment]
Sorry, I didn't realise `http.Header` already had `Get()` and `Set()`. I was thinking about adding the missing ones, for example `Values()` which was also added in Go 1.14 but was not available before.

**Comment by Julio-Guerra** [comment]
I am running third-party js I cannot modify and they are using `Object.keys` as I showed you in order to walk an object I provide though the go/js bindings.

Btw, this is working when using otto's [Value.Call](https://godoc.org/github.com/robertkrimen/otto#Value.Call) method but I didn't find the underlying implementation allowing it :thinking:

I unfortunately cannot use goja until I solve this, and ideally without having to copy the value to another one.

The other solution I can imagine would be checking if the go value implements a specific interface to let `ToValue()` or the enumeration function know that we want to use the map keys and not the methods.

**Comment by dop251** [comment]
You can convert `http.Header` to its underlying map type and pass this value to the runtime:

```go
	vm := New()
	m := http.Header{}
	m.Set("Test", "42")
	vm.Set("h", map[string][]string(m))
	v, err := vm.RunString(`
	var keys = Object.keys(h);
	keys.length === 1 && keys[0] === "Test";
	`)
	if err != nil {
		t.Fatal(err)
	}
	if v != valueTrue {
		t.Fatalf("v: %v", v)
	}
```

**Comment by Julio-Guerra** [comment]
The `http.Header` type is example to keep it simple here.
In my precise case, I have nested map types with methods each: `type RequestParams map[string]url.Values` where `RequestParams` and `url.Values` both have methods. Converting the root type only solves part of the issue :sweat_smile:

**Comment by dop251** [comment]
Sounds like a solid case for using ES6 proxy. Fancy giving it a try? I need testers 😄  https://github.com/dop251/goja/tree/proxy

**Comment by Julio-Guerra** [comment]
I ran the previous test with github.com/dop251/goja@proxy but got the same result.
Should I change something in the Go implementation?

**Comment by dop251** [comment]
You need to implement a Proxy (either in JS or in Go). See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy and https://github.com/dop251/goja/blob/proxy/proxy.go#L267

**Comment by Julio-Guerra** [comment]
Sorry, I didn't find the solution.
Here is what I tried with the `http.Header` example:

```go
	t.Run("map type binding", func(t *testing.T) {
		headers := http.Header{
			"k0": []string{},
			"k1": []string{"v1"},
			"k2": []string{"v21", "v22"},
			"k3": []string{"v3"},
		}
		vm := goja.New()
		jsVal := vm.ToValue(headers)
		vm.Set("headers", jsVal)
		vm.NewProxy(jsVal.ToObject(vm), &goja.ProxyTrapConfig{
			Get: func(target *goja.Object, property string, receiver *goja.Object) (value goja.Value) {
				return vm.ToValue(headers[property])
			},
			OwnKeys: func(target *goja.Object) (object *goja.Object) {
				keys := make([]interface{}, 0, len(headers))
				for k := range headers {
					keys = append(keys, k)
				}
				return vm.ToValue(keys).ToObject(vm)
			},
		})
		v, err := vm.RunString(`Object.keys(headers)`)
		require.NoError(t, err)
		result := v.Export()
		require.Equal(t, []interface{}{"k0", "k1", "k2", "k3"}, result)
	})
```

**Comment by Julio-Guerra** [comment]
I adapted the previous http headers test this way:

```go
	t.Run("map type binding", func(t *testing.T) {
		headers := http.Header{
			"k0": []string{},
			"k1": []string{"v1"},
			"k2": []string{"v21", "v22"},
			"k3": []string{"v3"},
		}
		vm := goja.New()
		jsVal := vm.ToValue(headers)
		proxy := vm.NewProxy(jsVal.ToObject(vm), &goja.ProxyTrapConfig{
			OwnKeys: func(target *goja.Object) (object *goja.Object) {
				keys := make([]interface{}, 0, len(headers))
				for k := range headers {
					keys = append(keys, k)
				}
				return vm.ToValue(keys).ToObject(vm)
			},
		})
		vm.Set("headers", proxy)
		v, err := vm.RunString(`Object.keys(headers)`)
		require.NoError(t, err)
		result := v.Export()
		require.Equal(t, []interface{}{"k0", "k1", "k2", "k3"}, result)
	})
```

Resulting in:
> TypeError: 'ownKeys' on proxy: trap result did not include non-configurable 'Add' at keys (native)

But anyway, now that I see how proxy works, I think we still have the issue with nested types: how could a sub-value be also proxied?

As a last resort, I changed the Go types I use to native Go types [instead of reusing `http.Header`, `url.Values`, etc.] and the problem gets avoided. But this is not super elegant :cry: I think I will go this way for now as I would really love to use goja instead of otto asap...

PS: other than that, the branch worked fine on the js code (a SQLi detection written in js).

**Comment by dop251** [comment]
In order for it to work you need to specify an empty object as the proxy target and you also need  to implement at least the getOwnPropertyDescriptor trap. Do a pull and have a look at TestProxy_Object_native_proxy_ownKeys()

**Comment by dop251** [comment]
As for nested types, just wrap them in another proxy on get and getOwnPropertyDescriptor.

**Comment by Julio-Guerra** [comment]
Thanks a lot for your help @dop251 but I'll keep my last resort solution because it is from far the simplest and less complex even if I lower the code quality ^^

I let you decide what you want to do with this issue.

Feel free to ping me for any VM tests. Your VM is very helpful for us (Sqreen). I will push my change to goja in the next few days.
