### ISSUE TITLE
Suggestion: merge goja_nodejs into goja

### ISSUE THREAD

**Issue by xushiwei** [dop251/goja#140]
For now, github.com/dop251/goja has cycle dependency.
See https://github.com/dop251/goja/blob/master/goja/main.go
It is not recommended for Go.

**Comment by dop251** [comment]
It is not a circular dependency because github.com/dop251/goja and  github.com/dop251/goja/goja are different packages. It would probably make sense to move the CLI into the nodejs package, but I don't see much point in doing so.

**Comment by xushiwei** [comment]
However, compiling github.com/dop251/goja always requires goja_nodejs. If so, what is the value of separating them from each other?

**Comment by zyxkad** [comment]
@dop251 Move the cli to somewhere else is reasonable, I can see the cli is using `github.com/dop251/goja_nodejs v0.0.0-20211022123610-8dd9abb0616d`. And the package at that point [8dd9ab](https://github.com/dop251/goja_nodejs/blob/8dd9abb0616d2e09e46e2629f6dd415c220bce3e/go.mod) is using `v0.0.0-20211022113120-dc8c55024d06`.
So we will be confused what's the actually version of the goja cli is using for
