### ISSUE TITLE
enumPop not reached when returning early

### ISSUE THREAD

**Issue by Asarew** [dop251/goja#148]
I think that the iterator is not being popped from the stack when returning from inside a `for in` loop

```js
var foo = {
  bar: "baz",
}
function dooDoThing() {
  for (var key in foo) {
    return;
  }
}
dooDoThing();
```
this will leave the iterator on `vm.iterStack`

**Comment by Asarew** [comment]
i haven't checked what would happen if you throw an exception but i suspect that the fix you closed this issue with wouldn't cover that case

**Comment by dop251** [comment]
Exception should be fine
