### ISSUE TITLE
Create Object Example

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#150]
Can someone provide a complete example of the example from the docs. I would like to instantiate a new object from within that exists as a map[string]interface{}

go object:

var m3intrfs= make(map[string]interface{})
m3intrfs["one"] = "foo"
m3intrfs["two"] = 2
m3intrfs["three"] = 3.3

var m4intrfs= make(map[string]interface{})
m4intrfs["one"] = "foo"
m4intrfs["two"] = 2
m4intrfs["three"] = 3.3

I would like to inject either object based on an arg of 1 or 2.

func MyObject(call goja.ConstructorCall) *Object {
    // call.This contains the newly created object as per http://www.ecma-international.org/ecma-262/5.1/index.html#sec-13.2.2
    // call.Arguments contain arguments passed to the function

    call.This.Set("method", method)

    // ...

    // If return value is a non-nil *Object, it will be used instead of call.This
    // This way it is possible to return a Go struct or a map converted
    // into goja.Value using runtime.ToValue(), however in this case
    // instanceof will not work as expected.
    return nil
}

runtime.Set("MyObject", MyObject)

Then it can be used in JS as follows:

var o = new MyObject(arg);
var o1 = MyObject(arg); // same thing
o instanceof MyObject && o1 instanceof MyObject; // true

**Comment by dop251** [comment]
I'm not exactly sure what you are trying to achieve but if it's just returning a `map[string]interface{}` you don't need to use this mechanism (unless you absolutely have to call it using the `new` operator). You can use a regular function instead:

```go
vm.Set("f", func(arg bool) map[string]interface{} {
      if arg {
         return make(map[string]interface{}{ .... })
      }
      return make(map[string]interface{}{ .... })
})
```
Then just call it as any other JS function
```js
var o = f(true);
```

**Comment by Kunderao** [comment]
dop251,  you are a god. Thank you for helping me see clearly. I wanted to return a map[string]interface{}  structure from the go world into goja env.  Which structure it returned would be  specified by the argument in the function call. It all works now.

on another note:

Would you, when you have time, provide a full example of full go object instantiation with with methods and all  into the js env. I realize I don't need this but I am interested in seeing how it works.

Thank you!

**Comment by dop251** [comment]
There is an example here: https://github.com/dop251/goja/issues/45#issuecomment-341508495 It was written before the implementation, but I think it's still valid.

But again, I must stress that in most cases you don't need it, you can pass any Go `struct` and exported fields and methods will become available in JS.
