### ISSUE TITLE
An issue with "new Function"

### ISSUE THREAD

**Issue by wailovet** [dop251/goja#151]
I found this code does not work when I use it

```
    a = function () {
        this.m2 = (new Function("with(this){m(c)}"))
    };
    a.prototype.c = "hello";
    a.prototype.m = function () {
        console.log("c:", this.c)
    };
    b = new a();
    b.m2()
```

 chrome  result : "c: hello"
 goja   result : "c: undefined"

**Comment by dop251** [comment]
Thanks for reporting. It should now be fixed, but I would not use `with` unless it's some legacy code you cannot or do not want to touch. Use strict mode whenever possible.

**Comment by wailovet** [comment]
> Thanks for reporting. It should now be fixed, but I would not use `with` unless it's some legacy code you cannot or do not want to touch. Use strict mode whenever possible.

Thanks, this error comes from an extension library and I can't modify it
