### ISSUE TITLE
Structs

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#153]
type str struct {
	A [5]float64
	B [5]float64
	C [5]float64
	D [5]float64
}

func main(){
	mystr:= str{
		A: [5]float64{11,22,333,444,55},
		B: [5]float64{11,22,333,444,55},
		C: [5]float64{11,22,333,444,55},
		D: [5]float64{11,22,333,444,55},
	}
	vm.Set("mystr", mystr)
	var prg = "" +
		"mystr.A[0];"
}
I get a nil from this. Am I not indexing the array properly? mystr.A works fine just not  mystr.A[0] access.

'mystr.A'  yields [11 22 333 444 55]

**Comment by Kunderao** [comment]
Is there a way to inject the methods of a struct into a VM as well?
type str struct {
	A [5]float64
	B [5]float64
	C [5]float64
	D [5]float64
}

func( s *str) getMult(idx int) float64 {
	return s.A[idx] * s.B[idx]
}

var prg = "" +
		"e = getintr(1); e; auth.Salary(2,3); " +
		"f=mystr.getMult(1);"

vm.Set("mystr", mystr)

TypeError: Object has no member 'getMult' at prg1:1:53(20)panic: TypeError: Object has no member 'getMult' at <eval>:1:53(20)

**Comment by dop251** [comment]
To answer your first question, there is no support for arrays yet, only slices. I will add it shortly.
As for the second question, yes, but the methods must be exported, just like fields (i.e. should be GetMult).

**Comment by Kunderao** [comment]
type str struct {
	A [5]float64
	B [5]float64
	C [5]float64
	D [5]float64
}

func( s *str) GetMult(idx int) float64 {
	return s.A[idx] * s.B[idx]
}

main(){
	var prg = "" +
		"e = getintr(1); e; auth.Salary(2,3); " +
		"f=mystr.GetMult(1);"

	vm.Set("mystr", mystr)

TypeError: Object has no member 'GetMult' at prg1:1:53(20)panic: TypeError: Object has no member 'GetMult' at <eval>:1:53(20)

**Comment by Kunderao** [comment]
I conerted to slices:

type str struct {
	A []float64
	B []float64
	C []float64
	D []float64
}
	mystr:= str{}
	mystr.A=make([]float64, 100)
	mystr.A[0]=0
	mystr.A[1]=1

var prg = "" +
		"mystr.A[0];"

The above still yields a nil.

**Comment by dop251** [comment]
You need `vm.Set("mystr", &mystr)`, otherwise mystr is unaddressable and therefore a pointer method cannot be called on it, like in the following example:
```go
var s str
m := make(map[int]str)
m[0] = s
m[0].GetMult(1) // will cause a compile error
```

**Comment by Kunderao** [comment]
I no longer get method "not found" errors as I am now setting with reference how ever the functions return a nil

type str struct {
	A [5]float64
	B [5]float64
	C [5]float64
	D [5]float64
}

func( s *str) GetMult(idx int) float64 {
	return s.A[idx]*s.B[idx]
}

func( s *str) SayHello() string {
	return "Hello world\n"
}

main()
{
	mystr:= str{
		A: [5]float64{11,22,333,444,55},
		B: [5]float64{11,22,333,444,55},
		C: [5]float64{11,22,333,444,55},
		D: [5]float64{11,22,333,444,55},
	}

vm.Set("mystr", &mystr)

	var prg = "" +
		"mystr.GetMult(1);" +
		"f"+
		"mystr.SayHello()"

either function returns a nil.

**Comment by dop251** [comment]
Please provide a full compilable test case.

**Comment by Kunderao** [comment]
I converted the project to go modules. It pulled the latest sources. Methods work fine now but accessing slices does not. Full test source below.

------------------------
package main

import (
	"fmt"
	"github.com/dop251/goja"
)


type str2 struct {
	A []float64
	B []float64
	C []float64
	D []float64
}

func( s *str2) GetMult(idx int) float64 {
	return s.A[idx] * s.B[idx]
}

func( s *str2) SayHello() string {
	return "Hello world\n"
}

func main() {

	mystr2:= str2{}

	mystr2.A=make([]float64, 100)
	mystr2.A[0]=0
	mystr2.A[1]=2
	mystr2.B=make([]float64, 100)
	mystr2.B[0]=0
	mystr2.B[1]=2

	fmt.Println("Run from go GetMult: ",mystr2.GetMult(1))


	vm := goja.New()

	var prg = "" +
		"//mystr2.GetMult(1);" +  //works
		"//mystr.SayHello();" +   //works
		"mystr2.A[0]"  //does not work

	vm.Set("mystr2", &mystr2)

	prgc, err := goja.Compile("prg1", prg, false)
	if err != nil {
		print(err.Error())
	}

    {
		runpg, err := vm.RunProgram(prgc)

		if err != nil {
			print(err.Error())
		}

		if runpg != nil {

			foo := runpg.Export().(interface{})
			fmt.Printf("\nFrom Runprogram: \n%v",foo)
		}
	}

	runString, err := vm.RunString(prg)

	if err != nil {
		panic(err)
	}


	fl := runString.Export().(interface{})

	fmt.Printf("\n from RunString: %v\n",fl)
}

**Comment by dop251** [comment]
You need to change this:

```go
var prg = "" +
	"//mystr2.GetMult(1);" +  //works
	"mystr2.A[0];" + //does not work
	"mystr2.SayHello();" //does not work
```

to 

```go
var prg = "" +
	"//mystr2.GetMult(1);\n" +  //works
	"mystr2.A[0];\n" + //works
	"mystr2.SayHello();" //works
```
Otherwise you are running the following string: "//mystr2.GetMult(1);mystr2.A[0];mystr2.SayHello();" which is treated as a comment line and you get `undefined` as a result.

**Comment by Kunderao** [comment]
Dop251. Makes sense. Thank you so much! In the rush to test things in quick succession, I missed that.
