### ISSUE TITLE
Preventing updates back to a golang variable

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#154]
Is there a way to prevent writing back to a golang variable from the Goja VM in script?
        var myway :=2;
	vm.Set("myvar", myvar)

Can I prevent write back to a variable from JS/Goja?
Such as:  'myvar=1'

Thank you.

**Comment by dop251** [comment]
Same rules as with Go apply: if you pass a pointer changes will affect the original, if you pass a value it's a copy and therefore changes will not affect the original.

In your example setting "myvar=1" in JS will not update Go variable.

**Comment by Kunderao** [comment]
Is there a way to make a pass by ref data structure like a Go Struct readonly in the goja VM? Pass by ref is faster I believe with by large structures. Also methods don't transfer when you user pass by value. Also when pass by ref only has to be done once.

Thank you

**Comment by dop251** [comment]
The only way I can think of is using ES6 Proxy which is available in `es6` branch. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy

**Comment by Kunderao** [comment]
Proxying is an interesting concept. However can it be done in Golang and sent to the Goja VM as a proxy?

**Comment by dop251** [comment]
Proxy is available in goja in the `es6` branch.

**Comment by Kunderao** [comment]
Would you add the Go variable to the VM and then execute a proxy wrapper in the VM as a secondary script? How would this be done?

**Comment by dop251** [comment]
You could either implement the proxy in Go and use (*Runtime).NewProxy() or implement the handler in JS, the latter would probably be easier as there is plenty of information online.
