### ISSUE TITLE
Benchmark against gopher-lua, is there any idea about improve goja's performance?

### ISSUE THREAD

**Issue by myrfy001** [dop251/goja#156]
Here is a bench with a pure go Lua 5.1 script engine, It show that goja's speed is far behind Gopher-lua.  The benchmark shows that goja has a lot of memory allocation than Gopher lua.

Gopher-lua is a good project and since it's written in go, there is no overhead for C-FFI, very suitable for a lot of function calls from script engine to the go code. but lua language is not popular among peoples(say it's array index starts from 1 ), I hope I can use javascript as an embedded script language in my go project. Goja is good for calling from script to native go, but the performance is not acceptable.

So, is there any plan / idea to improve the speed?

* Benchmark for Gopher-lua
```
package luabench

import (
	"strings"
	"testing"

	lua "github.com/yuin/gopher-lua"
	"github.com/yuin/gopher-lua/parse"
)

var (
	script = `
	for x=1,100000 do
	end
	`

	prog *lua.FunctionProto
	vm   *lua.LState
)

func CompileString(source string) (*lua.FunctionProto, error) {
	reader := strings.NewReader(source)
	chunk, err := parse.Parse(reader, "User Custom Lua Script")
	if err != nil {
		return nil, err
	}
	proto, err := lua.Compile(chunk, "User Custom Lua Script")
	if err != nil {
		return nil, err
	}

	return proto, nil
}

func init() {

	vm = lua.NewState(lua.Options{SkipOpenLibs: true})
	var err error = nil
	prog, err = CompileString(script)
	if err != nil {
		panic(err)
	}

}

func BenchmarkLua(b *testing.B) {

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		lfunc := vm.NewFunctionFromProto(prog)
		vm.Push(lfunc)
		vm.PCall(0, lua.MultRet, nil)

	}

}

```

* Benchmark for Goja
```
package jsbench

import (
	"testing"

	"github.com/dop251/goja"
)

var (
	script = `for (var x=0; x<100000; x++){}`

	prog *goja.Program
	vm   *goja.Runtime
)

func init() {
	prog, _ = goja.Compile("aaa", script, false)
	vm = goja.New()
}

func BenchmarkSample(b *testing.B) {

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		vm.RunProgram(prog)
	}

}
```

**Comment by dop251** [comment]
Short answer is 'no'. 

Long answer: It's not fair to compare against LUA in general, because LUA was designed to allow simple and efficient implementations whereas ECMAScript wasn't. I cannot see a way of improving goja's performance further without making the code much, much more complex for which I don't have time.
