### ISSUE TITLE
Converting a *string value to a JS value

### ISSUE THREAD

**Issue by Julio-Guerra** [dop251/goja#158]
Hello,

I was having issues with some JS execution until I realized that the JS value was created out of a Go `*string` string pointer value. It is indeed not converted the same way as a string value, and I think the JS code wasn't working because of a distinct API for the `*string` conversion.

Reading `ToValue()`'s code, it seems indeed not handled as a string, so I was wondering if this is intentional or if it is simply missing.

Thanks!

**Comment by dop251** [comment]
Pointers to primitive values are converted into objects which behave similar to ECMAScript String, Number or Boolean. Internally though they remain pointers so they track the original value, for example:

```go
	vm := New()
	s := "test"
	vm.Set("s", &s)
	res, err := vm.RunString(`s == "test"`) // note non-strict equality
	if err != nil {
		t.Fatal(err)
	}
	if v := res.ToBoolean(); !v {
		t.Fatalf("value: %#v", res)
	}
	s = "test1"
	res, err = vm.RunString(`s == "test1"`)
	if err != nil {
		t.Fatal(err)
	}
	if v := res.ToBoolean(); !v {
		t.Fatalf("value: %#v", res)
	}
```

**Comment by Julio-Guerra** [comment]
@dop251, I could isolate the problem to `typeof` which returns `"object"` and not `"string"`:

```
		vm := goja.New()
		s := "test"
		vm.Set("s", &s)
		res, err := vm.RunString(`typeof s`) // note non-strict equality
		if err != nil {
			t.Fatal(err)
		}
		if v := res.ToString().String(); v != "string" {
			t.Fatalf("value: %#v", res)
		}
```

**Comment by dop251** [comment]
As it should:
```
$ node
Welcome to Node.js v14.3.0.
Type ".help" for more information.
> typeof new String("test")
'object'
```

**Comment by Julio-Guerra** [comment]
Oh my... :sweat_smile: 
It looks like there's no simple solution to that (https://stackoverflow.com/questions/6286542/how-can-i-check-if-a-var-is-a-string-in-javascript).

I am going to convert my Go `*string` to `string` to avoid that.

Thanks for your time :muscle:

**Comment by dop251** [comment]
No problem. `instance of String` would work BTW.
