### ISSUE TITLE
(*vm).Interrupt causes a data race

### ISSUE THREAD

**Issue by nilium** [dop251/goja#16]
Per pull request #14, (*vm).Interrupt causes a data race. This results in undefined behavior and means that interrupts are currently unsafe to use. It can be resolved in the short term by using atomics (as in #14) or other explicit synchronization to signal the interrupt from a separate goroutine, and in the long term may be fixed in another manner.

As discussed in #14, it is unacceptable for a data race to be included in a critical part of a VM, especially as part of an interrupt. According to @dop251, the data race and undefined behavior here is intentional in the pursuit of performance, and objects to the use of atomics to resolve this. The goal, then, is to find another method of causing an interrupt that both satisfies @dop251's performance requirements (currently unstated) and eliminates the data race, preferably without introducing unsafe code that cannot be checked by the race detector.

This issue is intended to discuss other approaches to removing the interrupt data race, knowing that atomics are off the table (or somehow too slow).

**Comment by nilium** [comment]
@kirillDanshin you said you had something you could propose here in #14. Is that still the case?

**Comment by kirillDanshin** [comment]
@nilium first of all, we should try to use atomic bool instead of int32 or atomic.Value. I'll push one of my production implementations and send the link here.

**Comment by nilium** [comment]
@kirillDanshin There are no atomic bools in the stdlib, hence the uint32 (smallest, least ambiguous thing). Functionally, it should make little difference there, and I wouldn't want to add an atomic bool library dependency to goja to address a data race.

**Comment by Perelandric** [comment]
Has anyone verified that the `interrupted()` calls get inlined? I wonder if the atomic load somehow prevents it. Maybe manually inlining it would help.

The atomic load itself is implemented in assembly and looks to be just [a few instructions](https://github.com/golang/go/blob/master/src/sync/atomic/asm_amd64.s#L94-L98), so I wouldn't think that would make much difference.

**Comment by nilium** [comment]
I'll check the compiler output to see if it's inlining it. Wasn't my main concern in its addition, but will see if its spending more time than needed on call time for the interrupted method.

**Comment by Perelandric** [comment]
I tested a simple example, and it looks like it doesn't get inlined:

``` go
package test

import "sync/atomic"

type vm struct{
    halt bool
    interrupt uint32
    interruptVal string
}

func (vm *vm) test(s string) { 
    for !vm.halt && !vm.interrupted() { 
        vm.interruptVal = s 
    } 
}

func (vm *vm) interrupted() bool { 
    return atomic.LoadUint32(&vm.interrupt) != 0
    //return vm.interrupt != 0
}
```

Here's the result of `go build test.go -gcflags -m`

```
./test.go:18: &vm.interrupt escapes to heap
./test.go:17: leaking param: vm
./test.go:11: leaking param: vm
./test.go:11: leaking param: s
```

If the `return vm.interrupt != 0` is used instead then it gets inlined:

```
./main.go:17: can inline (*vm).interrupted
./main.go:12: inlining call to (*vm).interrupted
./main.go:11: leaking param: s
./main.go:11: (*vm).test vm does not escape
./main.go:17: (*vm).interrupted vm does not escape
```
So maybe dropping that method and writing it inline will help.

**Comment by nilium** [comment]
Finding the same. Running benchmarks with inlining it by hand.

**Comment by nilium** [comment]
I've thrown the benchmark output in a gist over here: https://gist.github.com/nilium/1deb990c193ad946d329d27c5e7202ef

Looks like there's a decent improvement for inlining it by hand, though there's some obvious jitter on it since this is running on my machine and I can't guarantee it's not going to be affected by sharing a playground with other processes on the system. The diff for inlining:

```diff
diff --git a/vm.go b/vm.go
index fe5e6ea..bdad864 100644
--- a/vm.go
+++ b/vm.go
@@ -278,11 +278,11 @@ func (vm *vm) init() {
 
 func (vm *vm) run() {
 	vm.halt = false
-	for !vm.halt && !vm.interrupted() {
+	for !vm.halt && atomic.LoadUint32(&vm.interrupt) == 0 {
 		vm.prg.code[vm.pc].exec(vm)
 	}
 
-	if vm.interrupted() {
+	if atomic.LoadUint32(&vm.interrupt) != 0 {
 		vm.interruptLock.Lock()
 		v := &InterruptedError{
 			iface: vm.interruptVal,
@@ -294,10 +294,6 @@ func (vm *vm) run() {
 	}
 }
 
-func (vm *vm) interrupted() bool {
-	return atomic.LoadUint32(&vm.interrupt) != 0
-}
-
 func (vm *vm) Interrupt(v interface{}) {
 	vm.interruptLock.Lock()
 	vm.interruptVal = v
```

**Comment by nilium** [comment]
@dop251 Any update on this?

**Comment by dop251** [comment]
The inlined version looks ok. In fact it produces exactly the same code on amd64 and nearly the same code on other platforms I tried with one extra simple instruction added. I'll do some final checks and commit.

**Comment by nilium** [comment]
In that case, I can reopen the pull request with the new commit.
