### ISSUE TITLE
Custom struct with extensible interface

### ISSUE THREAD

**Issue by ickby** [dop251/goja#160]
I'm using goja in a framework of mine with dynamically extensible types which are exposed also in JavaScript via goja. At runtime startup I can add methods and properties to my structs with a custom callback system, and than exposes the newly constructed structs to JS. Currently I achieve that by creating new objects in Goja (Runtime.NewObject()) and than adding the properties dynamically with setter/getter ("Object.DefineAccessorPRoperty()") and adding functions via "Object.Set()". This works very well. However, the problem comes with exporting back to Golang. Calling "Export()" on the corresponding value does of course not return my custom struct, but fails as it tries to export all Properties and Methods into a Map. ("cannot export value property"

I tried to workaround this by checking every "Value" if it represents one of my custom types and than use that instead. However, this comes to a limit with lists and maps which could hold my custom types. Maybe there is a better way of getting my custom struct by Export() than iterating all maps and lists to filter out custom types?

Note that I also cannot use the reflect type goja object, as this is not extensible at runtime with new Properties and Methods.

**Comment by dop251** [comment]
Not sure I understand, could you provide some code?

**Comment by ickby** [comment]
I tried to create a gist showing my general architecture, hopefully this is clearer: https://gist.github.com/ickby/e359b2c88661223394c26f9474e4e401

So the Test struct is what I want to expose to js, with all callbacks callable as native js functions. As callbacks are added at runtime I cannot use the reflect object goja provides, hence I fallback to fully setup a goja.Object for myself. But than I loose the backlink to my custom object, and "Export()" does return not what I want. Is there some way I can retain that backlinking, so that export return my type?

**Comment by dop251** [comment]
Add a "hidden" property to your *Object that contains the original struct, as such:

```go
jsObject.DefineDataProperty("__goExport", vm.ToValue(self), goja.FLAG_FALSE, goja.FLAG_FALSE, goja.FLAG_FALSE)
```

You can then `Get()` this property and call Export() on it which will return your original struct.

A more appropriate way would be using a `Symbol` which is available in the `es6` branch but it has not been exposed via Go API yet (which does not make it impossible, you'll just need to write a couple of functions in JS and call them from Go).

**Comment by ickby** [comment]
Thats a nice idea! I do something similar with identifiers and map lookups, but thats way more convoluted than you proposal. 

There is one problem, that is when the custom jsObject is used in composite types like lists or dicts. E.g. "[MyObject]" If I call Export() on a list goja calls "Export()" recursively on all its entries, same for dicts or other objects properties. This does than of course not work. The only workaround I can think of is to check each goja.Value not only for my custom struct, but also for lists and dicts and than Iterate myself into those. This seems to work, but feels very clunky and error prone (who knows if I anticipated all possible nesting types). So my hope was that there is a way to change the "Export" return value for a goja.Object somehow, to rely on the full logic implemented in goja itself.

**Comment by dop251** [comment]
No, there is no way to change Export's behaviour, so you'll need to replace it with your own version that would iterate over properties recursively which looks like what you are doing.

You could avoid this altogether by passing your original `struct` to JS as-is. It would change the way you call your methods (would be `MyObject.Callbacks.MyMethod()`), but you wouldn't have any issues with Export().

**Comment by ickby** [comment]
Ah I see, thats a bit unfortunate, but not too bad. Thanks for the info.

And by the way: nice peace of software, it works very well and is a pleasure to work with!

**Comment by dop251** [comment]
That's nice to hear, thank you 😄
