### ISSUE TITLE
Weird try bug 

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#161]
While debugging why a [k6](https://github.com/loadimpact/k6) script stopped working (thanks btw for the awesome JS VM :tada: ), I found that something very strange happens and was pretty sure it has something to do with `__proto__` and `setPrototypeOf`(as the problem was with a polyfill for it), but it turned out to have nothing to do with them it is just the end effect.  

After probably a couple of hours I managed to produce this k6 script (I also have a test for goja later on so no need to use k6 for debugging :)):
```javascript
var mod = {};
var f = function(){}
(function(module) {
    module.prop1 =function() {
        try {
            throw new Error("something");
        } catch (error) {
        }

        return function() {
            if (false) {
                f()
            }
            return true
        };
    }()
}(mod))

console.log(typeof mod.prop1);
```

which is the minimalist I could get it that still breaks. 
The problem is that mod.prop1 is "undefined" and not "function". This gets "fixed" if:
1. there is `var e = error` in the catch (or for that matter there is anything done with the error), but just `console.log("something")` isn't enough
2. the function being returned is ... simpler? I don't know how to explain it but if it doesn't have an `if` with something inside it - it doesn't trigger. 

I also produced a [test to catch](https://github.com/dop251/goja/commit/9ad12d6847a8416ecc1d7edd18936f306b58e8bb) this ... with hopes that I will fix it ... but it seems a little bit over my head :( 

My guess is that this is something with the stack getting borked, but can't tell you why any of the above "fixes" it :man_shrugging: 

For the record an update of goja in k6 just changed which parts of the polyfilled get executed, so it isn't anything new as far as I can tell and also is still broken in the es6 branch :( 
Also .. it might not be `try`, but it is what I have produced it with :(

**Comment by dop251** [comment]
Thanks for reporting this with a clear test case. I spotted the stack leak pretty quickly, what took most of the time is understanding why it worked elsewhere 😄

**Comment by MStoykov** [comment]
Thanks for fixing it so fast :D :tada:
