### ISSUE TITLE
*goja.Runtime as a persistent object, how to release the memory

### ISSUE THREAD

**Issue by yzpnet** [dop251/goja#163]
I create a *goja.Runtime pool,  get one to exec code each time.

code like this:
```
var runtimeObj := pool.getOne()
runtimeObj.Set("STDIN", stdin)
timer := time.AfterFunc(global.Config.JsEngine.ExecuteTimeout, func() {
	runtimeObj.Interrupt("javascript plugin execute timeout, system force interrupt")
})
defer timer.Stop()
if cache != nil {
	val, err = runtimeObj.RunProgram(cache.(*goja.Program))
} else {
	val, err = runtimeObj.RunString(code)
}
// 计算返回结果
stdout := runtimeObj.Get("STDOUT")
```

Variable stdin contains hundreds of data every time.

APP running after a period of time, memory continues to rise.

**Comment by yzpnet** [comment]
I found the source code is to use a map

**Comment by dop251** [comment]
Global variables naturally remain referenced for as long as the Runtime is referenced. Avoid them and if you can't, set them to Undefined() before returning the Runtime to the pool.

**Comment by theharveyz** [comment]
> I create a *goja.Runtime pool, get one to exec code each time.
> 
> code like this:
> 
> ```
> var runtimeObj := pool.getOne()
> runtimeObj.Set("STDIN", stdin)
> timer := time.AfterFunc(global.Config.JsEngine.ExecuteTimeout, func() {
> 	runtimeObj.Interrupt("javascript plugin execute timeout, system force interrupt")
> })
> defer timer.Stop()
> if cache != nil {
> 	val, err = runtimeObj.RunProgram(cache.(*goja.Program))
> } else {
> 	val, err = runtimeObj.RunString(code)
> }
> // 计算返回结果
> stdout := runtimeObj.Get("STDOUT")
> ```
> 
> Variable stdin contains hundreds of data every time.
> 
> APP running after a period of time, memory continues to rise.

请问`pool.getOne()`逻辑采用的是`sync.Pool`吗？
