### ISSUE TITLE
Disabling Assignment Operators

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#164]
Where in the code is it best to disable all assignment operators below? What is the most simplest way to disable the following from being recognized as valid operators? Thank you.

ADD_ASSIGN                     +=
SUBTRACT_ASSIGN                -=
MULTIPLY_ASSIGN                *=
QUOTIENT_ASSIGN                /=
REMAINDER_ASSIGN               %=
AND_ASSIGN                     &=
OR_ASSIGN                      |=
EXCLUSIVE_OR_ASSIGN            ^=
SHIFT_LEFT_ASSIGN              <<=
SHIFT_RIGHT_ASSIGN             >>=
UNSIGNED_SHIFT_RIGHT_ASSIGN    >>>=
AND_NOT_ASSIGN                 &^=
 ASSIGN                         =

**Comment by dop251** [comment]
Uhm... I don't know.. Probably write a Babel plugin (https://github.com/jamiebuilds/babel-handbook/blob/master/translations/en/plugin-handbook.md). But why?

**Comment by Kunderao** [comment]
Without going to the Es6 branch and utilizing proxy, I felt I can modify the code to disable the assignment operators so that I can have a readonly environment.

**Comment by dop251** [comment]
You don't necessarily need a Proxy, Object.freeze() may be enough: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze

**Comment by Kunderao** [comment]
This actually did the trick. dop251 this is simple and elegant and cheap solution. Thank you. I assume that once the code below is run in the runtime it is persistent until the runtime/vm is destroyed.

'use strict\n'
'Object.freeze(foo)'

**Comment by Kunderao** [comment]
I tried the following and freeze did not make the object immutable:

package main

import (
	"fmt"
	"github.com/dop251/goja"
)


var m3 = make(map[string]interface{})

func main() {

	m3["one"] = "foo3"
	m3["two"] = 2.3
	m3["three"] = 3.3

	vm := goja.New()
	vm.SetFieldNameMapper(goja.TagFieldNameMapper("json", true))

	var prg="'use strict';\n" +
			"Object.freeze(m3);\n"+
		    "m3.one='changed'\n"

	vm.Set("m3",&m3)

	runString, err := vm.RunString(prg)

	if err != nil {
		fmt.Printf("\nError from Runstring: \n%v", err.Error())
	} else {
		fl := runString.Export().(interface{})
		fmt.Printf("\nFrom RunString: %v\n", fl)
	}

}

**Comment by dop251** [comment]
Wrapped go maps obviously don't support it as they are literally just wrappers around normal go maps. You'll need to copy it into a js Object to make it work.

**Comment by Kunderao** [comment]
Just for giggles, I wanted to see how the Runtime maps a map access back to the original Go map. Where in source would that be?

Thank you.

**Comment by dop251** [comment]
Read through the project's file names and take a wild guess :)
