### ISSUE TITLE
Maps and Concurrent access

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#166]
If one defines a map in golang and assigns it to a Runtime as such:

``` go
var m3= make(map[string]interface{})
m3["one"] = "foo3"
m3["two"] = 2.3
m3["three"] = 3.3
vm.Set("m3", &m3)

var prg="'use strict';\n" +
	      "Object.freeze(m3);\n"+
	      "m3.one\n"

	vm.Set("m3",&m3)

runString, err := vm.RunString(prg)
```

considering maps in golang are not thread safe and require a mutex for concurrent access, 
how would one make sure this access is mutex is locked and unlocked  from a JS script from within the VM/Runtime?

Thank you.

**Comment by dop251** [comment]
You will need to either wrap the object using `Proxy` (in es6 branch) or lock the mutex before calling vm.Run*() or expose the mutex in JS and lock it from there.
