### ISSUE TITLE
RegExp

### ISSUE THREAD

**Issue by lujjjh** [dop251/goja#168]
Goja uses two regular expression libraries:
* `regexp`
* `github.com/dlclark/regexp2`

I found some behaviors that are inconsistent with JavaScript regular expression.

##  1.`lastIndex > 0` with `^` assertion

In both regexp wrappers, goja simply truncates the first `start` UTF-16 code units and calls the matcher.

https://github.com/dop251/goja/blob/f19759604c88e17c96c01c568e10ee1e5d0912ad/regexp.go#L30-L38

https://github.com/dop251/goja/blob/f19759604c88e17c96c01c568e10ee1e5d0912ad/regexp.go#L218-L221

This makes the first character of the truncated substring always the line start:

```js
'aaa'.match(/^a/g); // should return ['a'], actually ['a', 'a', 'a']
```

## 2. matches' `index` with `regexp2`

```js
var re = /(?=)a/; // a hack to use regexp2
re.exec('\ud83d\ude02a').index // should return 2, actually 1
```

## 3. `.` in `regexp`

```js
/./.exec('\ud83d\ude02')[0] // should return '\ud83d', actually '\ud83d\ude02'
```

**Comment by dop251** [comment]
Incidentally, I have been looking into this recently. Could you check this branch: https://github.com/dop251/goja/tree/regexp
It's still work in progress, but all the cases you've mentioned should work.
