### ISSUE TITLE
Calling golang function from the Vm

### ISSUE THREAD

**Issue by onthegit** [dop251/goja#169]
Hello, 

is it posssible to call golang function from inside the VM (javascript) and return value to the VM javascript?

**Comment by dop251** [comment]
Yes. See https://github.com/dop251/goja/blob/a695b0cdd4987b22f979a6f4d4ea30689058441a/runtime_test.go#L299 and https://github.com/dop251/goja/blob/a695b0cdd4987b22f979a6f4d4ea30689058441a/runtime_test.go#L236

The latter has better performance but requires your function to have a specific signature and requires you to do type conversions explicitly.

And in general, have a look at runtime_test.go, it has tons of useful usage examples.
