### ISSUE TITLE
ToValue doesn't convert time.Time to JS Date

### ISSUE THREAD

**Issue by slinkydeveloper** [dop251/goja#170]
As in the issue title, I stumbled on this issue where i'm trying to set a `time.Time` as variable in the engine:

```
func TestDate(t *testing.T) {
	vm := goja.New()
	vm.Set("time", time.Now())
	res, err := vm.RunString("time.getFullYear()")
	require.NoError(t, err)
	require.Equal(t, 2020, res.ToInteger())
}
```

```
=== RUN   TestDate
    filter_engine_test.go:44: 
        	Error Trace:	filter_engine_test.go:44
        	Error:      	Received unexpected error:
        	            	TypeError: Object has no member 'getFullYear' at <eval>:1:17(3)
        	Test:       	TestDate
--- FAIL: TestDate (0.00s)
```

**Comment by dop251** [comment]
Please see #72

**Comment by slinkydeveloper** [comment]
Thank you!

**Comment by slinkydeveloper** [comment]
I'm trying to use `vm.New(vm.GlobalObject().Get("Date").ToObject(vm), vm.ToValue(t.Unix()))` from golang side to create a `goja.Value`, but that doesn't seem to work. Is there something i'm overlooking?

**Comment by dop251** [comment]
Sorry, I forgot that `Unix()` returns seconds and the `Date` constructor requires milliseconds. So, you need `t.UnixNano()/1e6`

**Comment by slinkydeveloper** [comment]
That works fine, thanks! What about documenting it somewhere (like in the readme)? I can pr it if you want to
