### ISSUE TITLE
How stable is es6 branch?

### ISSUE THREAD

**Issue by abeMedia** [dop251/goja#172]
Hi @dop251, 

First of all thanks for such a great package!

I basically just have a question. I'm using goja in a production application and require certain es6 functions which you've already implemented in the es6 branch.

How likely is this branch to be buggy? Is it safe to use in production?

Thanks!

**Comment by abeMedia** [comment]
Sorry I should have read your readme as you already mentioned it's fairly stable...

**Comment by dop251** [comment]
I am going to merge es6 into master shortly, just need to update some documentation.
