### ISSUE TITLE
Support pre-1.14 versions of Go

### ISSUE THREAD

**Issue by nwidger** [dop251/goja#183]
Now that the es6 branch is merged into master, Go 1.14 or newer is needed to build goja.  From what I can tell, this is only due to the new dependency on the hash/maphash stdlib package that was added in 1.14.  Since I'm currently stuck in an environment using Go 1.13, I tried my hand at fixing this by adding a drop-in replacement github.com/dop251/goja/maphash package to allow building goja on older versions of Go.  [Here's a link to my branch](https://github.com/dop251/goja/compare/master...nwidger:prego1.14?expand=1).

For anyone using 1.14 or newer, github.com/dop251/goja/maphash uses type aliases to use the stdlib hash/maphash implementation, otherwise for older versions of Go it uses an adapted version of [this file](https://github.com/golang/go/blob/d571a77846dfee8efd076223a882915cd6cb52f4/src/hash/maphash/maphash.go).  The main change was to use math/rand.Uint64() and hash/crc64 instead of the builtin's runtime_fastrand/runtime_memhash functions.  I tried running the tests for both goja and goja_nodejs using both Go 1.13.14 and Go 1.14.7 with these changes in place and everything passed, but I haven't gone further than that yet.

I don't know if this is an acceptable change for you, but I figured it was worth a shot.  I don't know if you are planning to use other features that are only available in Go 1.14 or newer, or if maintaining a replacement package like this would be an unacceptable maintenance burden for you.  If it is acceptable, I'm happy to open a PR with my changes.

**Comment by dop251** [comment]
Why are you stuck with 1.13?

**Comment by nwidger** [comment]
I'm developing at Go package that's being built within the [OpenWRT](https://openwrt.org/) project.  The build system of 19.07.2, the current stable release, uses Go 1.13 and this isn't something I have the ability to change.  You can imagine my disappointment when ES6 and the Node.js search algorithm got merged and I found out I can't build goja anymore because of this! :tired_face:

**Comment by dop251** [comment]
Well, I'm sorry to say that, but I'm not going to support old versions of Go. Due to the compatibility promise upgrading should be a trivial task, especially in almost 6 months time since 1.14 was released. I suggest you open a ticket with OpenWRT and in the meantime use your branch. 1.14 is going to be a legacy version soon anyway, as 1.15 has just been released.

Also, if you're not linking against native libraries you may want to consider cross-compilation in which case you don't even need OpenWRT build system at all.

**Comment by nwidger** [comment]
I completely understand, and if I was in your place I'd likely make the same decision.  Thanks for the quick response.
