### ISSUE TITLE
Regexp match slower after es6 branch

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#185]
I am not really certain there is much to be done, and whether this shouldn't be a bug to the regexp2 library, but here it goes:
```golang
func BenchmarkRegexpMatch(b *testing.B) {
        const SCRIPT = `
        "a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
         a\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\ra\nb\r\c\nd\r\e\n\f\rg\nh\r\
        ".match(/[^\r\n]+/g)
        `
        b.StopTimer()
        prg, err := Compile("test.js", SCRIPT, false)
        if err != nil {
                b.Fatal(err)
        }
        vm := New()
        b.StartTimer()
        for i := 0; i < b.N; i++ {
                vm.RunProgram(prg)
        }
}
```
Comparing 043cf4f to 3cddd0f5 
```
name           old time/op    new time/op    delta
RegexpMatch-8     256µs ± 6%     965µs ± 2%   +277.23%  (p=0.008 n=5+5)

name           old alloc/op   new alloc/op   delta
RegexpMatch-8    45.6kB ± 0%  1024.2kB ± 0%  +2147.45%  (p=0.008 n=5+5)

name           old allocs/op  new allocs/op  delta
RegexpMatch-8     1.57k ± 0%     3.17k ± 0%   +101.65%  (p=0.008 n=5+5)
```

The difference increases with the size and it gets to the point that going over 60k lines previously took k6 around 0.2s and now takes over a minute and a half ...(btw I am not arguing that this is a good use of regexp ;) ) 

From my quick profile, it seems like goja always uses strings as UTF16 now which adds additional complexity and additional allocations, so maybe there is some room for improvement trying not to go UTF8<->UTF16 all that many times if possible. But I haven't really looked in-depth in the code so I can't really say if that is possible or if that is the real problem.

**Comment by dop251** [comment]
Bad news is that the change was necessary due to somewhat limited API that the standard Go regexp engine provides, see https://github.com/dop251/goja/blob/3cddd0f5c376675f7d3908051ec0150ce9157cb2/regexp.go#L113 and https://github.com/dop251/goja/blob/3cddd0f5c376675f7d3908051ec0150ce9157cb2/regexp.go#L137

Good news is that there is indeed room for improvement which I'm going to commit shortly. Unless you override standard properties of RegExp or of its prototype this should make it work even faster than the old version.

**Comment by MStoykov** [comment]
Thanks a lot :tada: 
My ...  unscientific test shows that with the same 60k lines we can parse it 100 times in 7.86s vs 11s of the old version ... so ... WAY better :D
