### ISSUE TITLE
Add git version tags for friendlier Go module support

### ISSUE THREAD

**Issue by tliron** [dop251/goja#187]
Currently, when using Go modules goja will appear in `go.mod` as something like this:
```
github.com/dop251/goja v0.0.0-20200818110326-5574b5dbd2b9
```
The way to fix this is simply to add tags using the Go semantic version format, e.g.:
```
git tag v1.0.45
```
I realize that this request can bring up the issue of proper versioning for goja, but I think it can be done without overthinking it for now. :) Simply bump the final "." number for every commit to master.

**Comment by dop251** [comment]
Not gonna happen, sorry.
