### ISSUE TITLE
Not checking for int overflows.

### ISSUE THREAD

**Issue by Riku32** [dop251/goja#197]
Goja does not check for int overflows, the code `new Array(1000000).fill(2^6)` should fail immediately on V8 or most JS runtimes but It does not and causes CPU usage to become very intense.

**Comment by dop251** [comment]
1. Why should it fail immediately when creating an 8Mb array?
2. V8 doesn't fail.
3. Neither does goja.
4. Increasing the size eventually causes problems, but for both V8 and goja. There is nothing in ECMAScript specification as far as I could see that would mandate failing on such operations.
5. There are no integer overflows here.
