### ISSUE TITLE
Check if something is still running. Kill the VM?

### ISSUE THREAD

**Issue by Riku32** [dop251/goja#198]
Can we check if something is still running so maybe we can have a limited runtime time? So we could maybe check if the thing is finished executing? That also applies to the event loop. On top of that can we have something to just stop the execution mid-process?

**Comment by nwidger** [comment]
I don't know if this has been suggested previously, but I think one way to allow limiting the runtime would be to add context support to goja.  Something like:

``` go
func (r *Runtime) RunProgramContext(ctx context.Context, p *Program) (result Value, err error)
func (r *Runtime) RunScriptContext(ctx context.Context, name, src string) (Value, error)
func (r *Runtime) RunStringContext(ctx context.Context, str string) (Value, error)

func (f ConstructorCall) Context() context.Context // or a Context field perhaps
func (f FunctionCall) Context() context.Context    // or a Context field perhaps
```

The three new RunXXXContext methods would function exactly like their existing RunXXX counterparts but would stop execution if the context is canceled, perhaps returning ctx.Err().  If a RunXXX method is called, the runtime's context would be set to context.Background().  The Context methods on ConstructorCall/FunctionCall would be used by native Go code to detect cancellation and return.  Finally, ToValue could be updated to support passing in the runtime's context if a wrapped function's first argument is a context.Context.

@dop251 Is a feature like this something you would consider merging?  If so I'd be happy to take a stab at it.

**Comment by dop251** [comment]
Have you checked the Interrupt method (https://github.com/dop251/goja#interrupting)?

**Comment by nwidger** [comment]
@dop251 I have but as far as I know the Interrupt method doesn't provide a solution for stopping execution if a native Go function is running (which includes all built-ins), is that correct?

**Comment by dop251** [comment]
Yes. But how is your proposal going to do any differently? You'd have to add the context checking to a lot of places in the built-ins to make it effective. Instead you could just as well add checking for the interrupted flag, but I'm not sure I like the idea in general.

**Comment by nwidger** [comment]
I agree, if the interrupted flag was made accessible that could be used by native Go functions to stop executing.  But I think there is value in making goja integrate nicely with the context package, given that it's the officially designated tool to use for deadlines and cancellation.  What do you think?

**Comment by dop251** [comment]
I think Context is the second worst thing in Go after error handling 😞 It makes APIs bloated and more difficult to understand. It's inefficient because in order to check for cancellation you have to do a channel read which is relatively costly. And it assumes the recipient would do the right thing and check for cancellations, however it's not obliged to do so.

**Comment by nwidger** [comment]
Fair enough.  Do you see value then in giving native Go functions (including those defined in other packages) access to the interrupted flag somehow?

**Comment by dop251** [comment]
Yes, could be useful.

**Comment by noctarius** [comment]
I handled it with capturing the context from the surrounding scope when defining the method for the runtime.
