### ISSUE TITLE
nil pointer dereference in VM execution

### ISSUE THREAD

**Issue by Mischanix** [dop251/goja#20]
Reproduction js:
```js
(function(){
	console.log("test");
	function x(a, b) {
		if (a || b) return 1;
		return 0;
	}

	function y(b) {
		return [].concat(Array.prototype.slice.call(arguments))
	}

	x.apply(this, y(void 0, 1));
})();
```

FunctionCall.Arguments that goes to x ends up having nil instead of undefined.

**Comment by mkg0** [comment]
i just had same error and this fixed it ^^
thank you -and the author also-

**Comment by dop251** [comment]
Thanks for reporting this. The Arguments array will not normally contain nils, if that happens it's better to fix the place that is causing it. I'm going to push the fix shortly.

**Comment by dop251** [comment]
On a second thought... It may also arrive via the API, so your fix is actually correct.
