### ISSUE TITLE
Adding public library

### ISSUE THREAD

**Issue by Kunderao** [dop251/goja#204]
What is the most efficient way to add a public library such as lodash in to a VM? Thank you.
https://raw.githubusercontent.com/lodash/lodash/4.17.15-npm/lodash.js

**Comment by dop251** [comment]
I'm not sure what you mean by "add". Just run it using `RunString` or, if you have many runtimes, compile it first using `Compile` and then run using `RunProgram`.

**Comment by Kunderao** [comment]
dop251. Thank you for you reply. I would simply like to add this file and its functions into the VM so that I can reuse the VM over and over again and make the lodash functions available to compiled JS programs/snippets to access. So the above file is not the program but simply a library of functions that I want to make available in the VM itself to actual programs that will be run with RunProgram or RunString.

**Comment by dop251** [comment]
There is nothing special about this file. It's a javascript code that, when evaluated, defines and exposes certain objects and functions that represent the functionality. If you look at the very end of the file you can see exactly how it's done.
