### ISSUE TITLE
Travis Jobs failing on PPC64LE architecture

### ISSUE THREAD

**Issue by kishorkunal-raj** [dop251/goja#217]
Hi All,
I am using Travis-ci to run jobs on "Linux on Power" (ppc64le) architecture but the job for Go: 1.x & GIMME_ARCH=386 is failing and exited with 1. Below are the logs:

Setting environment variables from .travis.yml

$ export GIMME_ARCH=386

108.59s$ travis_setup_go

go version go1.15.3 linux/ppc64le

$ export GOPATH="/home/travis/gopath"

$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.15.3.src/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.rvm/gems/ruby-2.7.0/bin:/home/travis/.rvm/gems/ruby-2.7.0@global/bin:/home/travis/.rvm/rubies/ruby-2.7.0/bin:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.kiex/elixirs/elixir-1.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin"

$ export GO111MODULE="auto"

$ gimme version

v1.5.4

$ go version

go version go1.15.3 linux/ppc64le
go.env

$ go env
before_install.1

0.00s$ mkdir -p $GOPATH/src/github.com/dop251/
before_install.2

0.00s$ ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/dop251/ || true
install

13.72s$ travis_install_go_dependencies 1.x -v

0.31s$ diff -u <(echo -n) <(gofmt -d .)

The command "diff -u <(echo -n) <(gofmt -d .)" exited with 0.

4.58s$ go vet .

The command "go vet ." exited with 0.

4.60s$ go test -short $RACE ./...

fork/exec /tmp/go-build674018733/b001/goja.test: exec format error

FAIL	github.com/kishorkunal-raj/goja	0.002s

?   	github.com/kishorkunal-raj/goja/ast	[no test files]

?   	github.com/kishorkunal-raj/goja/file	[no test files]

fork/exec /tmp/go-build674018733/b091/ftoa.test: exec format error

FAIL	github.com/kishorkunal-raj/goja/ftoa	0.003s

?   	github.com/kishorkunal-raj/goja/ftoa/internal/fast	[no test files]

?   	github.com/kishorkunal-raj/goja/goja	[no test files]

fork/exec /tmp/go-build674018733/b108/parser.test: exec format error

FAIL	github.com/kishorkunal-raj/goja/parser	0.003s

?   	github.com/kishorkunal-raj/goja/token	[no test files]

?   	github.com/kishorkunal-raj/goja/unistring	[no test files]

FAIL

The command "go test -short $RACE ./..." exited with 1.

Done. Your build exited with 1.

Travis Job ID: https://travis-ci.com/github/kishorkunal-raj/goja/jobs/402447388

Please have a look & provide your suggestions.

Thanks in advance!

**Comment by dop251** [comment]
GIMME_ARCH=386 builds it for 32bit Intel architecture. I use it because native Travis lacks native support for it. It won't work on any of the supported Travis architectures other than amd64. You need to make sure unsupported combinations are excluded from the build matrix.
