### ISSUE TITLE
Ordered objects?

### ISSUE THREAD

**Issue by uppfinnarn** [dop251/goja#22]
Is there any chance we could have objects preserve insertion order in goja? The ES spec no longer mentions if objects should be ordered or unordered, but Chrome, Firefox and Node all preserve insertion order.

Test script:

```js
let obj = {"a": 1, "b": 2, "c": 3}
for (key in obj) { console.log(key) }
```

**Comment by dop251** [comment]
Hm... I thought it was already preserving the order. It is indeed not part of ES5.1, but since it's common behaviour goja should conform. I'll take a look a bit later.

**Comment by dop251** [comment]
I tried running this and I'm getting a, b, c. Not sure what is the problem.

**Comment by uppfinnarn** [comment]
Ah, my bad, I was looking at Go `Object` instances and made a poorly verified assumption about the JS-side behavior. There's no `Keys()` function, and the only way to access the list of keys is to export it into an unordered `map[string]interface{}`.

**Comment by Perelandric** [comment]
@uppfinnarn The ordering requirements (or lack thereof) of a `for-in` statement hasn't changed. Before ECMAScript 6, it was implementation defined, and it still is. Code shouldn't rely on any sort of ordering that follows the [Enumerate](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-enumerate) semantics.

**Comment by dop251** [comment]
@uppfinnarn There is now.

**Comment by uppfinnarn** [comment]
👍 

@Perelandric Generally speaking, I agree with you, but in this case I'm working with an application-specific DSL, not portable code.
