### ISSUE TITLE
throwing an Exception within Runtime

### ISSUE THREAD

**Issue by konethmelathil** [dop251/goja#222]
Dop251, 
Thank you for the great work.

If you have a external function defined such as:

``` go

vm := goja.New()
vm.Set("getitem",getitem)

var prog = "getitem('foo');\n" //foo does not exist!
ran,err := vm.RunProgram(prgcl)

func getitem(name string) interface{} {
// get named item from somewhere and return
// if it doesn't exist throw an exception up to RunProgram so it can be picked up by RunProgram
}

```
How can I throw an error up to vm.Runtime if the item "name" does not exist instead of failing silently?

Thank you

**Comment by konethmelathil** [comment]
Found the answer:

put   panic(vm.ToValue("Error")) in the function. However the error message adds extraneous info in the message such as
" at source/foobar.func1 (native)."
Can that be suppressed?

**Comment by dop251** [comment]
The resulting exception will be of type `GoError` and will have a `value` property containing the original value. See https://github.com/dop251/goja/blob/e21ccf39bfce8045562435deacb82e5ebff5a494/runtime_test.go#L876 for more details.
