### ISSUE TITLE
Improve SEO by referencing plausible search phrases somewhere in the README

### ISSUE THREAD

**Issue by finnbear** [dop251/goja#223]
I could not find this repository on the first page of Google or DuckDuckGo with the query "run javascript in go" or "go javascript." I only found v8go and otto (an issue on which led me to this repository). Therefore, I suggest you modify the description of this repository in the README to include phrases like the above. The biggest issue is that search engines don't seem to associate JavaScript with ECMAScript, so I suggest you use the word JavaScript in your description (regardless of technical correctness).

**Comment by dop251** [comment]
I have also changed the repository description. Hope this helps.

**Comment by septs** [comment]
https://github.com/avelino/awesome-go/pull/3230
