### ISSUE TITLE
when Runtime.RunScript(filepath, ""), can't read the script file

### ISSUE THREAD

**Issue by evildao** [dop251/goja#226]
when Runtime.RunScript(filepath, ""), can't read the script file

`parser/parser.go` line 100

```go
func ReadSource(filename string, src interface{}) ([]byte, error) {
	if src != nil {
		switch src := src.(type) {
		case string:
			return []byte(src), nil
		case []byte:
			return src, nil
		case *bytes.Buffer:
			if src != nil {
				return src.Bytes(), nil
			}
		case io.Reader:
			var bfr bytes.Buffer
			if _, err := io.Copy(&bfr, src); err != nil {
				return nil, err
			}
			return bfr.Bytes(), nil
		}
		return nil, errors.New("invalid source")
	}
	return ioutil.ReadFile(filename)
}
```

src can't to set nil

**Comment by dop251** [comment]
Sorry, I don't understand.

**Comment by evildao** [comment]
![搜狗截图20201204093650](https://user-images.githubusercontent.com/6054838/101110690-7e3b6680-3614-11eb-90ef-f8e5095d6396.png)

**Comment by dop251** [comment]
I don't see a problem. Please provide either a failing test case illustrating the desired behaviour or a pull request implementing it.

**Comment by gongcf** [comment]
goja source: parser.go
`
func ReadSource(filename string, src interface{}) ([]byte, error) {
	if src != nil {
....

`
src is will never be nil

> I don't see a problem. Please provide either a failing test case illustrating the desired behaviour or a pull request implementing it.
