### ISSUE TITLE
access to hrtime

### ISSUE THREAD

**Issue by RichardWright** [dop251/goja#230]
Hi

Via the k6 project, the following line fails 

`const now = process.hrtime.bigint();`

`ReferenceError: process is not defined\n\tat file:///tmp/socket-test.js:63:19(93)\n\tat github.com/loadimpact/k6/js/common.Bind.func1 (native)\n\tat _default (file:///tmp/socket-test.js:42:33(50))\n" executor=ramping-vus scenario=default source=stacktrace`

What's the recommended way of accessing nanosecond time via goja?

**Comment by dop251** [comment]
`process` is not a part of ECMAScript standard, therefore goja does not support it. If you were working with goja directly there would be a way, however you are not, so this question is best directed to the k6 dev team.

Also note, goja does not support BigInt.
