### ISSUE TITLE
Major Issue with Interpretor

### ISSUE THREAD

**Issue by konethmelathil** [dop251/goja#236]
There seems to be a serious error where goja ignores symbol/variables error after the && operator. It does not happen with the || operator.

**SDlcs** should be rejected as it is does not exist. It is **Slcs**.

Using github.com/dop251/goja v0.0.0-20201212162034-be0895b77e07
``` go
package main

import (
	"fmt"
	"github.com/dop251/goja"
)

var m3 = make(map[string]interface{})

type substr struct {
	Sen  float64 `json:"Sen"`
	Sang float64 `json:"Sang"`
}
type str struct {
	Slcs []substr `json:"Slcs"`  //<<<<< defined here
}

func main() {

	var Str = str{[]substr{{1, 2}, {2, 3}}}   //<< instantiated here

	m3["one"] = "foo3"
	m3["two"] = 2.3
	m3["three"] = 3.3
	m3["four"] = Str  //<< assigned to m3.four here


	vm := goja.New()
	vm.SetFieldNameMapper(goja.TagFieldNameMapper("json", true))

	var prg = []string{
		"m3.four.Slcs[1].Sen<1 && m3.four.Sldcs[0].Sang<1 \n", //ignores but should not
		"m3.four.Sldcs[1].Sen<1 && m3.four.Slcs[0].Sang<1 \n",   //flags as error
		"m3.four.Slcs[1].Sen<1 && m3.four.SlDcs[0].Sang<1 \n",  //ignores but should not
		"m3.four.Slcs[1].Sen<1 || m3.four.SlDcs[0].Sang<1 \n",  //flags as error
	}

	vm.Set("m3", &m3)


	for  i:= 0; i<len(prg); i++{
		fmt.Printf("\nRun %d\n", i)
		runString, err := vm.RunString(prg[i])

		if err != nil {
			fmt.Printf("\nError from Runstring: \n%v", err.Error())
		} else {
			fl := runString.Export()
			if fl != nil {
				fl2 := fl.(interface{})
				fmt.Printf("From RunString: %v\n", fl2)
			} else {
				fmt.Printf("From RunString: nil\n")
			}

		}
	}
}

```

output:

Run 0
From RunString: false

Run 1

Error from Runstring: 
TypeError: Cannot read property '1' of undefined at <eval>:1:15(4)
Run 2
From RunString: false

Run 3

Error from Runstring: 
TypeError: Cannot read property '0' of undefined at <eval>:1:26(14)
Process finished with exit code 0

**Comment by dop251** [comment]
> There seems to be a serious error where goja ignores symbol/variables error after the && operator. It does not happen with the || operator.
> 
> **SDlcs** should be rejected as it is does not exist. It is **Slcs**.

No it shouldn't. See https://www.ecma-international.org/ecma-262/#sec-binary-logical-operators-runtime-semantics-evaluation
