### ISSUE TITLE
Evaluations performance decreases with more variables in a single struct

### ISSUE THREAD

**Issue by konethmelathil** [dop251/goja#238]
I am facing a performance issues where if the variable struct being introduced into the environment has an increasing number of variables then the performance of the evaluations go down. What is weird is that if some of the slices are not instantiated the performance is better even if they are not part of any evaluations. This is a theoretical question to dop251 as to what could be causing this and is there anything I can do to minimize performance issues when introducing more variables to the struct below. And I plan to instantiate all the slices. 

Or simply what is the correlation to variable count in the struct that is instantiated vs non-instantiated or even the number of variables in the struct and performance decrease. Please note that these become more evident at high rates.

 Thanks in advance.

``` go
type foo struct {
A []float64 `json:"a"`
B []float64 `json:"b"`
C []float64 `json:"c"`
D []float64 `json:"d"`
E []float64 `json:"e"`
}

A=make([]float,5)
B=make([]float,5)
C=make([]float,5)
//D=make([]float,5)
//E=make([]float,5)

vm.SetFieldNameMapper(goja.TagFieldNameMapper("json", true))
vm.Set("foo", &foo)

```

**Comment by dop251** [comment]
It is difficult to say based on the information you have provided. Can you share some benchmark code?
