### ISSUE TITLE
Missing Object.assign member

### ISSUE THREAD

**Issue by tanis2000** [dop251/goja#24]
I have a piece of JS code that does the following:

```
    var a = Object.assign({}, state, {
      isAuthenticating: false,
    });
```

where `state` is an empty object, and even though it runs fine in the browser when bundled, it fails running that same bundle in goji with the following error:

```
TypeError: Object has no member 'assign'
```

**Comment by dop251** [comment]
Object.assign() is not part of ES5.1. If you want to run ES2016 code you may want to use Babel with appropriate polyfill plugins (in your case, this one might work: https://babeljs.io/docs/plugins/transform-object-assign/)

**Comment by tanis2000** [comment]
I thought about that.. but it turns out that the babel plugin is actually turning:

```
Object.assign(a, b);
```

into

```
var _extends = ...;

_extends(a, b);
```

and that doesn't really look much ES5.1 as well..

**Comment by dop251** [comment]
It does to me. Have you actually tried it?

**Comment by Perelandric** [comment]
@tanis2000 

I think you're taking the `var _extends = ...;` too literally. Pretty sure the `...` is meant to represent whatever the polyfill puts in its place.

Having `...` as an expression isn't valid in any version of ES.

**Comment by tanis2000** [comment]
You guys are right. I took it literally for the spread operator. I tried it and it works so it's definitely not literally that :)
Cheers!
