### ISSUE TITLE
Question: Some questions about spread syntax

### ISSUE THREAD

**Issue by zbysir** [dop251/goja#241]
1. Is goja going to implement spread [Spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) in the near future?
2. I'm trying to implement it and submit contributions, but I need your help: Should ArrayLiteral's spread operation be at compile time or at runtime? Can you tell me where I can find the relevant code (in any language)?

**Comment by dop251** [comment]
All ECMAScript features are in scope, however I cannot give any estimates. As for the spread syntax, I haven't looked into it yet, so can't answer your question. When implementing a new feature you should follow the specification: http://www.ecma-international.org/ecma-262/. Sometimes it also helps to look at the relevant tc39 tests: https://github.com/tc39/test262

**Comment by zbysir** [comment]
thank you :smiley:
