### ISSUE TITLE
Techniques for Handling Interfaces

### ISSUE THREAD

**Issue by vishalkuo** [dop251/goja#242]
A basic working example to illustrate:
```golang
package main

import (
	"fmt"

	"github.com/dop251/goja"
)

type S struct {
	Test int
}

type myInt interface {
	Foo() int
}

func (s *S) Foo() int {
	return s.Test
}

func main() {
	vm := goja.New()
	v, _ := vm.RunString(`
		var s = {
			Test: 4		
		}
		s
	`)
	s := &S{}
	vm.ExportTo(v, s)
	fmt.Printf("%d\n", s.Test)
}
```

Right now, in order to coerce the `RunString` output value into a golang struct, we'd have to know ahead of time that it's an instance of `*S`. I was wondering if there were techniques for dealing with the output being one of several implementations of `myInt`. The only thing I can thing of is every struct that implements myInt must also have a `Tag`/`Type` field indicating what golang struct to use and then to switch on that tag field when exporting the goja Value. 

I was curious if there are better ways to achieve what I'm looking for or if this is the best method.

**Comment by dop251** [comment]
I'm not entirely sure what you mean... If a `Value` is a wrapped Go implementation of an interface it can be exported into an interface variable:
```go
	vm := New()
	val := vm.ToValue(&S{})
	var exp myInt
	err := vm.ExportTo(val, &exp)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := exp.(*S); !ok {
		t.Fatal(exp)
	}
``` 
If you are exporting a plain JS object, there is no way of telling which implementation you want it to export to. The choice must be made explicitly either in Go or in JS. In the former case you can use the technique as above. In the latter case you could expose a constructor function and return the result of it to the Go side:

```go
vm.Set("newS", func(/*...*/) *S {
    return &S{/*...*/}
}
res, err := vm.RunString(`newS(/*...*/)`)
// handle err
var exp myInt
err = vm.ExportTo(val, &exp)
// ....
```

**Comment by vishalkuo** [comment]
Yep - I was doing something wrong here, I was conflating how k6 used goja with goja features themselves. Thanks!
