### ISSUE TITLE
Is it possible to trace every function called in JS script?

### ISSUE THREAD

**Issue by panzhongxian** [dop251/goja#249]
I know how to dump the stack when a exception is throwed out in #28 . 
Is there any method that could help me to know all functions I have called?

For example, as the following JS script:

```js
function a_func() {
    throw("Test");
}
function b_func(){
    a_func();
}
function c_func(){
    b_func();
}
c_func();
```

I want to return the string array like:

```
enter func => c_func (<eval>:9:10(2))
enter func => b_func (<eval>:6:10(2))
enter func => a_func (<eval>:3:10(2))
exit func <= a_func (<eval>:3:10(2))
exit func <= b_func (<eval>:6:10(2))
exit func <= c_func (<eval>:9:10(2))
```

Is there any mothod to do this?

Or how could we write a new function (maybe naming like `RunStringWithTrace`) based on `RunString`, which return three variables. The third one will bring out the functions' traces. Do you have any advice?

Thanks.

**Comment by dop251** [comment]
It depends. There is no way to blanket trace every single function call, but if you have an option to wrap the functions you could use Runtime.CaptureCallStack() in the wrapper to get the position of the call. Hope this helps.

**Comment by panzhongxian** [comment]
Thanks for your reply. I read the code and find a way to trace all functions (although I think "tracing all functions called" is an ugly idea  :sob: )

I add an logging line in `func (vm *vm) run()`  before `vm.prg.code[vm.pc].exec(vm)`:

```golang
fmt.Printf("vm.prg.code[vm.pc]: %T, %+v\n", vm.prg.code[vm.pc], vm.prg.code[vm.pc])
```

When I call `RunString()`, the output looks like:

```diff
- vm.prg.code[vm.pc]: goja.getVar1Callee, c_func
- vm.prg.code[vm.pc]: goja.call, 0
- vm.prg.code[vm.pc]: goja.enterFuncStashless, {stackSize:0 args:0}
+ vm.prg.code[vm.pc]: goja.getVar1Callee, b_func
+ vm.prg.code[vm.pc]: goja.call, 0
+ vm.prg.code[vm.pc]: goja.enterFuncStashless, {stackSize:0 args:0}
! vm.prg.code[vm.pc]: goja.getVar1Callee, a1_func
! vm.prg.code[vm.pc]: goja.call, 0
! vm.prg.code[vm.pc]: goja.enterFuncStashless, {stackSize:0 args:0}
! vm.prg.code[vm.pc]: goja._loadUndef, {}
! vm.prg.code[vm.pc]: goja._retStashless, {}
! vm.prg.code[vm.pc]: goja._pop, {}
@@ vm.prg.code[vm.pc]: goja.getVar1Callee, a2_func @@
@@ vm.prg.code[vm.pc]: goja.call, 0 @@
@@ vm.prg.code[vm.pc]: goja.enterFuncStashless, {stackSize:0 args:0} @@
@@ vm.prg.code[vm.pc]: goja._loadUndef, {} @@
@@ vm.prg.code[vm.pc]: goja._retStashless, {} @@
@@ vm.prg.code[vm.pc]: goja._pop, {} @@
+ vm.prg.code[vm.pc]: goja._loadUndef, {}
+ vm.prg.code[vm.pc]: goja._retStashless, {}
+ vm.prg.code[vm.pc]: goja._pop, {}
- vm.prg.code[vm.pc]: goja._loadUndef, {}
- vm.prg.code[vm.pc]: goja._retStashless, {}
- vm.prg.code[vm.pc]: goja._halt, {}
<nil>
```

I divided the logging line into 4 groups with different color. And I found all the function calls will cost 6 loop. If the `vm.prg.code[vm.pc]` were `goja.getVar1Callee`, I record "enter {function name}" and meanwhile push the funciton name to a stack; if the `vm.prg.code[vm.pc]` were `goja._retStashless`, I record "exit {function name}" and meanwhile pop the function name from the stack mentioned before. All the records will be store in list. After calling `RunString()`, users can fetch all the records.

Is there any problem with this implementation?

**Comment by panzhongxian** [comment]
I push a commit to my forked repos. https://github.com/panzhongxian/goja/commit/86444bf18acf209a09740fd342ff5251eebfab15

```golang
package main

import (
        "fmt"
        js "github.com/panzhongxian/goja"
)

func main() {
        vm := js.New()

        // Enable function trace.
        vm.SetRecordFuncCallFlag(true)
        const SCRIPT = `
        function a1_func() {
        }
        function a2_func() {
        }
        function b_func(){
          a1_func();
          a2_func();
        }
        function c_func(){
            b_func();
        }
        c_func()
        `
        vm.RunString(SCRIPT)

        // Fetch function trace.
        for _, record := range vm.FetchCalledFuncRecord() {
                fmt.Printf("%+v\n", record)
        }
}
```

Output:

```
{funcName:c_func depth:0 action:enter}
{funcName:b_func depth:1 action:enter}
{funcName:a1_func depth:2 action:enter}
{funcName:a1_func depth:2 action:exit}
{funcName:a2_func depth:2 action:enter}
{funcName:a2_func depth:2 action:exit}
{funcName:b_func depth:1 action:exit}
{funcName:c_func depth:0 action:exit}
```

**Comment by dop251** [comment]
This is not the best way of doing it, have a look at func.go, it's better to add tracing points to where calls are actually made.

In any case I don't think this this feature can be included main codebase, it's too specific and it impacts performance (albeit slightly).
