### ISSUE TITLE
Const causes "Unexpected reserved word" when using new

### ISSUE THREAD

**Issue by clarkmcc** [dop251/goja#258]
The following code works great
```javascript
var foo = require('foo')
var foos = [
    new foo.Bar()
]
```

but changing the var to const returns the error "Unexpected reserved word" and the provided line and column reference is for the "new" keyword.

```javascript
var foo = require('foo')
const foos = [
    new foo.Bar()
]
```

Let me know if any more information is needed.

**Comment by PaluMacil** [comment]
There is a branch for let and const work, but since these were not present in es5.1, goja didn't originally support them.

**Comment by dop251** [comment]
Most of the syntax enhancements of ES6 are not implemented yet (unlike built-ins which are mostly done). If you need them, use https://babeljs.io/

Specifically for let and const see #179.

**Comment by clarkmcc** [comment]
@dop251 Thanks. I see from the readme that goja can run the typescript compiler. Theoretically then I can feed typescript to goja and have it to the rest? Do you have anymore documentation on this? I couldn't find much.
