### ISSUE TITLE
Calling .shift() on a Go slice fails

### ISSUE THREAD

**Issue by sesposito** [dop251/goja#262]
I stumbled upon the following error: `TypeError: Can't delete from Go slice at shift (native)` upon calling `.shift()` on an array that was set in Go, so I wrote the following tests:

```
func TestGoSliceShift(t *testing.T) {
	const SCRIPT = `
	a.shift();
	`
	r := New()
	r.Set("a", []interface{}{1, 2, 3, 4})
	_, err := r.RunString(SCRIPT)
	if err != nil {
		t.Fatal(err)
	}
}

func TestJsArrayShift(t *testing.T) {
	const SCRIPT = `
	a = [1, 2, 3, 4];
	a.shift();
	`
	r := New()
	v, err := r.RunString(SCRIPT)
	if err != nil {
		t.Fatal(err)
	}
	println(v.String())
}
```

Running them I see the first one fails, but the second doesn't. Replacing [this line](https://github.com/dop251/goja/blob/master/object_goslice.go#L270) with something like:

```
	(...)
	s := *o.data
	ns := append(s[:idx], s[idx+1:]...)
	o.data = &ns
	(...)
```

Fixes `TestGoSliceShift`. I'll gladly open a PR to fix this, but I figured I'd open an issue first to understand if there's any side effects applying the above change that I'm not envisioning.

**Comment by dop251** [comment]
This is not how deleting from arrays works in ECMAScript. And the way it does work is not possible to emulate with Go slices, see my comment in #253.

Having said that, this particular case (`Array.prototype.shift`) theoretically could be supported as long as the Go slice is addressable (i.e. when `sliceExtensible` is set to `true`). This support would need to be added to `arrayproto_shift`. I will consider a PR.

**Comment by dop251** [comment]
It should work now, however you need to make sure you pass a pointer to a slice, otherwise it will fail on trying to set the length.
