### ISSUE TITLE
Implement spread

### ISSUE THREAD

**Issue by zedd3v** [dop251/goja#272]
Feature request

**Comment by Bessonov** [comment]
It would be very nice, if the two plugins weren't needed: https://github.com/k6io/template-typescript/blob/master/.babelrc#L6

Discovered this issue after adding [luxon](https://github.com/moment/luxon) to [k6](https://github.com/k6io/k6) test file.

**Comment by dop251** [comment]
Should be fixed by #303

**Comment by Bessonov** [comment]
Hey @dop251 , thank you very much!
