### ISSUE TITLE
Possible regression after the block scoping PR

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#273]
Before f3cfc97 :
```golang
package goja

import (
        "fmt"
        "testing"
)

func TestStrange(t *testing.T) {
        vm := New()
        f := func() Value {
                v, err := vm.RunString(`"use strict";(function() {
                                var a = s();
                                var b;
                                return function () {
                                        return a();
                                }
                        })()`)
                if err != nil {
                        t.Fatalf(err.Error())
                }
                return v
        }

        vm.Set("f", vm.ToValue(f))

        s := func() Value {
                v, err := vm.RunString(`"use strict";(function() {
                                return function() {
                                        return b={p:5};
                                };
                        })()`)
                if err != nil {
                        t.Fatalf(err.Error())
                }
                return v
        }
        vm.Set("s", vm.ToValue(s))
        vm.Set("log", vm.ToValue(func(s string) { fmt.Println(s) }))
        _, err := vm.RunString(`"use strict";
                var c = f();
                log(c());
        `)
        if err != nil {
                t.Fatalf(err.Error())
        }
}
```

Would "work" but after it will say:

```
    strange_test.go:44: ReferenceError: b is not defined at <eval>:3:18(5)
```

Obviously, the code above is somewhat how `require` is implemented, but I guess there is some other use case for this ... obscurities.

Also technically I would argue that this should *not* work with just `require` code as this is literally:
in `main.js`:
```javascript
require("b.js")()
```
in `b.js`:
```javascript
var a = require("s.js)
var b;
exports.default = function () { return a() }
```

in `a.js`:
```javascript
exports.default = function () {return b = {p:5}}
```

And in the case of k6 we use 'babel' so all of the above also works with the 'import/export' syntax which **totally** shouldn't work.

P.S. I am really sorry I keep reporting these obscure. hard to reproduce bugs it just so happens that we keep hitting them :sob: 

edit: also the below code works, so the problem is the intermediate `RunString` calls or something related to them.
```golang

func TestStrange2(t *testing.T) {
        vm := New()
        vm.Set("log", vm.ToValue(func(s string) { fmt.Println(s) }))
        _, err := vm.RunString(`"use strict";
                var c = (function(){
                        var a = (function() {
                                return function() {
                                        return b={p:5};
                                };
                        })();
                        var b;
                        return function () {
                                return a();
                        }
                })()
                ;
                log(c());
        `)
        if err != nil {
                t.Fatalf(err.Error())
        }
}
```

**Comment by dop251** [comment]
Hi,

There was a bug in that `vm.stash` was not reset prior to running a  program recursively (i.e. calling `(*Runtime).RunProgram()` from within another call of (*Runtime).RunProgram()). This is now done here: https://github.com/dop251/goja/blob/6fc852574a34b2f8b7b8945ed62014c6e0af962c/runtime.go#L1215

So, this is not a regression, this is the opposite. The code obviously should not have worked.

**Comment by MStoykov** [comment]
Looking, again, at the two examples, I just think of them to be ... the same, at first glance. In the first case, I just call the lambda through some go code.

Thinking about it some more though - the lambda inside (`a`) needs to have access to the variable in the outer scope and that only works in the "normal" case because it is defined in the same code and goja knows that it needs to provide the variable `b` to that lambda as it did parse them together.

Doing this with `RunString` "correctly" likely will require some refactoring in goja as at the time of the RunString the outer code is already being executed. I am not particularly certain that this is even a good idea, this likely fixes some shadowing/acting at a distance that would probably not be noticed otherwise ... 

I am adding this mostly as an explanation of my thinking, and for anyone who comes across this in the future, not so much with the idea that goja should support this. 

Again in the real example with `import/export` syntax that through babel gets to `require`/commonjs and then that is breaks - for that one, it makes *no* sense for it to work as it did, so it is generally a good thing that broke ;)

**Comment by dop251** [comment]
Because `Run*` methods run the code in the global context, the code is equivalent to this:
```javascript
globalThis.f = function() {
    return (0,eval)(''+
        '"use strict";' +
        '(function() {' +
        '   var a = s();' +
        '   var b;' +
        '   return function () {'+
        '       return a();'+
        '   }'+
        '})()')
}

globalThis.s = function() {
    return (0,eval)(''+
        '"use strict";'+
        '(function() {'+
        '   return function() {'+
        '       return b={p:5};'+
        '   }'+
        '})()')
}

console.log(f()());
```

Changing it so that it runs in the local context would be very problematic. It would essentially mean dropping all static variable resolution and making everything dynamic. Not even TC39 dared doing this, that's why there is a difference between direct and indirect `eval` invocation 😄
