### ISSUE TITLE
Will objects that are frequently used such as XMLHttpRequest be added in the future?

### ISSUE THREAD

**Issue by EwingTsai** [dop251/goja#274]
These objects are very useful for developers who are used to coding in a browser environment.

**Comment by dop251** [comment]
This project is purely ECMAScript (https://www.ecma-international.org/publications-and-standards/standards/ecma-262/). Any additional functionality or runtimes should be done as separate projects (like https://github.com/dop251/goja_nodejs). In any case I have no plans implementing any of those, sorry.
