### ISSUE TITLE
Support for getters/setters in JS

### ISSUE THREAD

**Issue by imgurbot12** [dop251/goja#279]
Would it be possible to extend support for `Object.DefineAccessorProperty` to allow for custom getters/setters in Go or to allow for getters/setters on structs to work on field assignments in JS?

Here is an example of the implementation of the same function in javascript:
```javascript
const student = {n: "student"}
Object.defineProperty(student, "name", {
    get : function() {
        return this.n
    },
    set : function(value) {
        this.n = value
    }
})
```

Perhaps it could be auto-implemented with struct setters
```go
type Student {n string}
func (s *Student) Name() string {
  return s.n
}
func (s *Student) SetName(name string) {
  s.n = name
}

vm := goja.New()
vm.Set("student", &Student{n: "name"})
vm.RunString(`student.name = "new name"`)
```

**Comment by MStoykov** [comment]
I am not certain if you are aware that you can actually currently do this with [Object.DefineAccessorProperty](https://pkg.go.dev/github.com/dop251/goja?utm_source=godoc#Object.DefineAccessorProperty) 

as in 
```golang
package goja_test

import (
	"testing"

	"github.com/dop251/goja"
)

type Student struct{ n string }

func (s *Student) Name() string {
	return s.n
}

func (s *Student) SetName(name string) {
	s.n = name
}

func TestDefinePropertyE(t *testing.T) {
	vm := goja.New()
	o := vm.NewObject()
	s := &Student{n: "name"}
	err := o.DefineAccessorProperty("name",
		vm.ToValue(func(call goja.FunctionCall) goja.Value {
			return vm.ToValue(s.Name())
		}),
		vm.ToValue(func(call goja.FunctionCall) (ret goja.Value) {
			s.SetName(call.Argument(0).String())
			return
		}),
		goja.FLAG_TRUE, goja.FLAG_TRUE)
	if err != nil {
		t.Fail()
	}
	vm.Set("student", o)
	vm.RunString(`student.name = "new name"`)
	if s.n != "new name" {
		t.Fail()
	}
}
```

As you can see you can't just wrap the object and goja to do the rest. I guess goja can be extended to do it, but I would expect this will have a lot of corner cases while the current behaviour is more aligned with how it works for `json` marshalling and co,

**Comment by imgurbot12** [comment]
I was totally unaware you could such a thing; this definitely solves my problem. I spent a lot of time combing through the docs but had difficulty understanding how to do something like this.

Thanks!

**Comment by totaltube** [comment]
Is there any way to define getters and setters for dynamic key? In example, I want to have a map accessable in js ( set any map properties and read them ), but there may be concurrent access to this map, so I need to define setter and getter with mutexes.
