### ISSUE TITLE
About the "Date" problem in JS script

### ISSUE THREAD

**Issue by iveryo** [dop251/goja#281]
Such as:
new Date("2021-04-18 23:59:59").getTime()
The result returned after the script is run is: 1618790399000
My expectation is: 1618761599000
Is it a bug? Thank you

**Comment by dop251** [comment]
Hi. Strictly speaking no, it's not a bug. The [specification](https://262.ecma-international.org/10.0/#sec-date.parse) only requires to support `YYYY-MM-DDTHH:mm:ss.sssZ`, anything else is left up to implementations, which means any code that relies on it is not portable. For instance in Safari 14.0.3 yor code returns NaN.

I found a mentioning in the MDN docs [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse]) that "when the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as local time". It's non-standard though. I might look at it at some point, but it's not a priority right now.

**Comment by iveryo** [comment]
Okay thank you
