### ISSUE TITLE
Why is BigInt a blacklisted feature ?

### ISSUE THREAD

**Issue by Gabri3l** [dop251/goja#282]
Not a request or anything, just was curious to learn why `BigInt` is not supported. I was wondering if it was something that will never be supported or possibly on the roadmap. Thank y'all for this amazing package!

**Comment by dop251** [comment]
It is blacklisted because it's not implemented yet and I don't want the tests to fail because of that. Everything that's in the ECMAScript spec will eventually be implemented.

**Comment by Gabri3l** [comment]
Awesome thank you for the response!
