### ISSUE TITLE
Host Object cannot assign props in strict mode

### ISSUE THREAD

**Issue by zhwaaaaaa** [dop251/goja#284]
Cannot assign to property pp of a host object
`type hostObj struct {
	esModule bool
}

func (h *hostObj) GetVal() string {
	return "GetVal->"
}

func ExampleBindPropToHostObject() {
	r := New()
	i := &hostObj{
		esModule: true,
	}
	value := r.ToValue(i)
	r.Set("aa", value)
	r.Set("bb", i)
	str := `
		aa.pp=123;
		bb.pp1=123;
		Object.keys(aa).length
        `
	program, err := Compile("tst.js", str, true)
	if err != nil {
		panic(err)
	}
	runString, err := r.RunProgram(program)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%s", runString)
	// Output: 1

}`

**Comment by dop251** [comment]
You cannot access property that doesn't exist in the Go `struct`. And you cannot access non-exported properties either.
