### ISSUE TITLE
ToInteger() int64  can change to ToInteger() int64, err ?

### ISSUE THREAD

**Issue by Chairou** [dop251/goja#285]
I use 
vm.Set(k, vm.ToValue(v).ToInteger())
when I send a string "1,2,3" to it , It silent return 0 , no anything else print.

so maybe you cloud change ToInteger() int64 to ToInteger() int64, err ?  

thanks for your time :)

**Comment by dop251** [comment]
There is a merit in your request, however ToInteger() was meant as a convenience method which you can use in an expression and which you use when you know you're dealing with an integer. If you're not sure, you can use ToFloat() instead which returns NaN if conversion is not possible.
