### ISSUE TITLE
Immediately-invoked function expressions

### ISSUE THREAD

**Issue by patrickjm** [dop251/goja#286]
Does Goja support these?

At the moment, this is what I'm getting:

```js
(()=>{ printHello() })()

// ... Line 1:3 Unexpected token ) (and 2 more errors)
```

Expected behavior
```js
(()=>{ printHello() })()

// ... Hello
```

Webpack relies heavily on these to isolate modules (unless you set `output.iife: false`), so it would be very useful to see them supported

**Comment by MStoykov** [comment]
Hi @patrickjm,

Immediately invoking functions is supported, but what isn't is [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). 

Some people (us at k6 including) use babel to transpile our code down to what is supported by goja. We even only use the [plugins for things](https://github.com/k6io/k6/blob/daca27c2628c96efd915d16f91bc26b119c5d0df/js/compiler/compiler.go#L41-L72) that aren't supported ;) Note that we use babel 6.26.0, for ... [reasons](https://github.com/k6io/k6/issues/981), but the latest versions seem to also work with goja.

We also have a [template repository](https://github.com/k6io/template-es6) doing the transformation outside of k6. Which also uses webpack and babe,l which can possibly help you find which configurations will make webpack not emit arrow functions ;)

**Comment by jvatic** [comment]
@patrickjm As @MStoykov said, arrow functions are not supported and you may want to consider using something like babel to transpile your code first. You might consider using the [goja-babel](https://github.com/jvatic/goja-babel) package which uses the standalone version of babel running within goja to transpile code into something you could then run within goja.

**Comment by patrickjm** [comment]
Awesome, thank you both!
