### ISSUE TITLE
Using a module loader (AMD or System)

### ISSUE THREAD

**Issue by clarkmcc** [dop251/goja#287]
I'm looking for some guidance on how to utilize a module loader with goja. I've written a [package](https://github.com/clarkmcc/go-typescript) that transpiles typescript code using Goja and I would like to combine all my typescript files into one bundled output file. I can do this easily using the typescript config:

```json
{
  "compilerOptions": {
    "module": "amd"
  }
}
```

However I get this error when compiling the typescript:

```
Only 'amd' and 'system' modules are supported alongside --outFile
```

I'm trying to figure out a way to implement the AMD or System module loaders in Goja so that I can work with these bundle files but I'm struggling with even where to start. I think it may be even more complicated due to the fact that I think these are async loaders and Goja does not have an event loop. Thoughts?

_Edit: I'm sorry, I see I typed `commonjs` in the JSON example when I meant to type `amd`_

**Comment by nwidger** [comment]
Have you taken a look at the [goja_nodejs](https://github.com/dop251/goja_nodejs) package, specifically its [require](https://pkg.go.dev/github.com/dop251/goja_nodejs) package?  It implements 
the [NodeJS module search algorithm](https://nodejs.org/api/modules.html#modules_all_together), and I've used it to load modules into goja compiled from TypeScript using `compilerOptions.module=commonjs` myself.

**Comment by clarkmcc** [comment]
@nwidger I can get it to work with commonjs without any issues, the problem is bundling. When I bundle typescript code into a single file using the `compilerOptions.module=amd`. I'm testing a solution now evaluating the [Almond AMD module loader](https://github.com/requirejs/almond) in the runtime before loading my bundle and it seems to be promising.

**Comment by clarkmcc** [comment]
I was able to solve this problem by pre-evaluating a light-weight [AMD module loader](https://github.com/requirejs/almond) into the runtime before evaluating my script. I packaged this entire workflow up into an [existing package](https://github.com/clarkmcc/go-typescript) that I use to simplify this process. The usage is fairly simple and addresses my problem of running scripts and importing from AMD-style compiled modules.

```go
// This is the module we're going to import
modules := strings.TrimSpace(`
    define("myModule", ["exports"], function (exports, core_1) {
        Object.defineProperty(exports, "__esModule", { value: true });
        exports.multiply = void 0;
        var multiply = function (a, b) { return a * b; };
        exports.multiply = multiply;
    });
`)

// This is the script we're going to transpile and evaluate
script := "import { multiply } from 'myModule'; multiply(5, 5)"
result, err := EvaluateCtx(context.Background(), strings.NewReader(script),
    WithAlmondModuleLoader(),
    WithEvaluateBefore(strings.NewReader(amdModuleScript)),
    WithTranspile())

// Returns 25
```
