### ISSUE TITLE
RegExp constructor returns different results than regex literal

### ISSUE THREAD

**Issue by clarkmcc** [dop251/goja#288]
I have the following two expressions that are returning different results based on whether I use the `RegExp` or do a regex literal. Is that expected? This seems like a bug. Thanks!

```javascript
new RegExp('bizhub\s[0-9]+').test('bizhub 224e') // Returns false

/bizhub\s[0-9]+/.test('bizhub 224e') // Returns true
```

**Comment by MStoykov** [comment]
You need to escape the slash `\` in the constructor's first argument  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#flags_in_constructor

**Comment by clarkmcc** [comment]
@MStoykov silly mistake, thank you.
