### ISSUE TITLE
TypeError: Object has no member 'error'

### ISSUE THREAD

**Issue by preppypiet** [dop251/goja#29]
Hi, I realise this is a duplicate of #27 but it was closed so I thought I'd create a new one. The line that is causing this error for me was calling a react-dom/server render to string with a react-redux Provider wrapper around a RouterContext. 

An easy way to see this happen is to clone latest of https://github.com/olebedev/go-starter-kit and run 'make install' and 'make serve' to run the app. With js disabled, no server side render occurs. You just have to change line 235 to assign an error var and check if it's not nil in server/react.go. I just panicked on it to produce output similar to: 

```
main.(*JSVM).Handle.func1(0xc420180180)
        /Users/pieter/coding/go/src/teststarter/server/react.go:238 +0x232
teststarter/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).RunOnLoop.func1()
        /Users/pieter/coding/go/src/teststarter/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:109 +0x31
teststarter/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).run(0xc4201b0000, 0xc4201b0201)
        /Users/pieter/coding/go/src/teststarter/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:116 +0x77
created by teststarter/vendor/github.com/dop251/goja_nodejs/eventloop.(*EventLoop).Start
        /Users/pieter/coding/go/src/teststarter/vendor/github.com/dop251/goja_nodejs/eventloop/eventloop.go:87 +0x44
```

I had the exact same error with a smaller test that renders out a react app, and the same error occurred when react-redux's connect function was used. I don't really know where to start looking for a cause to this. If you've got an idea of where I can start looking, I might be able to help fix the issue. Thanks!

My go env is:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pieter/coding/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.1/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/ss/7vgx61gj12373gbg_pbst6pw0000gn/T/go-build423786578=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by ufukomer** [comment]
@preppypiet Yea, it is all about versions. Show me your package.json.

**Comment by dop251** [comment]
I've added the location of the error to the default Error() message. Hope this helps in future.
