### ISSUE TITLE
Fix date parsing

### ISSUE THREAD

**Issue by zedd3v** [dop251/goja#292]
`Date.parse('December 04, 1986')`

Expected: **534034800000**

Got: **NaN**

**Comment by dop251** [comment]
@zedd3v The expected return value should actually be 534038400000, because date only formats are treated as UTC (see my comment in #281).

@Duske This expression works for me, are you sure you're using the latest version?

**Comment by Duske** [comment]
It occured in latest [k6](https://github.com/grafana/k6) load generator. When I investigated it, they use a recent version of goja: https://github.com/grafana/k6/blob/41712f75726c9451d2c3d04a1a806709c31de484/go.mod#L11

**Comment by MStoykov** [comment]
@Duske it seems to work for me and returning `1624370080000` including for the last 4 versions of k6. I get the same value in a browser(firefox) and I get the same using `date` on the cli. 

Can you provide a script that does actually return the wrong value? 

Also, I would prefer k6 bugs to be reported to k6 we can escalate them to goja if/when needed ;)
