### ISSUE TITLE
(request) Safe-mode isolation/execution

### ISSUE THREAD

**Issue by angadn** [dop251/goja#298]
Hi all! 👋 This may be out of scope, but would be happy to contribute myself if relevant, and pointed in the right direction.

**Use-case**
One of my projects uses Goja for executing user-defined JavaScript. For obvious _security_ reasons, I'd like to prevent certain snippets of code from executing, including (but probably not limited to):
- `eval(...)`
- `require(...)`
- `globalThis[...]`
- `process`

While I am currently accomplishing this with simple code-checks and assigning the aforementioned identifies as `undefined`, I am curious as to what the best way would be to achieve complete isolation from the underlying host in Goja (without something like accessing a Docker container over the network - the Goja invocations often range into a few hundred-thousand and the application is performance-critical).

Some helpful things would be:
- Ability to pass a context for cancelation to a `Callable`.
- Ability to deny access entirely to the underlying filesystem and environment.

Thanks for your time! 😄

**Comment by clarkmcc** [comment]
Correct me if I'm wrong, but the default Goja environment (the result of running `goja.New()`) only has the `eval` method and the global `this` object as illustrated below. Require would only be available if you loaded a module loader into your runtime and process is a NodeJS package that you would have to re-write in Go and make available to the Goja runtime. 

```go
func TestRuntime(t *testing.T) {
	runtime := goja.New()
	// This works
	t.Run("eval", func(t *testing.T) {
		value, err := runtime.RunString(`eval(10 + 10)`)
		require.NoError(t, err)
		require.Equal(t, "20", value.String())
	})
	// This works
	t.Run("this", func(t *testing.T) {
		value, err := runtime.RunString(`this`)
		require.NoError(t, err)
		require.NotNil(t, value)
	})
	// This does not work
	t.Run("require", func(t *testing.T) {
		_, err := runtime.RunString(`require`)
		require.Error(t, err)
	})
	// This does not work
	t.Run("process", func(t *testing.T) {
		_, err := runtime.RunString(`process`)
		require.Error(t, err)
	})
}
```

It seems to me that the only thing you have to worry about is the functionality that you expose via your own Go binding functions, all other functionality is isolated to the runtime. What I mean by that is that you don't have to worry about someone modifying your host machine filesystem for example unless you provide a Go binding function to the Goja runtime that allows the runtime to modify the host filesystem.

**Comment by angadn** [comment]
@clarkmcc Nice! In my tests `globalThis` seemed to have also worked but I suppose most of my worries are misplaced in `require` and `fs` are unavailable by default 😄

**Comment by dop251** [comment]
Please see #85 and #94. Bottom line is, it depends on your definition of 'safe'. Filesystem access can be prevented by disabling source maps (`rt.SetParserOptions(parser.WithDisableSourceMaps)`) or providing your own source map loader (`parser.WithSourceMapLoader`), but it's still open to DoS attacks by starving CPU or RAM. The former can be partly mitigated by limiting execution time using `Interrupt`.
