### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by sleungcy** [dop251/goja#30]
I have what-wg-fetch loaded by one of the react modules, it seems to be expecting self to be defined. 

ReferenceError: self is not defined
        at bundle.js:56189:19(7)

the traced code at line 56189:
```
 56182 /***/ function(module, exports, __webpack_require__) {
 56183
 56184         // the whatwg-fetch polyfill installs the fetch() function
 56185         // on the global object (window or self)
 56186         //
 56187         // Return that as the export for use in Webpack, Browserify etc.
 56188         __webpack_require__(395);
 56189         module.exports = self.fetch.bind(self);
 56190
 56191
```

I tried setting 'self' as an empty object before running bundle.js, but then I get the error "Host Object is not extensible". 

What can I do about this and any other future modules that expects to run on browsers? Was setting self/window an empty object a good approach?

**Comment by olebedev** [comment]
It's 'fetch's issue. Look at its API.

**Comment by dop251** [comment]
Judging by the error you tried something like this:

```go
vm.Set("self", map[string]interface{}{})
```

You definitely don't want to do this. It creates a JS wrapper around the map and every time you put a JS value into it, the value will be Export()'ed and then every time you reference it from JS it will be wrapped again. (Aside of this, the reason for the error is those wrapped maps are not extensible by default. Can't remember if there was a good reason for me to do it this way, probably not, I'll change it).

If you want to set it to an empty object it could be done like this:

```go
vm.Set("self", vm.NewObject())
```

However, in browsers 'self' appears to be the global object, so to make it more compatible you should do the same. I'll probably add something like vm.GlobalObject(), but for now you can do this:

```go
vm.RunString("var self = this")
```

**Comment by sleungcy** [comment]
That's very interesting! I will definitely try this.
