### ISSUE TITLE
Proxy creation panics on target not callable

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#306]
The following tc39 [test panics](https://github.com/tc39/test262/blob/f37edcb486db80d7aaf50147df14268a910556a9/test/built-ins/Proxy/create-target-is-not-callable.js) which unfortunately is from after the current commit used in goja :(

**Comment by dop251** [comment]
Are you sure this is the right test? I can see it and it passes.

**Comment by dop251** [comment]
Ok, got it, the test I have is slightly different (`p.call()` vs. `p()`)
