### ISSUE TITLE
Convert *ast.Program back to string

### ISSUE THREAD

**Issue by clarkmcc** [dop251/goja#310]
I'm currently using this to parse some Javascript. Is it possible to make modifications to the `*ast.Program` and then turn it back into a string?

```go
program, err := goja.Parse("", script)
if err != nil {
    return nil, err
}
```

**Comment by dop251** [comment]
No. Moreover you're not really supposed to modify the AST tree produced by the parser as it contains references to specific positions in the source code. The reported stacktrace locations will be inaccurate after this.

And in general, the parser and the ast modules are there only to support the main purpose, i.e. running JS code. They are not covered by API compatibility promise as is the main module. In hindsight I should have made them internal, too late for that now though I guess...

If you need to do code transformations use one of the great tools available, babeljs for instance.
