### ISSUE TITLE
Symbol not being iterated when destructuring a Proxy

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#313]
[test/language/expressions/object/dstr/object-rest-proxy-ownkeys-returned-keys-order.js](https://github.com/tc39/test262/blob/6e2a29417ad52ba114c26838a288510d704efa1b/test/language/expressions/object/dstr/object-rest-proxy-ownkeys-returned-keys-order.js)

fails with

```
Test262Error: Expected [foo, 0] and [Symbol(), foo, 0] to have the same contents.
```

**Comment by dop251** [comment]
Actually fixed by a88d78e02a29a01fcbc84aec8e6efecdf760b685 (the commit message is wrong)
