### ISSUE TITLE
TypedArray issues 

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#315]
This is a list of some corner cases (IMO) tests that are failing with TypedArrays:
- [test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex-desc-configurable.js](https://github.com/tc39/test262/blob/6e2a29417ad52ba114c26838a288510d704efa1b/test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex-desc-configurable.js), should not be possible to set numerical index on TypedArray with `configurable: true` 
- [test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex.js](https://github.com/tc39/test262/blob/6e2a29417ad52ba114c26838a288510d704efa1b/test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/key-is-numericindex.js) the reverse if `configurable: false` 
- [test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/tonumber-value-detached-buffer.js](https://github.com/tc39/test262/blob/6e2a29417ad52ba114c26838a288510d704efa1b/test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/tonumber-value-detached-buffer.js) - evaluation ordering issue ? with detach involved
- [test/built-ins/TypedArrayConstructors/internals/Get/key-is-not-minus-zero.js](https://github.com/tc39/test262/blob/6e2a29417ad52ba114c26838a288510d704efa1b/test/built-ins/TypedArrayConstructors/internals/Get/key-is-not-minus-zero.js) ... uh something way too complicated

All those errors changed after the last changes, but likely have been broken for longer,just haven't been noticeable. There are bunch more detach errors that haven't changed so :shrug:

**Comment by dop251** [comment]
The detached buffer semantics has been recently updated, so I had to disable some tests because they are out-of-date in my version. I clearly need to find a way to upgrade the tests, and I'm planning to do so after implementing arrow functions and template strings. In the meantime, please do not report any typed arrays or array buffers related issues (unless it's a panic).
Thanks!
