### ISSUE TITLE
Exported objects null and undefined fields treated equally

### ISSUE THREAD

**Issue by absorbb** [dop251/goja#317]
Currently, when goja vm exports js objects with undefined fields it replaces them with null value:
```go
res, _ := vm.RunString(`
(function () { return {
            "a": undefined,
            "b": null}
})()
`)
fmt.Println(res.Export())
```
will result: `map[a:<nil> b:<nil>]`

That doesn't seem right. Because in JS undefined and null are not the same things and we are loosing some data here.
E.g. `JSON.stringify` serialize the same object to JSON without "a" field: `{"b":null}`

It would be great if goja will treat `undefined` the same way as `JSON.stringify` because that is behavior people working with javascript get used to. Or that will be configurable via some flag.

Thanks for the great vm!

**Comment by dop251** [comment]
Unfortunately (or rather fortunately) there is no equivalent of `undefined` in Go, so when exporting from ECMAScript we have to map 3 possible states (property does not exist, property set to `undefined` and property set to `null`) to 2 (property does not exist, property set to `nil`). Whichever mapping you choose there always will be loss of information.

As for the flag, I don't see a strong case for it really. If it's critical for you you can always implement and use your own export function.

**Comment by absorbb** [comment]
@dop251 Is there some way to use custom export function other than forking repository or using reflection with unsafe?

**Comment by dop251** [comment]
The public API should be enough to write your own equivalent of the Export function. Is there anything missing?

**Comment by absorbb** [comment]
Got it.
If somebody will also need that here is the code:
```go
var jsObjectReflectType = reflect.TypeOf(make(map[string]interface{}))

func Export(vp *goja.Value, vm *goja.Runtime) interface{} {
	v := *vp
	if v.ExportType() == jsObjectReflectType {
		return exportObject(v.ToObject(vm), vm)
	} else {
		return v.Export()
	}
}

func exportObject(o *goja.Object, vm *goja.Runtime) map[string]interface{} {
	keys := o.Keys()
	m := make(map[string]interface{}, len(keys))
	for _, itemName := range keys {
		v := o.Get(itemName)
		if v != nil {
			if v.ExportType() == nil && v.String() == "undefined" {
				continue
			}
			m[itemName] = Export(&v, vm)
		} else {
			m[itemName] = nil
		}
	}

	return m
}
```

**Comment by dop251** [comment]
You can use `Runtime.IsUndefined()` to check if the value is `undefined`

**Comment by absorbb** [comment]
Thank you
