### ISSUE TITLE
Panic in `parser.ParseFile`

### ISSUE THREAD

**Issue by mrduncan** [dop251/goja#318]
I came across the following panic while doing some fuzzing and figured I'd pass it along:

```go
package main

import "github.com/dop251/goja/parser"

func main() {
	parser.ParseFile(nil, "", "let{f(", 0)
}
```

https://play.golang.org/p/p0Vco0YNu0z

Appreciate all the work that's gone into this project!

**Comment by dop251** [comment]
Thanks for reporting!
