### ISSUE TITLE
feature request: add an ability to work with utf16 string representation from Go

### ISSUE THREAD

**Issue by ilyapashuk** [dop251/goja#321]
hello

when I'm sending string value to js or getting it from js function, it is converted to or from utf16.

please add a new type "JavascriptString []byte" to make it possible to directly pass such utf16 strings between runtimes.

**Comment by dop251** [comment]
Hi. You can pass immutable `Value` between runtimes (essentially everything except `*Object`).

**Comment by ilyapashuk** [comment]
may be it will be usefull to document this?
without documentation this is an undocumented part of api that may change in future, because now documentation says that values can not be passed between runtimes at all.
