### ISSUE TITLE
Using of rest argument binding in inner function, breaks it

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#327]
Original report https://github.com/grafana/k6/issues/2131.

Smallest reproduction:
```javascript
function f(...rest) {
         () => rest; // remove this line to fix.
         return rest.length;
}
f(1,2) // this returns 0 not 2
```
as shown there having adding another variable to which to using rest and then using that in the lambda fixes it *including* that the following works:
```
function f(...rest) {
         const alias =  rest;
         return (() => alias.length)();
}
f(1,2) // this returns 2 actually
```
but doesn't work if in this case you just use `rest` instead.

This doesn't seem related to lambdas as it also doesn't appear to be working with functions.

I would guess some optimizations somewhere as calling `eval` before the lambda fixes it.

Another thing that I noticed (that might be a completely separate issue) is that 
```
function f(...rest) {
         eval(rest[0]) // not the missing ;
         () => rest; 
         return rest.length;
}
f(1,2) // this returns 0 not 2
```

returned `Line 3:3 Malformed arrow function parameter list` but I don't know if this isn't really how it should work  :shrug:

**Comment by dop251** [comment]
Thanks for reporting. The other issue that you mention is not a bug, ASI does not apply to this case, so it's interpreted as `eval(rest[0])() => rest`
