### ISSUE TITLE
Function to turn a *ast.Program into a *Program

### ISSUE THREAD

**Issue by liclac** [dop251/goja#33]
I'm having some fun involving AST trees of JS snippets, and it feels a little silly that if I want to run one of them, I can't just chuck the already parsed tree at a runtime, but have to do the parsing twice.

Please consider sating my gluttony for microoptimizations.

**Comment by dop251** [comment]
Out of curiosity, how do you convert AST into string?

**Comment by liclac** [comment]
I don't, I parse an AST tree and crawl through it looking for identifiers - I'm basically looking to highlight the external variables that are actually referenced inside user-provided snippets: https://github.com/loadimpact/k6/commit/1fa59b24371b6bda804c0f1c2b78bdec1c26b248

**Comment by dop251** [comment]
Ah, I see. I thought you were doing some manipulations with the AST before compiling.

**Comment by liclac** [comment]
❤️
