### ISSUE TITLE
Runtime.ToValue provides specific behavior for reflect.Func

### ISSUE THREAD

**Issue by zuiwuchang** [dop251/goja#330]
Is it possible to provide an interface so that users can customize the Runtime.ToValue function to handle the behavior of reflect.Func? For example, in New() *Runtime, set a function to specify how ToValue handles reflect.Func.

The reason for this is: all the native functions (case reflect.Func) are called by ToValue provides a default calling rule, I need a way to change this default calling rule. For global functions, I can implement a function to convert reflect.Func to `case func(FunctionCall) Value` to ToValue, but I cannot provide this wrapper for member functions because member functions are automatically passed in **objectGoReflect._get** To ToValue cannot call the wrapper I provided.

In fact, I implemented a Promise. I hope that if a certain token is passed in when calling the Go native function directly in js, I will create a Promise and return it to js and execute the native function in the new goroutine for the function to use the Promise after completion Notify js. So I can't use the default call method provided by goja, I need to be able to customize the call implementation to quickly expand all native functions to support Promise.

**Comment by dop251** [comment]
See #332
