### ISSUE TITLE
ExportTo throws error from `string` to `[]byte`

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#333]
Post https://github.com/dop251/goja/commit/6e5fa0950d16122cfb1a7bf8a8bcd52c499e389e if you have a string value and you try to export it to `[]byte` you will get something like:
```
                Error:          Received unexpected error:
                                could not convert -----BEGIN CERTIFICATE-----
                                MIIE6zCCA9OgAwIBAgICBNIwDQYJKoZIhvcNAQELBQAwgdsxCzAJBgNVBAYTAlpa
                                MRkwFwYDVQQIExBLb3B1bmNlemlzIEtyYWlzMREwDwYDVQQHEwhBc2h0aW5vazEa
                                MBgGA1UECRMRMjIxQiBCYWtlciBTdHJlZXQxDjAMBgNVBBETBTk5OTk5MRwwGgYD
<removed for size>
                                ddBqJe0XUeAX8Zr6EJ82
                                -----END CERTIFICATE----- to []uint8 at go.k6.io/k6/js/common.Bind.func1 (native)
```

I have discussed this previously with the team as exporting js scripts to bytes is slightly interesting in whether we get the UTF16 or the utf8 representations, but up to this point it always worked out to be the UTF8 one, which is also what we kind of depend on. 

The quick and dirty fix I came up with(breaks other things), which also shows that this is done very inefficiently :facepalm: is to drop the `expKind == kind` part of the check here https://github.com/dop251/goja/commit/6e5fa0950d16122cfb1a7bf8a8bcd52c499e389e#diff-273ef2c87873bb7655d4ef6156723ac1ae2789fec1912b6f35623847ba2a9203R1828 as it wasn't previously there.

To be honest we might be better off actually taking `goja.Value` and working with that as we have other cases where we have done similar things as we can have `string`, `ArrayBuffer` and `[]byte` (no longer possible to acquire hopefully from within a script) and we needed to move between those, so maybe in this particular case it makes more sense for us to just move to that :shrug: , but still decided to report it

**Comment by dop251** [comment]
Thanks. In general I did not want to use the default reflect conversion mechanism because sometimes it doesn't do what you'd expect, but in this particular case I think it's worth restoring the old behaviour. I'll take a look.
