### ISSUE TITLE
Promises eat exceptions 

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#337]
Great job on the promises :tada

I have the following problem:
```
new Promise((res) => {throw "bad Promise"});
```
Will surprisingly completely eat the exception. This gets particularly bad when you have a script error that would've thrown an exception, but instead, you get nothing. 

I found that I can get the just string representation in onReject handler/callback or [PromiseRejectionTracker](https://pkg.go.dev/github.com/dop251/goja#PromiseRejectionTracker) but it will be nice if at least the second one gets access to the original exception so that can be reported to the user.

**Comment by dop251** [comment]
I'm not sure what you mean by "original exception", but both the argument of onReject and `(*Promise).Result()` will contain the value that was thrown.

If you mean access to the stack trace, it's a little complicated. The specification doesn't mention it at all as far as I can tell. Existing implementations provide access to it through `Error.stack`, but you can throw any value, not just an instance of `Error`. Nevertheless, I should probably do the same, but currently it can only be captured using `(*Runtime).CaptureStackTrace()` in this situation.

**Comment by MStoykov** [comment]
I guess I was misunderstanding how it works, but yeah the idea was that I would want to get the stacktrace and report it.

Having tried it to now use it in https://github.com/grafana/k6/pull/2228/commits/f34e3de1f7e96f504cf041faea086d1ca50d2678 and I have to say it's not great, but given that this is the specification and having played around with it I don't see how given how Promises work:
- `then` might have been called or not by the time a promise is resolved
- and you can call it again on an already rejected Promise and (even one for which the rejection handler has already been called) it still needs to queue the new rejection handler

Given all of the above, I kind of don't see how they could've designed it any other way and I am pretty sure there is probably some discussion(s) around the time of the design about all of these problems, likely even with explanations on why at least parts of those are unavoidable given the (then) current state of ECMAscript/js :(. 

Also at least from my very fast test the only way to know that  Promise was made with `goja.NewPromise` and then rejected before a handler was added is that the stacktrace (will hopefully if implemented correctly with event loop) be saying just "native". This also makes it quite hard to give any good feedback on what the user could potentially fix :(. 

So ... I don't know, maybe more examples and more documentation on how this is a problem that doesn't have a "correct" answer for everybody and what the different approaches might be, and how they are all problematic will be nice :shrug:

**Comment by dop251** [comment]
I believe to some extent this could be mitigated by grabbing a stack trace when an instance of `Error` is created and providing access to it to the code (this is what other implementations do as far as I know). Then, if you reject a Promise with an `Error` you can get the stack trace.

I'll have a closer look at how it's done in V8 (for example what happens when an Error is re-thrown, etc...) and try to implement something similar.
