### ISSUE TITLE
ES6 class support

### ISSUE THREAD

**Issue by matthewmueller** [dop251/goja#349]
Hey @dop251, thanks for all your hard work on Goja. I'm especially grateful for the recent Promise API support. 

Goja is really close to being ready to natively run what ESBuild outputs to ES6 via `esbuild --target=es2015 <entry...>`. 

One thing that's missing is class support:

```js
class A extends B {
  constructor() {
     super()
  }
}
```

I was actually surprised to see that class support came in ES6, but I had a look at the [ES6 support table](http://es6-features.org/#ClassDefinition) and it looks like it's there.

For my use-case, I'm trying to render Svelte code on the server-side, but the compiler generates classes:

```js
var SvelteElement
if (typeof HTMLElement === "function") {
  SvelteElement = class extends HTMLElement {
    constructor() {
      super()
      this.attachShadow({ mode: "open" })
    }
    // ...
}
```

**Comment by dzonerzy** [comment]
Thanks for all your hard work first of all! do we have an eta for the es6 support?

**Comment by arukiidou** [comment]
@[dzonerzy](https://github.com/dzonerzy)
He says [that](https://github.com/dop251/goja#can-you-implement-feature-x-from-es6-or-higher),

I will be adding features in their dependency order and as quickly as time permits. `Please do not ask for ETAs.`
