### ISSUE TITLE
Is it possible to create an array object from Go?

### ISSUE THREAD

**Issue by matwachich** [dop251/goja#35]
Hello!
Everything is in the question: what is the equivalent Go code for JS `var obj = [10, 20, 30]`?
Thanks!

**Comment by dop251** [comment]
If you mean native js array, then no. You can, however, pass a pointer to a []interface{} which will be represented as a host object similar to an array:

```go
	vm := goja.New()
	a := []interface{}{10, 20, 30}
	vm.Set("a", &a)
	vm.RunString("a.push(40)")
	fmt.Println(a) // prints [10 20 30 40]
```

**Comment by dop251** [comment]
I hope this answers your question, @matwachich Feel free to open another ticket if you have any further questions.
