### ISSUE TITLE
Add `GetGlobals()` and `GetLocals()` in runtime.go for debugger.

### ISSUE THREAD

**Issue by panzhongxian** [dop251/goja#356]
Hi, @dop251 . I know we can get variables by their names with `func (r *Runtime) Get(name string) (ret Value)` and the debugger can use these functions to print specific variables.

But as mentioned in [Support info variables-like command. #11 ](https://github.com/mostafa/goja/issues/11), when integerating the debugger with IDE like VS Code, there is a window to show both locals and globals.

Could you expose some interfaces to access all the global and local variables sperately. 

Maybe it seems like `func (r *Runtime) GetGlobals() (ret map[string]Value)`.

**Comment by panzhongxian** [comment]
Thanks for your reply in #355 , Could you give me more advice on the this topic "forced local variable name maps"?

**Comment by dop251** [comment]
I've mentioned it here: https://github.com/dop251/goja/pull/297#issuecomment-872547045

With global variables there is another issue: `var` bindings are kept in the global object, but so are the standard built-ins (like `Object`, `Array`, etc.). There is currently no way to distinguish them, you'll have to address it somehow.

**Comment by panzhongxian** [comment]
Thanks. @dop251
