### ISSUE TITLE
close the vm

### ISSUE THREAD

**Issue by ClarkQAQ** [dop251/goja#357]
so how to "close" the virtual machine after `vm.Interrupt("halt")`? `vm = nil`? But this seems to cause a memory leak

**Comment by dop251** [comment]
The vm itself doesn't run any goroutines and does not use finalizers. So, there is no need to close it. Assuming you don't have any references to it, it should be garbage-collected. Bear in mind that references can be indirect, e.g. through an *Object or another exported non-primitive value. Just setting vm to nil may not be enough.
