### ISSUE TITLE
Proposal Around Contexts

### ISSUE THREAD

**Issue by steve-gray** [dop251/goja#359]
Whilst I understand and agree a lot of the arguments in the thread around #243 _against_ contexts, a bit of time has passed - and it's something of a contemporary reality that Go has contexts as an established standard. When implementing code from the VM that reaches out to external services, I imagine people are doing something similar where they're smuggling contexts in closures for every helper etc, and it makes the consumer codebases look a little non-modern. 

A very realistic/expected scenario for Goja would be to run small fragments of external code in a sandbox-ish way - and imposing approximate execution time constraints on them would be a natural requirement.

It's possible to brute-force emulate native support for contexts here (My pull request #358 was in relation to not being able to differentiate a JS error from a context error, useful in my scenario). However, it means every caller of Goja needs something like this unpretty code, but it does have zero impact on the core runtime or performance characteristics:

(Note I'm not handling all cases here, this is a butchered/cut down version of something else so a lot of the cleanup flow is just for illustrative purposes)

```
        var instance *goja.Runtime
        // Setup your program/instance here blah blah

    
        // Nominal context for demo purposes
        ctx, cancel := context.WithTimeout(context.Background(), time.Second)
        defer cancel()

	// Interrupt when done
	exited := make(chan bool)
	go func() {
		// Wait for the exit
		select {
		case <-exited:
		case <-ctx.Done():
			instance.Interrupt(ctx.Err())
		}

		// Drain
		for range exited {
		}
	}()

         // When the function ends, write to the channel and close
         // to trigger one of the select cases
	defer func() {
		exited <- true
		close(exited)
	}()

         ret, err := instance.RunProgram(prog)
```

What I'd propose is:

- Provide "WithContext" versions of the various runtime entry points, using a pattern like the above, where context failures interrupt the VM.  No changes internally to the VM architecture at this stage around this, but rather if someone builds a little infinite loop in JavaScript, or something too exciting, it'll just get caught easily enough
- Documentation that these will not interrupt inside native code operations (This is already the case today with every single other library - i.e. a factorisation library doesn't check contexts at all, so a cancelled context isn't an instant return)

Then for a part 2/revisit down the road, if relevant:

- Storage of the context as part of the runtime state when executing.
- Expansion of FunctionCall/ConstructorCall to provide means to access the context, allowing the Go code backing these interop functions to reason about the context the runtime was invoked with.

I believe this is a nice middle road - it offers context support, improves the usability of the framework - but does not change any code around raw runtime execution, so should have no performance impact that could be reasonably measured.

Am happy to do this up as a PR, as it's pretty straightforward.

**Comment by dop251** [comment]
My position hasn't changed. Aside from it still being ugly, in my opinion it's wrong to think of `Context` as a mechanism to interrupt everything. It works for blocking operations (because it is tightly coupled with netpoll), but nobody in their right mind would add something like `SortWithContext()` to the standard library (at least I hope). 

And because `Interrupt()` only interrupts the VM run loop, it would be wrong to use it to sandbox untrusted code. Exposing a `Context` wrapper around it would create false expectations and further promote its incorrect usage. You can put as many caveats in the documentation as you like, when it's a standard API people are much less likely to pay attention. They'll see the familiar `Context` and will jump right into it.

And if you absolutely must, you can still have an external wrapper similar to what you mentioned, there is no need to pollute the API or add unnecessary dependency. You could even have something like `SetInterruptContext(*Runtime, *Context)` and `ClearInterruptContext(*Runtime)`, taking care to make the latter synchronous if you want to reuse the Runtime.

**Comment by steve-gray** [comment]
Im using it as scripting framework over APIs and mechanisms that do themselves require contexts as input. The contexts themselves are not for “security”, but rather allow you to reason about termination timelines - the only security aspect to contexts themselves is that they’re a standard way of relaying authorization data between processes.

  *    An expired context would trigger stopping of the VM at the next opportunity with an interrupt when executing JS.
  *   Code integrated with Goja can be executed with a native go context, which can be propagated to code so that when it emerges from the runtime the context chain is consistent. You need this for stuff like tracing etc.
  *   Your example of sort with context is precisely what I covered explicitly as something where it doesn’t make sense - however if Sort for some reason was capable of calling external code or services, then in that scenario a context aware API surface is the standard.

Context is a reality for dealing with Go code that does anything more than pure math locally today, and the absence of native context support means every single interaction requires a volume of boilerplate - boilerplate that must be repeated every time - whereas putting this into the framework itself is really trivial as a one off. Doing it as a wrapper around the library isn’t possible purely as it needs to be smuggled into the objects passed to the external code invokes.

I’ll do it up in my local copy. If you’re still hesitant around it when it’s in a working form, then I guess I’ll live it as a fork, as doing this in thirty or fourty areas I’ve got in front of me would be more evil.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steve-gray** [comment]
Have done it all up as a PR, eliminated the need for goroutines by doing the interrupt check in the main loop (I couldn't get a meaningful difference in performance outside artificially low utility tests), has tests and benchmarks:

https://github.com/dop251/goja/pull/361

**Comment by dop251** [comment]
I'm not sure I get your point about "smuggling"... Why not just pass it as a regular parameter, like this:

```go
func TestPassContext(t *testing.T) {
	vm := New()
	vm.Set("httpGetWithContext", func(ctx ctx.Context, url string) (string, error) {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err != nil {
			return "", err
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return "", err
		}
		defer resp.Body.Close()
		s, err := io.ReadAll(resp.Body)
		if err != nil {
			return "", err
		}
		if resp.StatusCode != 200 {
			return string(s), fmt.Errorf("HTTP status code: %d", resp.StatusCode)
		}
		return string(s), nil
	})
	entry, err := vm.RunString(`
	(function(ctx) {
		return JSON.parse(httpGetWithContext(ctx, "https://beacon.nist.gov/beacon/2.0/pulse/last"));
	})
	`)
	if err != nil {
		t.Fatal(err)
	}
	var fn func(ctx.Context) (map[string]interface{}, error)
	err = vm.ExportTo(entry, &fn)
	if err != nil {
		t.Fatal(err)
	}
	resp, err := fn(ctx.TODO())
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := resp["pulse"]; !ok {
		t.Fatal(resp)
	}
}
```
If you're worried about the reflection overhead, the same can be done with `FunctionCall`:

```go
func TestPassContextNative(t *testing.T) {
	assertContext := func(v Value, r *Runtime) ctx.Context {
		if c, ok := v.Export().(ctx.Context); ok {
			return c
		}
		panic(r.NewTypeError("The value is not a Context"))
	}
	vm := New()
	vm.Set("httpGetWithContext", func(call FunctionCall) Value {
		ctx := assertContext(call.Argument(0), vm)
		url := call.Argument(1).String()
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		defer resp.Body.Close()
		s, err := io.ReadAll(resp.Body)
		if err != nil {
			panic(vm.NewGoError(err))
		}
		if resp.StatusCode != 200 {
			panic(vm.NewGoError(fmt.Errorf("HTTP status code: %d", resp.StatusCode)))
		}
		return vm.ToValue(string(s))
	})
	entry, err := vm.RunString(`
	(function(ctx) {
		return JSON.parse(httpGetWithContext(ctx, "https://beacon.nist.gov/beacon/2.0/pulse/last"));
	})
	`)
	if err != nil {
		t.Fatal(err)
	}

	fn, ok := AssertFunction(entry)
	if !ok {
		t.Fatal("Entry is not a function")
	}

	v, err := fn(nil, vm.ToValue(ctx.TODO()))
	if err != nil {
		t.Fatal(err)
	}
	resp, ok := v.Export().(map[string]interface{})
	if !ok {
		t.Fatal("Invalid response type")
	}
	if _, ok := resp["pulse"]; !ok {
		t.Fatal(resp)
	}
}
```

**Comment by steve-gray** [comment]
That boilerplate code per usage is awful, it's as much code as the actual framework level change I made - and you need an additional volume just to handle timeout based stopping of the VM with an interrupt etc, and you need to pass around that context value as an opaque variable through all of the JavaScript methods. 

The PR:

- Lets the code cleanly pass around the context in a type-safe way, without boilerplate
- Allows for a unified mechanism to handle time/deadline based stopping
- Has test coverage/benchmarks
- Is an opt-in/zero breaks change for existing users.

I'll close it off, but the folks in the other threads (#198, #243) were lamenting the same, but it's not a hill I'm prepared to die on.

**Comment by dop251** [comment]
I don't see any boilerplate, moreover the documentation says:

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

In this regard, I think passing the parameter is more inline with the recommended usage.

**Comment by steve-gray** [comment]
I feel thats not being intellectually honest, and applying not only a standard meant for Go to JavaScript and selectively to artificially support a view. Specifically it's giving a pass to the way arguments actually work in the project, where they lose their types and get stored in a slice in a structure. The actual intent of that standard as written is the context is passed as the first parameter entirely through the VM in this scenario - doing away with the VM variable in lieu of passing it through every stack frame as a variable from the entry-point right down to the potential exit back into Go-land. 

As I've said, I've closed the PR off.  You've got your views, and so I don't see the sense to continue on this topic.
