### ISSUE TITLE
Not filling variable Value arguments in functions

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#369]
Previous to https://github.com/dop251/goja/commit/f3aaa50fcbc264858f4ebe1b2866f8b7e3873b25#diff-ed51531ee94ac4961a768ad2b94e84c51e633bf108b354645d704056b89953da the following code:
```golang
func TestExportToFunc(t *testing.T) {
	vm := New()
	vm.Set("f", func(s string, g ...Value) {
		something := g[0].ToObject(vm).Get(s).ToInteger()
		if something != 5 {
			t.Fatal()
		}
	})
	_, err := vm.RunString(`
           f("something", {something: 5})
	`)
	if err != nil {
		panic(err)
	}
}
```
worked
now `g` is *nil*, *unless* a third or foth argument is provided to the function.

**Comment by MStoykov** [comment]
Unfortunately the merged fix https://github.com/dop251/goja/commit/61453c17e250def3fd1d56ad79cc73ce3c2f8549 has problems as well if the argument is instead a `function` as it also has `length`.

 So if the argument is a function instead of an object it will again ... not work :(

**Comment by dop251** [comment]
What if I remove this code? It seems redundant and ambiguous to me, if you need to pass an array as a variadic (or any other) argument, you can always use [Function.apply()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) or [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax).

I'll exclude any callables from being treated as array-like as well, just in case.
