### ISSUE TITLE
Access to global object from JS

### ISSUE THREAD

**Issue by abeMedia** [dop251/goja#373]
I'm trying to run some JS code in goja that contains some polyfills which try to extend `global`.
They are failing due to `global` not existing so I was wondering if there's a way to expose the global object to the script?

**Comment by dop251** [comment]
`global` is a non-standard nodejs-specific feature. Use `globalThis` if possible. If not, you can do `vm.Set("global", vm.GlobalObject())`

**Comment by abeMedia** [comment]
Awesome, thanks!
