### ISSUE TITLE
Allow executing scripts in non-global scope

### ISSUE THREAD

**Issue by jmattheis** [dop251/goja#374]
I want to execute the same script multiple times, but it currently fails because of already defined variables. While it would be cool, if the sub script has separate global variables, this is not really needed as this is probably more effort to implement.

I think the code for this already exists, because the `eval` built executes the given script in a separate scope. So the isGlobal parameter needs to be somehow exposed.

https://github.com/dop251/goja/blob/b09a6bfa842fbfe6dd40685e7d3ca4852a30a2ed/runtime.go#L1297

As a workaround, I can use the eval builtin, but with this I cannot use a precompiled program via `Runtime#RunProgram`.

I can contribute a PR for this, but I'm unsure where the change should be made because it could be added to multiple methods RunProgram, RunScript, RunString, Compile.

<details>
  <summary>Example Application</summary>

```go
package main

import (
	"fmt"
	"github.com/dop251/goja"
)

const script = `
const prevous = i;
i++;
prevous;
`

func main() {
	vm := goja.New()
	vm.Set("i", int64(10))
	compiled, err := goja.Compile("test.js", script, true)
	if err != nil {
		panic(err)
	}

	previous, err := vm.RunProgram(compiled)
	if err != nil {
		panic(err)
	}

	previous, err = vm.RunProgram(compiled)
	if err != nil {
		panic(err)
	}
	fmt.Println("previous", previous.ToInteger())
	fmt.Println("next", vm.Get("i").ToInteger())
}
```

</details>

---

As a sidenote: Thanks for maintaining goja! So far, it has been a pleasure to work with it, because it just works.

**Comment by dop251** [comment]
Have you considered wrapping your code in `{ ... }` or `(function() { ... })()`? The latter (combined with strict mode) will also give you an isolated VariableEnvironment.

**Comment by jmattheis** [comment]
Thanks for your response. Yes, this would fix the problem with the already declared variables, but it would make exception stack-traces slightly wrong, because on the line where the `{` is added, the column index is off by one compared to the script without the block scope. This is only a minor inconvenience, so I'd be okay, if you close this issue.
