### ISSUE TITLE
Convert Go *string pointer or type alias to a regular JS string?

### ISSUE THREAD

**Issue by klvnptr** [dop251/goja#377]
Hello. Thank you for goja, I love it :)

Question, that I hadn't been able to figure out so far: 
```go
input := "hello"
var str *string = &input
val := vm.ToValue(str)
```
In this case val will be a JS object. But I want it to be a JS string that contains "hello". Is there any way to do this?
Same question applies to type aliases:
```go
type Hello string
var hello Hello = "world"
helloVal := suite.vm.ToValue(hello)
```
helloVal will be a JS object instead of a string.

Thanks so much. Peter

**Comment by dop251** [comment]
Hi. Sorry, not sure what you mean. Do you want ToValue() to return plain string in this case?

**Comment by klvnptr** [comment]
Hello @dop251 Thanks for you reply.
Yes, in the first case I want ToValue to return a string instead of an object. Would be awesome to somehow override how ToValue behaves.

**Comment by dop251** [comment]
Sorry, but I don't feel like introducing the sort of customisation you are suggesting would be beneficial, it would make it more complicated and slower for everybody. Instead of using ToValue() or Export(), you can implement your own mechanism if necessary.

**Comment by klvnptr** [comment]
I would be happy to implement it, but it is impossible to do so without forking the project. Can you give me any suggestions how to do it without forking?
