### ISSUE TITLE
[Question] How to get original error out of GoError?

### ISSUE THREAD

**Issue by JokerQyou** [dop251/goja#386]
The usage is as follows:

- On the Go side there's a predefined function:
```go
var MyError = errors.New("my custom error")

func CustomStop() (goja.Value, error) {
    return nil, MyError
}
```
- It is then injected into the runtime:
```go
vm := goja.New()
vm.Set("stop", CustomStop)
```
- Now some Javascript code might choose to call `stop()` to throw this custom error, and I want to check on the runtime result to see if the error matches:
```go
_, err := vm.RunString("stop()")
if errors.Is(err, MyError) {
  fmt.Println("We got custom error")
  // Some custom logic...
}
```

But it seems all errors thrown by `CustomStop` are converted to `*goja.Exception`, and their original errors are lost. Is there a way to do this (to throw a predefined custom error via Javascript and check it on the Go side)?

**Comment by JokerQyou** [comment]
Based on this line: https://github.com/dop251/goja/blob/9037c2b61cbfa09e5302b4f61c751bfb3074fb5f/runtime.go#L547

```go
_, err := vm.RunString(transformer)
if e, ok := err.(*goja.Exception); ok {
	if w, ok := e.Value().(*goja.Object); ok {
		func() {
			var originalErr error
			defer func() {
				if reason := recover(); reason == nil && originalErr != nil {
					err = originalErr
				}
			}()
			originalErr = w.Get("value").Export().(error)
		}()
	}
}
if errors.Is(err, MyError) {
	fmt.Println("We got custom error")
	// Some custom logic...
}
```

But I would really want to avoid this internal implementation detail (and the ugly `recover()` around it).

**Comment by dop251** [comment]
Errors are wrapped in `GoError` to make them look more 'native' on the ES side. You can override this behaviour by using the low-level API:

```go
	customStop := func(call FunctionCall, r *Runtime) Value {
		panic(r.ToValue(MyError))
	}
	vm := New()
	vm.Set("stop", customStop)
```

Then you can extract the original value:

```go
	_, err := vm.RunString("stop()")
	if ex, ok := err.(*Exception); ok {
		val := ex.Value()
		if val.ExportType().AssignableTo(reflect.TypeOf((*error)(nil)).Elem()) { // the error type can be pre-calculated and assigned to a variable
			if errors.Is(val.Export().(error), MyError) {
				t.Log("We got custom error")
			} else {
				t.Fatal("not MyError")
			}
		} else {
			t.Fatal("not error")
		}
	} else {
		t.Fatal("not exception")
	}
```
(note the use of `ExportType` which avoids calling `Export` on all values which can be expensive). You can use the same mechanism if the error is wrapped in `GoError` as well, no need to use `recover`.

**Comment by JokerQyou** [comment]
This indeed is much more readable that my hacky workaround. Thanks for the help!
