### ISSUE TITLE
Can I interact with a JS script while it is running?

### ISSUE THREAD

**Issue by HZHgagaga** [dop251/goja#395]
For example, I have a javascript game loop, I use a Go grpc server to run it.

When the player sends an operation request, the Go grpc server will change the status of javascript game loop.

Can I do it with goji?

**Comment by timo-klarshift** [comment]
You can just set a function to your javascript, and when the gameloop calls this function you call out to go and in there you can return whatever state you previously retrieved by your grpc server (or call the grpc server from javascript). There are examples for this in the README
