### ISSUE TITLE
How can I capture console logs from inside VM

### ISSUE THREAD

**Issue by vishaNagpal** [dop251/goja#396]
Hello, 
For some requirements, I need to return the console logs. 
Had it been pure javascript, I could have done something like the below : 
`var list = [];
window.console.log = (val)=>{list.push(val)}`
// list will now contain all the console logs inside it
I tried to add a custom method like `print('something here')` but was unable to define it. Any help would be appreciated.
Thanks

**Comment by tigerwill90** [comment]
Hi, I'm not sure if I understood exactly what you try to achieve, but the following snippet may put you on the right path.
````go
var script = `
console.log = val => {list.push(val)}
console.log('foo')
console.log(123)
console.log('bar')
print(list) // print foo, 123, bar
`

rt := goja.New()

console := rt.NewObject()
if err := rt.Set("console", console); err != nil {
	panic(err)
}

list := make([]string, 0)
if err := rt.Set("list", &list); err != nil {
	panic(err)
}

print := func(value goja.Value) {
	fmt.Println(value.String())
}

if err := rt.Set("print", print); err != nil {
	panic(err)
}

_, err := rt.RunString(script)
if err != nil {
	panic(err)
}

fmt.Println(list) // print [foo 123 bar]
````

**Comment by vishaNagpal** [comment]
Hi, thanks for taking the time in responding. 
The approach you mentioned could not be used in my scenario as explicitly redefining the `console.log` is still possible every time I am calling `rt.RunString` but this way my RunProgram or RunString will not be returning my result as well as the collection of these log statements.
I found a workaround specific to my problem. Will be happy to share the PR here for your feedback as well. Let me know if you would want me to touch up some more aspect of this.
[PR raised here ](https://github.com/dop251/goja/pull/407)

**Comment by tigerwill90** [comment]
Just had a look at [the example you made](https://github.com/dop251/goja/commit/15a10c29eb19602f11f05e7dd36dfcfa6bdc993e#diff-6625fab536414416a329a34c8332aa3a524cdcdee52698ec4f1cb5872eb94b3fR9), what preventing you to set a `log` function that `append` to a `slice` the value passed in parameter ? 

````go
var script = `
var a = 5;
log("Consoling from log method - statement 1")
log("Consoling from log method - statement 2")
log("Variable value "+ (a+5))
`

rt := goja.New()

list := make([]goja.Value, 0)

log := func(value goja.Value) {
	list = append(list, value)
}

if err := rt.Set("log", log); err != nil {
	panic(err)
}

_, err := rt.RunString(script)
if err != nil {
	panic(err)
}

fmt.Println(list) // [Consoling from log method - statement 1 Consoling from log method - statement 2 Variable value 10]
````
