### ISSUE TITLE
Export RegExp

### ISSUE THREAD

**Issue by jakobbraun** [dop251/goja#398]
Hi,

I would like to export a JavaScript RegExp (for example `/.*/`) to GO.
Then I want to use to put it to another VM.

Here's what I tried:

```go
vm := goja.New()
result, err := vm.RunString(`/.*/`)
if err != nil {
    panic(err)
}
fmt.Println(result.Export())
```

This example prints: `map[]`.
I'd expect something else for example the string `.*`.

Could you give me a hint if that's possible?

**Comment by dop251** [comment]
You can get the pattern and the flags and use them to create a new RegExp in the target runtime:

```go
	vm := New()
	vm1 := New()
	result, err := vm.RunString(`/a/gi`)
	if err != nil {
		panic(err)
	}
	if o, ok := result.(*Object); ok {
		if src := o.Get("source"); src != nil {
			result1, err := vm1.New(vm1.Get("RegExp"), src, o.Get("flags"))
			if err != nil {
				t.Fatal(err)
			}
			if result1.String() != "/a/gi" {
				t.Fatal(result1)
			}
		}
	}
```

Exporting regexps using Export() is problematic because ECMAScript and Go regexps are not fully compatible so there is no 'native' type to export to.

**Comment by jakobbraun** [comment]
Thank you for the super quick reply! I could reproduce you suggestion.

Is it also possible to add this somehow as a custom exporter.
So my problem now is, that the regex is in a nested object structure:

```json
{
  "id": "123",
  "regex": /.*/
}
```
I' export the whole structure via `.Export()` into a structure of interfaces and maps. Would it be possible to hook into that export to add a custom export for RegExp?

**Comment by dop251** [comment]
Presently no. You need to either do some kind of preprocessing on the JS side, or export into a `struct` with the appropriate field being a `string`, or implement your own version of `Export()`.

It probably makes sense to export RegExp into some kind of custom object, similar to `Proxy` or `Promise`, but I don't consider it a high priority.

**Comment by jakobbraun** [comment]
Thanks a lot for your quick and helpful replies.
I'm closing this, since the question was answered.
