### ISSUE TITLE
Using a type for which a map is the underlying type

### ISSUE THREAD

**Issue by hariso** [dop251/goja#399]
Hello!

First and foremost, thanks for this great project!

We use goja at [Conduit](https://github.com/ConduitIO/conduit) to support transformations in data pipelines. As I'm documenting certain use cases, I'd like to ask the following:

We have the following type:
```go
type StructuredData map[string]interface{}
```

Let's say I'm writing a JS function to operate on an instance of  `StructuredData`. Is it possible at all to use the bracket syntax to set keys? i.e. can I have this in my JS code:
```js
function transform(data) {
    data["metadata"] = something;
    return data;
}
```

**Comment by dop251** [comment]
Yes, but only as long as StructuredData does not have any exported methods. See https://pkg.go.dev/github.com/dop251/goja#hdr-Maps_with_methods for more details.

**Comment by hariso** [comment]
@dop251 Thanks for the quick reply, that helps a lot. In this case, StructuredData does have exported functions, so it looks like we'll go with the getter approach.
