### ISSUE TITLE
Add a method to builtin String type

### ISSUE THREAD

**Issue by clarkmcc** [dop251/goja#421]
I'd like to add a method to the built-in string type. Here's what I've got, and the error I am getting. First of all, is what I'm doing possible, and if so, what am I doing wrong?
```go
runtime.Get("String").ToObject(runtime).Set("toElement", func(call goja.FunctionCall) goja.Value {
    return nil
})
```
```javascript
"foobar".toElement()
```
```
Object has no member 'toElement' at <eval>:1:26(2)
```

**Comment by dop251** [comment]
You need to define the method on String.prototype, not on String.

**Comment by clarkmcc** [comment]
@dop251 ah, thank you. I tried this and am still getting the same error, so I'm assuming I'm doing something wrong...
```go
runtime.Get("String").ToObject(runtime).Prototype().Set("toElement", func(call goja.FunctionCall) goja.Value {
    return nil
})
```

**Comment by dop251** [comment]
Yes, what you're doing is `String.__proto__.toElement = ...`, and you need `String.prototype.toElement = ...`, i.e.
```go
runtime.Get("String").ToObject(runtime).Get("prototype").ToObject(runtime).Set("toElement", func(call goja.FunctionCall) goja.Value {
    return nil
})
```

**Comment by clarkmcc** [comment]
Worked perfectly. Thanks!
