### ISSUE TITLE
errors's `stack` property always include `Error`/`GoError`/something else

### ISSUE THREAD

**Issue by mstoykov** [dop251/goja#442]
While I was making k6's [promise rejection handling](https://github.com/grafana/k6/pull/2738/files) a *bit* better I noticed that I get double `GoError` in all our messages as I get the "error type" both in the message and the stack. 

You can see that in [this test](https://github.com/grafana/k6/pull/2738/files#diff-95364a5e4f0a21a1c5b4a334ab04a5753fd43a7eead55d712f6a7e3d5c6a2b3fR184-R198). Where the final message will be:
```
Uncaught (in promise) GoError: some error: GoError
      at go.k6.io/k6/js/eventloop_test.TestEventLoopRejectGoError.func1 (native)
      at <eval>:1:30(1)
      at native
```

I am wondering if the stack should have this at all :thinking: after all it is accessed by accessing `stack` so :shrug:

**Comment by dop251** [comment]
The idea was to make it consistent with v8... However, in v8 the stack property includes error message as well as its name (I suspect it's just a result of applying `Error.prototype.toString`). After this is fixed you can change your code to 

```go
value = e.vu.Runtime().ToValue(fmt.Sprintf("%s\n", stack))
```
(although I would drop `ToValue`, as you seem to be only using it as a string later.
