### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by zhughes3** [dop251/goja#443]
Hello, I am working on a legacy React codebase trying to refactor a webapp that has some XSS scripting vulnerabilities. The app gets built with webpack and then passed into Goja on the golang apps initialization.

I am trying to transform URL Search Params. My goal was to fetch the query parameters from the existing URL, do some checks, and then potentially transform the URL and force a redirect by setting `window.location`. 

My first implementation made heavy use of [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams#constructor) and the global window object. This didn't work when adding the code into goja with the error: `ReferenceError: URLSearchParams is not defined`

So, I tried a second implementation that didn't use URLSearchParams. But now, I get the following error: `ReferenceError: window is not defined`.

Do you have any recommendations on how to work around this whilst using Goja? Would this be a better use-case for the nodejs Goja? Optimally, I'd like to continue using Goja for less drift in the codebase.

**Comment by dop251** [comment]
Hi. I'm not exactly sure what you are trying to achieve, but `window` is part of the browser API, goja only implements the core ECMAScript specification.

**Comment by chenjink674** [comment]
goja runs on server backend, it seems to me that you need Html parser can run in goja? 
You could implement one using golang html parser and inject it into your vm?
