### ISSUE TITLE
Posibility to access goja bytecode and native fields of compiled programs

### ISSUE THREAD

**Issue by NULL0B** [dop251/goja#445]
Hi, nice project.

Would be nice to be able of inspecting the compiled program.

For example, here I would like to get all globals variables defined, so i must search for bind global instruction and inspect it.
As the code, other fields, and instriction structs are hidden with lowercase i cant access.

![image](https://user-images.githubusercontent.com/26231330/197375190-0fd70244-4c70-43f8-8b87-1ca628733c1b.png)

Would be nice to have the instructions structs public, and maybe some getters

**Comment by dop251** [comment]
Hi.

Neither the 'bytecode' nor the compiled programs have reached a state where I'm willing to commit to backward compatibility in terms of the API. By keeping them unexported I have the freedom to tweak them without breaking people's code. Hope this makes sense.
