### ISSUE TITLE
Adding native constructors

### ISSUE THREAD

**Issue by jeromegn** [dop251/goja#45]
I've forked and started dabbling into allowing package users to create "native" constructors and instances.

I'm implementing part of the Web API (`Response`, `Request`, `Headers`, etc.) and needed some way to create more complex instances that kept a state outside of goja.

Here's my rough implementation so far:

```go
// constructor.go

package goja

type NativeFunction func(FunctionCall) Value
type ConstructorFunction func(args []Value, inst *Object) *Object

type Method struct {
	call   NativeFunction
	length int
}

type Constructor struct {
	Name string
	r    *Runtime

	proto  *Object
	static *Object

	ctor   ConstructorFunction
	length int

	methods map[string]Method
}

func (r *Runtime) NewConstructor(name string, ctor ConstructorFunction, length int) *Constructor {
	return &Constructor{
		Name:    name,
		r:       r,
		ctor:    ctor,
		length:  length,
		methods: map[string]Method{},
	}
}

func (c *Constructor) createProto(val *Object) objectImpl {
	o := &baseObject{
		class:      c.Name,
		val:        val,
		extensible: true,
		prototype:  c.r.global.ObjectPrototype,
	}
	o.init()

	for name, method := range c.methods {
		o._putProp(name, c.r.newNativeFunc(method.call, nil, name, nil, method.length), true, false, true)
	}

	return o
}

func (c *Constructor) createStatic(val *Object) objectImpl {
	o := c.r.newNativeFuncConstructObj(val, c.ctor, c.Name, c.proto, c.length)

	// _putProp here...

	return o
}

func (c *Constructor) NewInstance(args []Value, proto *Object) *Object {
	bo := c.r.newBaseObject(proto, c.Name)
	val := c.ctor(args, bo.val)
	return val
}

func (c *Constructor) Init() {
	c.proto = c.r.newLazyObject(c.createProto)
	c.static = c.r.newLazyObject(c.createStatic)

	c.r.addToGlobal(c.Name, c.static)
}

func (c *Constructor) DefineFunction(name string, call NativeFunction, length int) {
	c.methods[name] = Method{call, length}
}
```

Surprisingly, this works ok. Here's an example of how I'm using it:

```go
func constructResponse(vm *goja.Runtime) goja.ConstructorFunction {
	return func(args []goja.Value, res *goja.Object) *goja.Object {
		res.Set("body", nil)
		res.Set("bodyUsed", false)
		res.Set("ok", true)
		res.Set("redirected", false)
		res.Set("status", 200)
		res.Set("statusText", "OK")
		res.Set("type", "default")
		res.Set("url", "")

		res.Set("text", bodyText(vm, strings.NewReader("")))

		return res
	}
}

func initResponse(vm *goja.Runtime) {
	c := vm.NewConstructor("Response", constructResponse(vm), 2)
	c.Init()
}
```

This works. Except I'm left with the same issue trying to keep state around. I have to create a bunch of closures.

For instance, for the `text()` function: I'd like it to keep around a `io.Reader` and read from it from the `text()` function.

As far as I can tell, there's already a similar pattern in goja. Namely, the `newDateObject` function seems to create a special kind of object that embed `baseObject` and a few more fields. It makes sense, except that's all unexported and I'm not sure how I can make it generic enough.

I'm mostly looking for advice on how to proceed. Ideally, from a package user's perspective, the developer would only have to provide a constructor and a struct instance to make it work.

I think maybe abstracting and exporting a few more structures would help. I guess I'd mostly need to create a few structs embedding `baseObject` or implementing `objectImpl`.

Any thoughts?

**Comment by dop251** [comment]
This seems to be a popular demand :) I deliberately tried to keep public API to minimum in case I need to change it, and I'd like to keep it that way at least for the time being.

Would it help if you could do something like this?

```go
type testNativeConstructHelper struct {
	rt *Runtime
	base int64
	// any other state
}

func (t *testNativeConstructHelper) calc(call FunctionCall) Value {
	return t.rt.ToValue(t.base + call.Argument(0).ToInteger())
}

func TestNativeConstruct(t *testing.T) {
	const SCRIPT = `
	var f = new F(40);
	f instanceof F && f.method() === 42 && f.calc(2) === 42;
	`

	rt := New()

	method := func(call FunctionCall) Value {
		return rt.ToValue(42)
	}

	rt.Set("F", func(call ConstructorCall) *Object { // constructor signature (as opposed to 'func(FunctionCall) Value')
		h := &testNativeConstructHelper{
			rt: rt,
			base: call.Argument(0).ToInteger(),
		}
		call.This.Set("method", method)
		call.This.Set("calc", h.calc)
		return nil // or any other *Object which will be used instead of call.This
	})

	prg := MustCompile("test.js", SCRIPT, false)

	res, err := rt.RunProgram(prg)
	if err != nil {
		t.Fatal(err)
	}

	if !res.StrictEquals(valueTrue) {
		t.Fatalf("Unexpected result: %v", res)
	}
}
```

**Comment by jeromegn** [comment]
Something like that could be nice for sure.

Would that set the `class` of the `baseObject` as `"F"`? Pretty useful for debugging.

It'd also be pretty nice to be able to check that a `FunctionCall.This` is an instance of `testNativeConstructHelper`.

This is actually pretty close to where I got! Here's a gist as an example: https://gist.github.com/jeromegn/b2d865f315ce50782bb9b33bea937309 (sorry, it's a bit lengthy.)

In my example, I feel like I'm using far too many closures there. I wish it was easier to access the vm. It's not a big deal though.

I also realized afterwards that I'm probably replicating the `Export` stuff. I modeled my thing from the `Date` implementation where you create a new type of object that you can pass around (as an `*Object`) and then cast it when you need it.

Any work towards being able to extend the runtime with native functionality sounds great to me.

If you don't totally dislike my implementation, I can turn it into a PR. Except I'm sure you can come up with something better give your knowledge of the codebase here!

**Comment by dop251** [comment]
It would work as specified here: http://www.ecma-international.org/ecma-262/5.1/index.html#sec-13.2.2 so the class would be set to 'Object'.

FunctionCall.This cannot be an instance of testNativeConstructHelper because testNativeConstructHelper is not a Value. I understand what you mean, but I can't see an easy way to achieve this. In javascript you could have used 'this instanceof F', but F is a Value that is created when you do rt.Set('F', ...), there is no easy way to get hold of it from within the constructor function... Why do you need it out of curiosity?

Like I said in #10 where is no easy way of marrying up the two concepts because they are too different.

**Comment by jeromegn** [comment]
Yea, I understand why it can't be a `testNativeConstructorHelper` directly. In my example, I'm wrapping whatever actual instance I want and then unwrapping when I need to access it. A bit like you did with https://github.com/dop251/goja/blob/master/date.go#L83 and then unwrapping here: https://github.com/dop251/goja/blob/master/builtin_date.go#L129-L131

Except I need to export the functions to make that work.

I need it for the same reason the `Date` class works that way. I need to store arbitrary data from Go and access it from the `Value` later. My prototypes define getters and setters for attributes that are accessed in underlying structures (like a `http.Header` or a `*http.Response`.)

I'm working on a simple JavaScript http middleware system. I initially played with V8 bindings, but that was hell.

RE ecma-262 RFC: Interesting. I imagine that might have changed in ES6? In my browser (Chrome), if I do

```js
console.log(new Response().toString())
```

I'll get a `[object Response]`. Maybe that's just a deviation by the browsers.

In any case, your example code would definitely help. It's a step in the right direction for sure.

**Comment by jeromegn** [comment]
It'd be nice to call a constructor function from outside the JS context though.

From your example, would it be possible to do the following? (or in a different way achieving the same result)

```golang
fn, _ := goja.AssertFunction(rt.Get("F"))
fn(arg0, arg1, arg2)
```

and get an object with the right prototype afterwards?

I want to be able to instantiate objects of native constructors to pass into function calls. Ideally, I would also be able to call constructors with native objects. I realize this would have to be outside the normal flow though, but "converting" things back and forth in and out the JS runtime sounds expensive.

More details about what I'm doing:
- I spawn a pool for `*goja.Runtime`, primed with all the constructors I want + running a few programs on it to preload functions I'll need later.
- I borrow from the pool to grab a function (http "middleware") and run it with custom objects (a bit like an Express.js middleware)
- Runtimes going back into the pool will be killed and new ones will take their place, primed with constructors and other stuff in the global scope.

Currently, the overhead of doing this is extremely small, getting real good RPS (maybe a 1K req/s overhead on my code.) I love that about goja. My code might be weird, but it seems to work well.

So for each request, I need to create an Object in the VM to pass to the JS functions and then from the response Object I get back, I need to convert it back to an `http.Response`. I'm sure that only takes a few microseconds, but I'm trying to reduce overhead as much as possible for hot paths (ie: getting a request.)

**Comment by dop251** [comment]
Yes, this is an equivalent of calling new fn(arg1, arg2), note arg0 is 'this' value which is not used.

**Comment by jeromegn** [comment]
(I just saw your commit)

I think my main issue with the way of setting properties and function to objects is that they are very static. There's no way to set getter and setter functions, or define their descriptors (enumerable, writable, configurable, etc.)

I want to use those because I'm dynamically getting values from "wrapped" golang interfaces. A js `Response` instance would wrap a go `*http.Response`. Calling `response.status` would return a number, which was converted from the `*http.Response.StatusCode`'s `int`.

I think with these 2 concepts, this could go a long way:

- Ability to define descriptors. Example:

```go
func (r *Runtime) DefineProperty(o *Object, name string, desc Descriptor)
```
(To map to JS' `Object.defineProperty`)

- Ability to "import" custom types. Example:

```go
func (r *Runtime) Import(o *Object, i interface{}) {
  o.imported = i // or whatever
}

res := &http.Response{}
o := r.NewObject()
r.Import(o, res)
o.ExportType() // reflect.Type representing *http.Response
o.Export() // interface{} that is a *http.Response
```

This is a bit like `Date` `*Object` works. It returns a `time.Time` if you call `.Export()` on it.

It would allow people to, with their constructor, be able to fetch the underlying go object and do things with it.

**Comment by dop251** [comment]
Exposing DefineProperty could be a useful addition, although I'd prefer to have an API like this:

```go
func (o *Object) DefineDataProperty(name string, value Value, writable, configurable, enumerable bool) { 

}

func (o *Object) DefineAccessorProperty(name string, getter, setter func(FunctionCall) Value, configurable, enumerable bool) {

}
```

Another addition could be ability to create an Object with given prototype. This way you could construct a Response object in Go:

```go
httpResponse := r.ToValue(func(ConstructorCall) Value { // it could create an empty HttpResponse object that does not wrap any *http.Response) })

r.Set("Response", httpResponse)

httpResponseProto, _ := httpResponse.Get("prototype").(*goja.Object)

resp := &http.Response{}
o := r.CreateObject(httpResponseProto)
o.DefineAccessorProperty("status", func (FunctionCall) Value { return r.ToValue(resp.StatusCode) }, nil, false, false)
...
```

If you need access to the underlying *http.Response object in Go only having a Value, you could have something like this:

```go
o.DefineDataProperty("__wrapped", r.ToValue(resp), false, false, false)
```

I understand that having o.Export() return *http.Response would be better in this particular case, but would create confusion in others, one would expect a predictable mapping between the object as it's seen in JS and its exported value.

**Comment by jeromegn** [comment]
That's interesting. I'm fine with that implementation.

How would you get the native, wrapped, value though? I imagine the result would be a `Value`.

```go
o.Get("__wrapped") // Value
```

That would, at best, give back a generic `*Object` with all exported values set on it (I think.) That's somewhat useful, but that would be fixed in time (like resolving a pointer). It wouldn't take into account the changing pointer if that's what the wrapped value was.

Your first example would work though.

Creating an object from a prototype sounds great. I'm sure you don't want to make it a separate type because that's how JS works, a prototype is a plain object. If it was possible to wrap go data somehow, it would be possible to make them more generic and not have to define accessors or data properties every time we build an object.

Btw, I love what you've done so far, this project is great :)

I'd be happy to implement some of this stuff if you can't find the time.

**Comment by dop251** [comment]
When you do ToValue() on a non-primitive type, it wraps it so that Export() returns the original value. It's even in README :) I should probably add an example to make it more obvious...

**Comment by jeromegn** [comment]
Oh cool, I totally missed that.

I think with that and the property descriptors, we'd mostly be there :D

**Comment by jeromegn** [comment]
Awesome commits :)

I think the last missing piece for me is the prototype. Setting properties happens inside the constructor and on the specific instance being created. It would be nice to have some access to the prototype.

Right now, the way I figured out how to do it is:

```go
func initResponse(r *goja.Runtime) {
	r.Set(responseName, responseConstructor)

	proto := r.Get("Response").ToObject(r).Get("prototype").ToObject(r)
	proto.DefineAccessorProperty("status",
		r.ToValue(statusGetter(r)),
		r.ToValue(statusSetter(r)),
		goja.FLAG_FALSE, goja.FLAG_TRUE,
	)
}

func responseConstructor(call goja.ConstructorCall) *goja.Object {
	setWrapped(call.This, &http.Response{
		StatusCode: http.StatusOK,
		Header:     make(http.Header),
	})
	return nil
}

func statusGetter(r *goja.Runtime) func(call goja.FunctionCall) goja.Value {
	return func(call goja.FunctionCall) goja.Value {
		return r.ToValue(MustUnwrapResponse(r, call.This).StatusCode)
	}
}

func statusSetter(r *goja.Runtime) func(call goja.FunctionCall) goja.Value {
	return func(call goja.FunctionCall) goja.Value {
		res := MustUnwrapResponse(r, call.This)
		res.StatusCode = int(call.Argument(0).ToInteger())
		return goja.Undefined()
	}
}
```

(I left out some parts, like wrapping and unwrapping the `*http.Response`)

Then, it works if I want to instantiate the same exact kind of object from outside JS like:

```go
goja.CreateObject(r.Get("Response").ToObject(r).Get("prototype").ToObject(r))
```

I'll get the same prototype for both something created within the JS context or from Go.

If that's the way to do it, then I'm ok with it.

I have a small nitpick about the new way to define properties: Why do the setter and getter need to be goja.Value? Can't they just be straight `func(goja.FunctionCall) goja.Value`? Not a big thing, just wondering about the decision here.

**Comment by dop251** [comment]
Instead of doing ```r.Set("Response", responseConstructor)``` you could wrap it into a Value first and hold on to it, and/or to the prototype:

```go
responseObject := r.ToValue(responseConstructor).(*Object)
responseProto := responseObject.Get("prototype").(*Object)
r.Set("Response", responseObject)
```
As for your other question, a) because this way you can use any Go function as setter or getter, like [here](https://github.com/dop251/goja/blob/9bbb616c1252aeff01046913dcb5afcd7c10af88/object_test.go#L23) for example and b) because the function gets wrapped into a Value internally anyway but there would be no way of getting this Value otherwise (other than calling Object.getOwnPropertyDescriptor()).

**Comment by jeromegn** [comment]
Ok everything seems pretty good with these changes. I do have another question:

Would it be possible to access the `*Runtime` from a `FunctionCall` and a `ConstructorCall`?

I tend to have to wrap all my functions in a closure so I have access to the runtime. It's incredibly useful to convert anything into `Value`s which is what a native function needs to return.

I wonder about performance too. Having to create so many closures sounds like it might take more resources than adding a struct field for a `*Runtime`. I could be wrong through! /shrug

Thanks so much for this project and adding these few features. Makes everything better.

I do have another note. I mistakenly set a `func (call ConstructorCall) Value` (notice it returns a `Value`, not an `*Object`) and I looked for the issue for an hour or so. The resulting native function didn't have a prototype (it was `nil`).

Maybe adding types for these function signatures would help prevent these issues? Like:

```go
type NativeFunction func(FunctionCall) Value
type ConstructionFunction func(ConstructorCall) *Object
```

I guess this would make it harder to change later, but it sounds useful to me (also less typing.) Also, it's really only a problem if we keep having to wrap closures to access the `*Runtime`. (I keep having to define functions that return functions with these specific signatures)

**Comment by dop251** [comment]
Can you give an example? Maybe it would make more sense to have a struct that would contain a *Runtime (and possibly other state) and then have native functions methods of that struct? This way you would always have access to the state including the *Runtime.

As for the types, it's unfortunate that such mistakes are possible, but I can't really see how it would help.

**Comment by jeromegn** [comment]
I guess I could create a struct like:

```go
type responseContructor struct {
  r *goja.Runtime
}

func(c *responseConstructor) doSomething(call goja.FunctionCall) goja.Value {
  // c.r is the Runtime
}

func initResponseConstructor(r *goja.Runtime) {
  ctor := r.ToValue(ctorFn).(*goja.Object)
  
  rc := &responseConstructor{r}

  proto := ctor.Get("prototype").(*goja.Object)
  proto.Set("doSomething", rc.doSomething)

  r.Set("Response", ctor)
}
```

I think I had a mental model conflict with this because I kept thinking of the struct holding the runtime reference as an instance built by the constructor, but I guess it's fine if it's a struct representing a contructor.

Creating types for common function signature helps reduce errors and requires less code writing. It's easy to mistype the function signature when you're returning it from another function. I personally won't be running into it so much by using a struct as outlined above, but it could simply some code internally for goja? Just a small thing :)

You can close this issue if you want. I feel like it satisfies all the needs of native constructors. I'm leaving it open right now just in case you aren't.

**Comment by edaniels** [comment]
I wish I read this and saw this project earlier! I did something like this a couple of days ago in otto at https://github.com/edaniels/otto/commit/d873303836d8c5b7e5239658b7b876cab661b99a. I doubt it will be of much use now but you never know.

**Comment by SmaugTheGreat** [comment]
I think it should be corrected in the readme (or in the code) that `func(ConstructorCall) *Object` returns an object and not a Value because it got me royally confused.
