### ISSUE TITLE
Issue when compiling typescript 5.0 compiler

### ISSUE THREAD

**Issue by vanackere** [dop251/goja#456]
Hi,

It looks like the next typescript compiler version (currently I tested with 5.0.0-dev.20221116) is compiled to a newer js dialect (es2018 ?) with features that goja does not support.

Would it be possible to add support for rest and spread properties for object literals in goja ? It looks like this would allow to run the current development typescript compiler properly 

https://github.com/tc39/proposal-object-rest-spread

**Comment by dop251** [comment]
It is supported as far as I can see.

**Comment by vanackere** [comment]
Oups you're right, it looks like this is a different issue with the generated js, I made a quick and wrong assumption about the problem. The exact error message I get is 
"Lexical declaration cannot appear in a single-statement context "

Appearing at the second line of this code:
---------------------
           case 264 /* ModuleDeclaration */:
              const moduleExports = ((_a2 = getSymbolOfNode(location)) == null ? void 0 : _a2.exports) || emptySymbols;
 -------------------

**Comment by vanackere** [comment]
Commenting the check in statement.go (I don't know if it was correct or not) let me go further in the compilation but unfortunately it looks like the generated code also depends on support for generators (https://github.com/dop251/goja/issues/436)

In the short term I have no other choice than downleveling the code to remove generator usage...
Feel free to close this bug if you wish

**Comment by dop251** [comment]
The error message could mean there is a bug. Can you provide a bit more context? I could not reproduce it and I could not find this in the TypeScript source repo.

**Comment by vanackere** [comment]
You should be able to easy reproduce this using `npm install typescript@next` and then loading the script located at node_modules/typescript/lib/typescript.js with goja

Le me know if you need a repository with the full testcase

**Comment by vanackere** [comment]
```go
package ts

import (
	"testing"

	"github.com/dop251/goja"

	_ "embed"
)

//go:embed node_modules/typescript/lib/typescript.js
var tsCompilerJS string

func TestTypescript(t *testing.T) {
	vm := goja.New()
	_, err := vm.RunString(tsCompilerJS)
	if err != nil {
		t.Fatal(err.Error())
	}
}

```

**Comment by vanackere** [comment]
Please note that there is a related tslint case :

**Comment by dop251** [comment]
Nevertheless, it was a bug. Thanks for reporting!
