### ISSUE TITLE
Functions defined in js eventually be released safely?

### ISSUE THREAD

**Issue by chenjink674** [dop251/goja#461]
goja is a cool project, but I still have some things I don't quite understand.Will functions in vm eventually be released safely?
I would like to know when the functions are safely released, or  always exist in my vm?

For example:

1. Functions that are in the js script
2. Go functions that are set into the vm 
3. Functions injected through custom modules from go

Thanks in advance!

**Comment by dop251** [comment]
Everything in goja is normal Go values and therefore subject to GC, i.e. a value is removed at some point after it becomes unreachable.
