### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by fupengl** [dop251/goja#465]
```js
const fileBuffer = Buffer.from(base64, 'base64')
```

**Comment by dop251** [comment]
`Buffer` is not part of the [ECMAScript](https://tc39.es/ecma262/) standard and therefore is out of the scope of this project. It could be implemented in [goja_nodejs](https://github.com/dop251/goja_nodejs) and in fact I have done some work on it, but it's not ready for production yet.
