### ISSUE TITLE
AssertFunction fails for object.function_name

### ISSUE THREAD

**Issue by keenskelly** [dop251/goja#468]
Hello! I have found a work-around for this issue that works for me, but it might be worth addressing to broaden overall compatibility. I created a simple object (function) with a nested function, but goja.AssertFunction() does not recognize the inner func. The workaround I used is to expose the inner function with an external assignemnt which goja.AssertFunction() does recognize. Both are represented in the example here. Am I overlooking something here?

**Example**
```
vm := goja.New()
vm.RunString(`
        function example() {
                this.hello = function() { return "Hello, World!"; }
        }
        ex = new example();
        exhello = ex.hello;
`)

// call exhello() <- this is our workaround; it works just dandy!
hello, _ := goja.AssertFunction(vm.Get("exhello"))
message, _ := hello(goja.Undefined())
fmt.Printf("Message: '%s'\n", message.ToString())

// call ex.hello() <- this is what we really wanted to do, but fails!
hello, ok := goja.AssertFunction(vm.Get("ex.hello"))
if ! ok { panic("Not a function: ex.hello") }
message, err := hello(goja.Undefined())
if err != nil { panic(err) }
fmt.Printf("Message: '%s'\n", message.ToString())

```
**Output**
Message: 'Hello, World!'
panic: Not a function: ex.hello

**Details**
Go 1.17.1
Ubuntu 18.04.2

**Comment by dop251** [comment]
Hi. The argument of `Get` is a property name, not an expression. In order to get to a nested property you can do something like this:

```go
vm.Get("ex").ToObject(vm).Get("hello")
```

or you can do this (but it will be slower):

```go
val, err := vm.RunString("ex.hello")
```

**Comment by keenskelly** [comment]
It works (!!) with:
`
hello, ok := goja.AssertFunction(vm.Get("ex").ToObject(vm).Get("hello"))
`
Thank you! Amazing project here, just found the other day, so still orienting myself, looking for examples, etc. (And to think that I almost got sucked into Tengo).
