### ISSUE TITLE
Wrapping map in a type breaks toValue after 6c0d9883792e42e6da320ac03ae0d6c1b0cd7530

### ISSUE THREAD

**Issue by mstoykov** [dop251/goja#469]
After 6c0d9883792e42e6da320ac03ae0d6c1b0cd7530 (git bisected it) it seems like wrapping `map[string]interface{}` breaks toValue at least in parts. The following example illustrates it

```golang
package goja

import "testing"

type mapping map[string]interface{}

func TestFunctionInMap(t *testing.T) {
	const SCRIPT = `
    a.s();
	`

	r := New()

	r.Set("a", mapping{ // !!!!!!!!!!!!  swapping for map[string]interface{} works
		"s": func() bool { return true },
	})

	prg := MustCompile("test.js", SCRIPT, false)

	res, err := r.RunProgram(prg)
	if err != nil {
		t.Fatal(err)
	}

	if !res.StrictEquals(valueTrue) {
		t.Fatalf("Unexpected result: %v", res)
	}
}
```

This will say that you can't call `[object Object]` but it will work if you swap mapping for the `map[string]interface{}` or use `ToValue` directly on the `func()` or if it is `func(FunctionCall) Value`. Probably other variants work as well.

The reflect code behaves strangely, and it seems like the origValue just happens to not be of Kind `func` . But ` reflect.ValueOf(i)` does return `func`. 

Just replacing `origValue` with `reflect.ValueOf(i)` ... breaks, obviously in some other cases. :( 
https://github.com/dop251/goja/blob/b95230a9dbad42ddf5220c752e5d396eb58f405f/runtime.go#L1861

**Comment by mstoykov** [comment]
Reverting the changes to object_gomap_reflect.go from https://github.com/dop251/goja/commit/6c0d9883792e42e6da320ac03ae0d6c1b0cd7530 fixes the issue and does not fail any other tests. 

But this seems wrong to me. Also, I don't understand why `value` returns different thing from `reflect.ToValue(value.Interface())` - that seems like the kind of thing that should give you equal values, but I have not used `reflect` all that much.

**Comment by dop251** [comment]
`MapIndex` returns an `reflect.Value` which is an interface which is kind of makes sense because that's what the map's element type.  `reflect.ValueOf()` on the other hand always returns the concrete value, not the interface.
