### ISSUE TITLE
A problem with AsyncContextTracker

### ISSUE THREAD

**Issue by mstoykov** [dop251/goja#472]
I have been trying to use the AsyncContextTracker and has so far hit some problems.

As previously explained we have this thing called `group` that calls a provide js function after changing some state and then restores it on the function finish. It also happens to measure how long the call takes. Nested `group` calls are allowed and base the state on each others. 

The problem boils down to Suspend not being called on async function "returning". 

Here is (probably too complicated) example: 

```javascript
group("1", async () => {
  // line A
  await 3;
  // line B
  group("2", async () => {
     // line C
     await 4;
     // line D 
 })
}).then(() => {
  // line E
})
```
Implementation detail:
In this implementation `group` makes a promise and resolves it directly so it can run it's AsyncFunction argument, so running `group("1", asyncFunc)` will run asyncFunc *after* `group` has returned and the stack is empty. It also returns wraps the returned (by its argument) promise and basically calls `.then` on it before returning the result of `.then`. Effectively chaining some more bookkeeping.

From what I can get the above works as:
On `line A` we have the correct value as `group` has made certain to set it before calling into the async function.
`await 3` suspends and then (in this case) immediately resumes with the value provided and in this cases we clear it and set it appropriately. 
On `line B` we have the value due to above :tada: 
`group 2` will now record the value we care about, make a promise and resolve it with it onFullfill having the correct value and using it to generate the new one. We now have one job queued to run the inner async function.
We return from `group 1`, in this case we have a the promise of the async function resolving, but as it is wrapped in another (for `group` internals - including clearing the value) which gets queued. 
But first we have to actually start executing the `group 2`
`line C` has the correct value, we go to await, which in this case leads to the resolution of the promise actually *returned* byt `group 1` which leads to queuing the last callback with line E.
Before it can return to we go back to `await 4` which resumes and we set the correct value.
At this point `line D` has the correct value and we return, effectively queuing the clearing of the `group 2` 
We go back to `line E` and ... it has the value we had at `line D` as nothing has yet told it to clear it.

Which is not good.

From my experiments, even with changes this will be a problem. Not getting that a previously executing resumed async function is now returning + no indication that a Promise job is starting, makes it so that there is no way for a host application to know that we go from one to the other. Which means that no way to clear anything that AsyncContextTracker was used to restore.

### Proposed solution:

It seems like just making it possible to know that a previously resumed async function returns(or I guess gets an exception) will be enough for this case. But it likely will be nice to know that an async function is also called. Not certain if it is a good idea to reuse both of the functions on AsyncContextTracker or there should be new ones.

p.s. I will try to make a smaller example with go code tomorrow, but have been pinpointing and fixing problems for a while and wanted to open an issue in case I need to work on something else in the mean time.

**Comment by dop251** [comment]
Hi. I would implement `group` slightly differently, returning the original promise rather than chaining another one. Going to push my changes in a separate branch shortly, let me know what you think.

Note, that if you chain the promise, you could clear the context in your `then` and `catch` hooks, so that the `Completed()` would not be required. However, it's easier to do it this way (also I suspect chaining could break async stacktraces).

**Comment by mstoykov** [comment]
>  returning the original promise 

This would be great but I needed a way to know that the group has compleated so that I can note how long it took to execute(in this case). As there is no other signal for that apart from the promise resolving - I need to use that and as you can have only one onFulfil (for example) callback I need to chain on the original and return it. I am not certain if you meant the same thing :thinking:  :shrug: 

> at if you chain the promise, you could clear the context in your then and catch hooks,

That is what basically happesn but from my experiments and thinking about it *unless* there is `Completed` call (as you have implemented) there is no way to be certain the host application will clear the state before another promise job gets to run. It will change the exact place it will happen, but I am pretty sure there is no way around it. 

Obviously this won't be a problem if you are arguing that the js code can be written to do it - but here the case is that we provide a helper that users use. So that needs to happen authomathically for them.

**Comment by mstoykov** [comment]
I can confirm that my version also works perfectly fine with `Completed` and I can arguably skip the wrapping now that I have `Completed` . Or at least I think so, as I haven't actually tried that part :sweat_smile:

**Comment by dop251** [comment]
So, does it solve the issue?

**Comment by mstoykov** [comment]
Sorry I though I have answered that - but yes, this seems to fix everytrhing and I managed to rewrite my WIP code to not need to wrap the returned Promise which is great improvement in the readability of the code :sweat_smile:
