### ISSUE TITLE
Can I do `sleep` and can I generate random numbers?

### ISSUE THREAD

**Issue by callebtc** [dop251/goja#473]
Thank you for this lib! I am not a JS dev so please excuse if the answers to my questions are obvious or trivial. 

* Can I somehow use it to sleep for n milliseconds? 
* Can I draw random numbers? 

That's it. I'd be very glad if someone could give an example of how I could achieve this.

**Comment by sigxcpu76** [comment]
```go
vm := goja.New()
vm.Set("sleep", func(ms int) { time.Sleep(time.Duration(ms)*time.Millisecond)})
```
