### ISSUE TITLE
Modifying objects in javascript fails silently

### ISSUE THREAD

**Issue by TristanSpeakEasy** [dop251/goja#475]
Hi

I am trying to modify a Golang object in javascript by adding an additional property to the object.

But after trying to do so when reading the property again in javascript it doesn't contain the set value (it is just undefined).

I recently switched over from Otto where I was setting an object from Golang, modifying it in javascript and then able to retrieve it again from Golang (it was now a map instead of the original go object) and then set it again in another js script and use the modified value.

But goja seems to just silently fail, no errors that modifying the object wont work. (Should it throw an exception in this case?)

Ideally I would be able to modify the object and get the modification back in the golang side.

Is there anyway to achieve this with Goja currently?

Thanks

**Comment by dop251** [comment]
Hi.

Assignments to non-writable properties fail silently in ECMAScript in non-strict mode. You should get a TypeError thrown in strict mode.

**Comment by TristanSpeakEasy** [comment]
Hi, yes thank you there was an instance of Compile I was calling with strict mode set to false and your comment helped me find it thank you.

And for now I have found a work around to the use case I want by using https://github.com/fatih/structs to convert the object to a map before injecting into the JS

**Comment by ernest-ag5** [comment]
Hi, I am using a custom type
```
 type EventsInputType map[string]any
```
If my function returns a value of this type (instead of the raw map), it is currently not possible to write properties to that value. Should it? @dop251

**Comment by dop251** [comment]
Yes, unless the type has exported methods, see https://pkg.go.dev/github.com/dop251/goja#hdr-Maps_with_methods

**Comment by ernest-ag5** [comment]
thanks @dop251 , that explains the behaviour I am seeing
