### ISSUE TITLE
Object not being added to array as expected

### ISSUE THREAD

**Issue by TristanSpeakEasy** [dop251/goja#476]
Hi,

I have come across a bug with an array within a nested object structure within a top level Go map not being set as I would expect.

My expectation is that `{"test":{"test":[{"Name":"test"}]}}` is the expected output from the console.log but running the below code I have provided to reproduce the issue the output is `{"test":{"test":[]}}`

Here is code to reproduce the issue

```
package main

import (
	"io"
	"net/http"

	"github.com/dop251/goja"
	"github.com/dop251/goja_nodejs/console"
	"github.com/dop251/goja_nodejs/require"
)

func read() []byte {
	res, err := http.Get("https://underscorejs.org/underscore-min.js")
	if err != nil {
		panic(err)
	}
	defer res.Body.Close()

	data, err := io.ReadAll(res.Body)
	if err != nil {
		panic(err)
	}

	return data
}

type Context struct {
	Global         any
	Local          any
	GlobalComputed any
	LocalComputed  any
}

func main() {
	data := 1
	globalComputed := map[string]any{}

	vm := goja.New()
	_, err := vm.RunString(string(read()))
	if err != nil {
		panic(err)
	}

	new(require.Registry).Enable(vm)
	console.Enable(vm)

	if err := vm.Set("context", &Context{
		Global:         data,
		GlobalComputed: globalComputed,
		Local:          data,
		LocalComputed:  globalComputed,
	}); err != nil {
		panic(err)
	}
	_, err = vm.RunString(`
function mergeTypes(outTypes, inTypes) {
  _.each(inTypes, (tt, scope) => {
    if (!outTypes[scope]) {
      outTypes[scope] = {};
    }

    _.each(tt, (t, model) => {
      if (!outTypes[scope][model]) {
        outTypes[scope][model] = [];
      }

      _.each(t, (type) => {
        if (
          !outTypes[scope][model].find((e) => {
            return e.Name === type.Name;
          })
        ) {
          outTypes[scope][model].push(type);
        }
      });
    });
  });

  return outTypes;
}

context.GlobalComputed.Types = {};

context.GlobalComputed.Types = mergeTypes(context.GlobalComputed.Types, {
  "test": {
	"test": [
		{
			"Name": "test"
		}
	]
  }
});

console.log(JSON.stringify(context.GlobalComputed.Types));
	`)
	if err != nil {
		panic(err)
	}
}
``` 

If I run the same code using a locally created JS object ie:

```
ctx = {
	GlobalComputed: {
		Types: {}
	}
};

ctx.GlobalComputed.Types = mergeTypes(ctx.GlobalComputed.Types, {
	"test": {
	  "test": [
		  {
			  "Name": "test"
		  }
	  ]
	}
  }
);
console.log(JSON.stringify(ctx.GlobalComputed.Types));
```

The output is as expected.

Maybe I am doing something wrong or misunderstanding a limitation here but any help is appreciated

**Comment by dop251** [comment]
Please read the caveats [here](https://pkg.go.dev/github.com/dop251/goja#Runtime.ToValue), especially caveat number 3 which I believe applies here.

**Comment by TristanSpeakEasy** [comment]
Is this something that can be worked around by passing the map in as a pointer? Or should I be looking at instantiating this object in JS and retrieving it from golang if I need access to it in both worlds?

**Comment by dop251** [comment]
The map is fine as is, the inner slice should be a pointer.

**Comment by TristanSpeakEasy** [comment]
In this case everything within the map is intended to be created within the JS world, meaning I can't ensure it is a pointer can I?

**Comment by dop251** [comment]
No, unless you make the map typed (i.e. `map[string]*[]any`) or expose a slice constructor that returns `*[]any` and use that instead of a usual way of creating arrays in JS. Or you could use a native javascript Object instead of the map and use `Get()` and `Set()` to manage it from Go. You can also check out DynamicObject.

**Comment by TristanSpeakEasy** [comment]
Great thank you very much for the help, I tried creating the top level object in JS and using Get/Set to managed it as you suggested and that works for me for now.

The behavior with the above example is counterintuitive to how I would have expected it would work though, that the Go map would have been filled up with `goja.Value` as they were js objects and arrays being created and therefore I could use them as I would have used any other JS value.

If they were Go objects I would have expected some limitations on modification but not that JS object would encounter limitations when added to a map or go slice.

Is the a sane expectation? And maybe points to an improvement that can be made in goja? Or am I missing some fundamental understanding as to why its implemented like this?

**Comment by dop251** [comment]
The idea is that `Value` is not exposed in exported or wrapped Go values, that's the whole point of "exporting". So the current behaviour is by design.

Like I said a few times before, there is no one-to-one match between ES and Go, so whatever interop you implement someone will find it counterintuitive. That's why there is a number of options available including DynamicObject and DynamicArray.
