### ISSUE TITLE
Stack incorrect after recursive RunProgram calls

### ISSUE THREAD

**Issue by TristanSpeakEasy** [dop251/goja#477]
Hi,

We are doing some slightly novel stuff with https://github.com/speakeasy-api/easytemplate to allow the embedding of JS within golang's text/templates. 

This package allows for some recursive behavior when interacting with the JS runtime such as `go (RunProgram) -> js (Call to Go to template file) -> go (Template File) -> template (Call go function to run JS) -> go (RunProgram) -> js (Call to Go to template file) -> go (Template File) -> template (Call go function to run JS) -> go (RunProgram)  -> js` etc

This generally seems to work okay except I have run into a bug which results in a `TypeError: Value is not an Object` error. This happens when trying to access the `underscore` library that is imported at the start after some level of recursion.

I have attempted to debug this but my unfamiliarity with the Goja code is hindering my progress to find the cause. But I have a reproducible of it within this test https://github.com/speakeasy-api/easytemplate/blob/main/engine_integration_test.go

Basically the test will fail with an error like `TypeError: Value is not an Object at inline:2:8(13) at github.com/speakeasy-api/easytemplate.(*Engine).init.func1.1 (native) at github.com/speakeasy-api/easytemplate.(*Engine).init.func1.1 (native)` after trying to execute the code here: https://github.com/speakeasy-api/easytemplate/blob/main/testdata/templates/test4.stmpl#L4

Which itself is executed from https://github.com/speakeasy-api/easytemplate/blob/main/internal/template/template.go#L194

From my debugging the value it gets from the stack when calling `getFuncObject(vm.stack[vm.sb-1])` at https://github.com/dop251/goja/blob/master/vm.go#L3724 is a string value instead of the intended `_` underscore object.

Any help figuring this out would be appreciated as I haven't yet found a workaround to unblock me.

**Comment by dop251** [comment]
Thanks for reporting!

**Comment by dop251** [comment]
I've just realised the fix was incomplete...
