### ISSUE TITLE
Make object/var/function immutable/constant?

### ISSUE THREAD

**Issue by rucuriousyet** [dop251/goja#48]
I'm wondering how I could make a value created using `vm.Set()` constant or immutible. I know that ES5 doesn't support `const` but what about Object.freeze or similar methods? I am trying to make sure the JS callable Go functions and mapped vars can't be accidentally overwritten to another value.

**Comment by dop251** [comment]
Instead of vm.Set("x", x) you can use this:

```go
vm.GlobalObject().DefineDataProperty("x", r.ToValue(x), goja.FLAG_FALSE, goja.FLAG_FALSE, goja.FLAG_TRUE)
```
