### ISSUE TITLE
Clarification on func(FunctionCall) argument reference safety

### ISSUE THREAD

**Issue by zllovesuki** [dop251/goja#487]
According to the godoc:

*Functions*

*func(FunctionCall) Value is treated as a native JavaScript function. This increases performance because there are no automatic argument and return value type conversions (which involves reflect). Attempting to use the function as a constructor will result in a TypeError. Note: implementations must not retain and use references to FunctionCall.Arguments after the function returns.*

Does it apply to:
1. Only `FunctionCall.Arguments` (`[]goja.Value`) the slice itself?
2. Any individual `goja.Value` from `FunctionCall.Argument(idx)`?
3. Or, even the `interface{}` from `.Export()`?

You can imagine the go function taking an `ReadableStream` returning a Promise (say network fetch) then resolve the promise with `Response`.

**Comment by dop251** [comment]
Only the slice, because it can be a slice of the value stack.
