### ISSUE TITLE
Maybe using the Just-In-Time(JIT) can improve performance ?

### ISSUE THREAD

**Issue by rickyggg** [dop251/goja#494]
Using JIT may reduce repetitive js interpretation to improve js vm performance

**Comment by chenjink674** [comment]
I did a test on js_ast.Program and goja.Program before and it seems that the above 2 structus cannot be serialized to disk except for saving them in map. 
ex: map["script1"] = &js_ast.Program or map["script1"] = &goja.Program

**Comment by dop251** [comment]
This is not on the roadmap. The goal of this project is to provide a stable, idiomatic(-ish) implementation of ECMAScript in Go. You may want to consider a v8 wrapper instead.
