### ISSUE TITLE
How to get promise exception?

### ISSUE THREAD

**Issue by monkeyWie** [dop251/goja#496]
Thank you for this great project!
How can I get the error information in Go when I execute and return a Promise in JS? Currently, I can only do it through the String() method. Is there a better way?

This is a sample code:
```
promise, err := vm.RunString(`
(async function(){
  throw new Error('fail');
})
`)
if err != nil {
  return nil, err
}

result := promise.Export().(*goja.Promise).Result()
// result.String() => Error: fail
fmt.Println(result.String())
// result.Export() => empty map[string]interface{}
fmt.Println(result.Export())
```

I noticed that there is actually an error object. How can I get it?

![image](https://user-images.githubusercontent.com/13160176/233597848-d15f7e20-d275-4577-b611-bac7dc09336f.png)

**Comment by dop251** [comment]
Hi. Not sure what you mean by "get it". The returned value _is_ the error object. The reason `Export()` returns an empty map is because its properties are non-enumerable, but you can get them by using `result.(*goja.Object).Get("message")` for example.

**Comment by monkeyWie** [comment]
Sorry, I didn't express clearly, I mean is how can I assert the error type, such as throwing a TypeError or URIError in JavaScript. How can I differentiate between them?

**Comment by dop251** [comment]
For that you will have to use a javascript function I'm afraid, i.e. `v, err := vm.RunString("e instanceof TypeError")`. There is https://github.com/dop251/goja/issues/268

**Comment by monkeyWie** [comment]
Thks! I get it
