### ISSUE TITLE
incompatible with algebra.js?

### ISSUE THREAD

**Issue by lxy071130** [dop251/goja#497]
For some reason I had to use algebra.js with goja.I ran the one modified by me with node.js and it seems that everything worked well.But when I use it in goja,it just return an empty `c.solveFor()`.  
I have no idea how this is happening and I wonder if this can be fixed.  
[here](https://pastebin.com/emU2jxLp) are the modified version.  
At last thanks greatly for developing this awesome project!

**Comment by dop251** [comment]
Hi. I'm getting the same result running the code in both nodejs and goja:
```console
$ node a.js
{"numer":4,"denom":1}
```

```console
$ goja a.js
2023/04/29 12:09:42 {"numer":4,"denom":1}
```
Are you using the latest version of goja?
