### ISSUE TITLE
InterruptedError should also implement String()

### ISSUE THREAD

**Issue by slavikm** [dop251/goja#50]
And return the string representation of `iface`
Otherwise, for every error we will need to check if it is InterruptedError and treat it differently.

**Comment by dop251** [comment]
InterruptedError is sort of meant to be treated differently, because it's not really an error. Could you please illustrate with some code?

**Comment by slavikm** [comment]
```go
	vm := goja.New()
	vm.Set("console", map[string]interface{}{"log": js.ConsoleLog(scriptName)})
	timer := time.AfterFunc(timeout, func() {
		defer util.RecoverWithStack()
		vm.Interrupt(fmt.Errorf("script %s timeout after %d", scriptName, timeout))
	})
	defer timer.Stop()
	res, err = vm.RunScript(scriptName, script)
	if err != nil {
		if ierr, ok := err.(*goja.InterruptedError); ok {
			log.Errorf("JS error: %v ", ierr.Value())
		} else {
			log.Errorf("JS error: %v", err)
		}
		return
	}
```
So, instead of just logging the issue, I need to check the type of error and then log it. Otherwise, I'm getting `<nil>` in the error instead of the timeout error.

**Comment by dop251** [comment]
Ok, raise a PR.
