### ISSUE TITLE
[]byte/string parameter conversion oddity

### ISSUE THREAD

**Issue by liclac** [dop251/goja#51]
```go
func TestByteToString(t *testing.T) {
	rt := goja.New()
	rt.Set("v", []byte("hi"))
	rt.Set("fn", func(v string) {
		assert.Equal(t, "hi", v)
	})
	_, err := rt.RunString(`fn(v)`)
	assert.NoError(t, err)
}
```

Expected "hi", got "104,105". Looks like mangling of arrays that could use a special case for `[]byte`? The opposite direction appears to work just fine.

**Comment by dop251** [comment]
I'm not sure []byte should be converted to string. Not only they are distinct data types, but one is immutable, the other is not. This means the data will be copied during the conversion which is inconsistent with how it normally works.

I had an idea of converting []byte into ArrayBuffer which is more suitable, but never really had the time to implement it.

**Comment by liclac** [comment]
Hm, good point. The dilemma we're facing with k6 is that we need some functions to accept string literals, but we also need to be able to handle binary data (POST-ing images being the big one that comes up) in some kind of sane fashion.

If I were to contribute an ArrayBuffer implementation, how would I go about doing it?

**Comment by dop251** [comment]
Make sure it passes all relevant tc39 tests and raise a PR. However you could consider wrapping []byte into a custom type before passing it to ToValue(). You could then define methods on that type and use them in JS. It all depends on what you want to do with it...

**Comment by dop251** [comment]
I'm closing this, if you do implement ArrayBuffer, please raise a PR
