### ISSUE TITLE
How to ensure concurrency？

### ISSUE THREAD

**Issue by cjf621** [dop251/goja#518]
var dummy = 1;
function onrev(
){
dummy=3;
};

gofunc();
log(dummy);

I currently have this type of code，the gofunc is Go Thread ，this callback onrev，the i use the lock  for  vm.run,then gofunc is  it

func gofunc(){
go runscript()
}
func gofunc(){
lock();
vm.runscript()
unlock();
}
then the onrev is run after  the script Running completed，
  how to i want?

**Comment by dop251** [comment]
In order to achieve concurrency with ECMAScript you must use an event loop, for example this one:  https://github.com/dop251/goja_nodejs/tree/master/eventloop

**Comment by cjf621** [comment]
> 为了实现ECMAScript的并发性，您必须使用一个事件循环，例如:[https://kgithub . com/DOP 251/goja _ nodejs/tree/master/event loop](https://github.com/dop251/goja_nodejs/tree/master/eventloop)

I can understand it this way，the vm runscript is not need lock，the lock need for the vm in vaule？

**Comment by dop251** [comment]
You can't do `go vm.RunProgram(prg)`. In fact, you should not use `vm` anywhere outside the function that runs on loop.
