### ISSUE TITLE
Modifying a pointer to a slice from Go doesn't seem to update properly in goja

### ISSUE THREAD

**Issue by ganigeorgiev** [dop251/goja#521]
Modifying a slice value or pointer to a slice from Go doesn't seem to update properly in goja. Consider the following code sample:

```go
package main

import (
    "fmt"

    "github.com/dop251/goja"
)

func main() {
    data := &[]int{}

    vm := goja.New()
    vm.Set("data", data)
    vm.Set("print", fmt.Println)
    vm.Set("append", func(a *[]int, v int) {
        *a = append(*a, v)
    })

    _, err := vm.RunString(`
        // modify with js
        data.push(1);
        print("push:", data.length); // 1

        // modify with go
        append(data, 2)
        print("append:", data.length); // still 1

        // but both elements are there
        print("data.0", data[0]) // 1
        print("data.1", data[1]) // 2
    `)
    if err != nil {
        panic(err)
    }
}
```

I haven't explored the goja internals yet to understand what actually is happening, but:

1. Is this some version of the [implementation caveats mentioned in the readme](https://pkg.go.dev/github.com/dop251/goja#Runtime.ToValue)?

2. If it is a caveat, is there a workaround, even if that means sacrificing the performance, eg. overwriting the default array behavior?

**Comment by dop251** [comment]
This is a case of an overzealous optimisation around the `length` property, and not maintaining the original value type for non-reflect slices (does not directly apply to your case, but still needs fixing).
