### ISSUE TITLE
Calling goja registered callback in a goroutine panics

### ISSUE THREAD

**Issue by ganigeorgiev** [dop251/goja#522]
I completely forgot about the [goroutine-safety note](https://github.com/dop251/goja#is-it-goroutine-safe) in the README while working on the goja integration for my project, but just to make sure that it is expected behavior and not a bug, consider the following minimal code:

```go
package main

import (
	"fmt"
	"sync"

	"github.com/dop251/goja"
)

type App struct {
	hook func()
}

func (a *App) SetHook(f func()) {
	a.hook = f
}

func (a *App) ExecHook() {
	if a.hook != nil {
		a.hook()
	}
}

func main() {
	app := &App{}

	// add a hook callback via the VM
	vm := goja.New()
	vm.Set("app", app)
	vm.Set("print", fmt.Println)
	_, err := vm.RunString(`
		app.SetHook(() => {
			print(1)
		});
	`)
	if err != nil {
		panic(err)
	}

	// perform some concurrent operation with the Go code
	var wg sync.WaitGroup
	wg.Add(3)
	for i := 0; i < 3; i++ {
		go func() {
			app.ExecHook()
			wg.Done()
		}()
	}
	wg.Wait()
}
```

Note that the goja script itself doesn't execute in a separate goroutine, but the wrapped function seems to be affected when running concurrently as it results in the following panic:

```sh
panic: runtime error: index out of range [5] with length 5 [recovered]
	panic: runtime error: index out of range [5] with length 5 [recovered]
	panic: runtime error: index out of range [5] with length 5
```

If it is expected behavior, is there a workaround to somehow automatically "unwrap" the goja function and convert:

```go
_, err := vm.RunString(`
    app.SetHook(() => {
        print(1)
    });
`)
```

to:

```go
vm.Set("callback", func() {
    print(1)
})
_, err := vm.RunString(`
    app.SetHook(callback);
`)
```

**Comment by dop251** [comment]
This is an expected behaviour because you're calling the arrow function which alters the VM state (as it uses the stacks, etc.). And no, there is no way to automatically "unwrap" the function, because in general case it's not known what it is doing (in your case it just calls `print`, but it could have been doing much more than that).

**Comment by ganigeorgiev** [comment]
Thanks for the quick response. I suspected that this is the case, but I didn't want to acknowledge that I spent almost 3 weeks working on something that it seems will not work as I intended. I should have tested my use case with concurrent clients from the beginning...
Anyway, I will spend a little more time experimenting with adding some sort of global synchronization (mutex/channel) and will see if that will be feasible at all.

**Comment by ganigeorgiev** [comment]
Just for info in case someone stumble here - the goja integration was refactored with slightly different API to workaround my earlier oversight. The main difference is that we now execute each route, middleware, etc. handler, that is usually running in its own gorouine, as a standalone goja program.

Some high overview of the current approach could be found in https://github.com/pocketbase/pocketbase/discussions/2825#discussioncomment-6376210.

_Documentation and examples how goja is used as part of the application could be also found in https://pocketbase.io/docs/js-overview/._
