### ISSUE TITLE
Clarify currently supported ES Version

### ISSUE THREAD

**Issue by Simerax** [dop251/goja#534]
The Readme currently says `ECMAScript 5.1(+) implementation in Go.`
and `Most of ES6 functionality, still work in progress`

The ES6 Milestone (https://github.com/dop251/goja/milestone/1) however is completed by now. Does this mean that Goja is actually ES6/ES2015 (+)?

It would be great to either create new issues for missing (ES6) features and add them to the ES6 milestone or to update the readme.

**Comment by dop251** [comment]
See my comment here: https://github.com/dop251/goja/discussions/520#discussioncomment-6269189
