### ISSUE TITLE
how to reuse goja.Program?

### ISSUE THREAD

**Issue by wxyz520** [dop251/goja#535]
I precompiled the JavaScript code into Map[string] *goja.Program, and each time I use it, I can directly retrieve it from the Map and execute RunProgram. I want to know goja.Program is goroutine-safe？ , and how to reuse goja.Program

**Comment by dop251** [comment]
It is documented, but in a slightly wrong place I think: https://pkg.go.dev/github.com/dop251/goja#Compile
I'll probably move it to https://pkg.go.dev/github.com/dop251/goja#Program
