### ISSUE TITLE
Strange behavior when using let assignment that throws exception

### ISSUE THREAD

**Issue by gbl08ma** [dop251/goja#539]
I ran into strange behavior when using `let` to create variables. See the following minimal example, where I have already commented the current resulting error values for convenience:

```go
package main

import (
	"fmt"

	"github.com/dop251/goja"
)

var vm *goja.Runtime

func callback(call goja.FunctionCall) goja.Value {
	panic(vm.NewTypeError("test TypeError"))
	return goja.Undefined()
}

func main() {
	vm = goja.New()
	vm.Set("callback", callback)
	_, err := vm.RunString(`let result = callback()`)
	fmt.Println(err) // TypeError: test TypeError at main.callback (native) <-- expected
	_, err = vm.RunString(`result = "something else";`)
	fmt.Println(err) // ReferenceError: Cannot access a variable before initialization at <eval>:1:1(2)
	_, err = vm.RunString(`let result = "then let me define it?";`)
	fmt.Println(err) // SyntaxError: Identifier 'result' has already been declared at <eval>:1:1(0)
}
```

This does not happen when using `var` instead of `let` (in this case, the reassignment works correctly) and naturally this is not possible with `const` (because you can't reassign constant variables, as goja helpfully reminds you when you try the reassignment in this example).

As far as I can tell, this is not expected JS behavior, at least judging by what browsers do:

![image](https://github.com/dop251/goja/assets/984584/8f7ff45d-ed3b-40b7-aca2-18ff8e5581ed)

In this case, I could reassign `result` after first assigning it to a rval that threw. I expected goja to do the same.

**Comment by gbl08ma** [comment]
I've traced the unexpected "Cannot access a variable before initialization" error to the `func (r *stashRefLex) set(v Value)` function in vm.go - but I don't think this is the root cause of the problem. The check happening in that function is needed to correctly implement the [temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz). I think the problem is with how the `let` statement is implemented, where, in the case of an exception, it leaves the variable in a state where it's as if the let statement hadn't occurred yet (i.e. the variable is left in the TDZ forever). My guess is that we need an additional panic recovery somewhere in the code that executes the let statement, to wrap around the exception thrown by the rval, so that, in my example, `let result = callback()` ends up behaving like `let result; result = callback()` (which would leave `result` as `undefined`). Judging by the behavior observed in browsers, I think that's how it's meant to work:
![image](https://github.com/dop251/goja/assets/984584/f86a3583-f31f-48a8-bdba-3c0bde8209fe)

**Comment by dop251** [comment]
Yes, ypu're right. Normally, if the initialiser throws an exception the block scope is exited and the lexical binding disappears along with it. However, when you are in the global scope, the bindling remains in TDZ so you can neither access, nor re-define it.

I believe this conforms to ECMAScript standard and the same happens in nodejs:

```console
$ node
Welcome to Node.js v20.5.1.
Type ".help" for more information.
> let a = (() => {throw new Error()})();
Uncaught Error
    at REPL2:1:23
> a
Uncaught ReferenceError: a is not defined
> let a = 1;
Uncaught SyntaxError: Identifier 'a' has already been declared
> a = 1
Uncaught ReferenceError: Cannot access 'a' before initialization
> 
```
My advice -- avoid lexical declarations in the global scope, I don't think they have thought it through.... I'd be happy to address this if you point me to the right place in the specs which describes exactly what should happen in this case.

**Comment by gbl08ma** [comment]
I agree, I don't think this edge case is standardized. It's comforting to know nodejs does the same thing 😂 and it probably makes sense for goja to follow the nodejs behavior rather than the browser behavior. I only ran into this because my project makes a REPL available to developers and running into exceptions while trying things out in such an environment is relatively common; I don't think there is a way this can happen in normal program execution. I should probably let go of the habit of always using `let` and start using var in the global scope.

If I'm going to dive into the internals of goja, I would rather do it to implement top-level await and not to handle this edge case 😄

**Comment by dop251** [comment]
Actually I was wrong, they _did_ think it through, but still decided to leave it like this :) https://esdiscuss.org/topic/toplevel-let-binding-can-be-left-permanently-uninitialized-after-an-error#content-12
