### ISSUE TITLE
JSON.stringify hangs indefinitely if trying to stringify a Go type with a circular reference

### ISSUE THREAD

**Issue by TristanSpeakEasy** [dop251/goja#543]
Ie a type like

```go
type CircularType struct {
	Self *CircularType
}
```

Will just cause JSON.stringify to hang indefinitely.

Would be great if this had some sort of detection for this and just bailed out at some point with an error

**Comment by TristanSpeakEasy** [comment]
Example of what happens in node 
![image](https://github.com/dop251/goja/assets/108070248/e2f438d4-b089-4c43-b7b3-485d60aefe24)

**Comment by TristanSpeakEasy** [comment]
thanks @dop251 very much appreciated

**Comment by dop251** [comment]
No worries, thanks for reporting!
