### ISSUE TITLE
How to identify js jump information through semantics

### ISSUE THREAD

**Issue by mnd5756242** [dop251/goja#545]
I wrote a crawler. In order to crawl to the jumps in js, I used regular expressions to extract the jump information in js. However, this matching method cannot obtain complex js jumps, so I want to improve it through js semantic recognition. Accuracy

Below is my regex：
for _, exp := range []string{`location\s*?=\s*?["'](.*?)["']`,
		`window.location\s*?=\s*?["'](.*?)["']`,
		`window.location.href\s*?=\s*?["'](.*?)["']`,
		`self\.location.*?=\s*?["'](.*?)["\']`,
		`top\.location.*?=\s*?["'](.*?)["\']`,
		`location\.replace\(["'](.*)["']\)`,
		`location\.assign\(["'](.*)["']\)`,
		`window.open\(["'](.*?)["']`} {
		jsRedirRe = append(jsRedirRe, regexp.MustCompile(exp))
	}

For the following piece of JS code, it is obvious that the jump cannot be extracted through regular expressions：

<script>window.onload=function(){ url ='/webui';window.location.href=url;}</script>

**Comment by dop251** [comment]
I'm not sure what you mean by "identify".

**Comment by chushuai** [comment]
This is a good requirement. I have also encountered this problem. Can you help me implement it? @dop251

**Comment by dop251** [comment]
It would be a very non-trivial task, but I don't believe it would require any changes in goja, as it is an implementation of ECMAScript standard, nothing more than that.
