### ISSUE TITLE
repl?

### ISSUE THREAD

**Issue by glycerine** [dop251/goja#55]
Hi @dop251 !  This is such a cool project.

I was just curious if there is already a REPL (interpretive prompt), or an easy way to make one?

Thank you.

**Comment by dop251** [comment]
Hi @glycerine. As far as I'm aware there isn't and I don't have any plans to write one, sorry.

**Comment by glycerine** [comment]
@dop251 no worries, thanks for the quick reply!  If I wrote one, would it be something goja would accept a pull request for?

**Comment by dop251** [comment]
Not as part of the core, maybe goja_nodejs or as a separate project..
