### ISSUE TITLE
[Bug] Big number representation wrong

### ISSUE THREAD

**Issue by hyunsooda** [dop251/goja#551]
This code is intended to output a typed number as is, but it currently produces an incorrect result.

```
v, err := vm.RunString("9323372036854754404")
if err != nil {
    panic(err)
}
fmt.Println(reflect.TypeOf(v.Export().(float64))) // == 9323372036854755000
```

**Comment by dop251** [comment]
This is expected, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER for more details.

Note, BigInt is not yet supported.

**Comment by hyunsooda** [comment]
Thanks, sorry for the noise.
