### ISSUE TITLE
proposal: pluggable panic handler

### ISSUE THREAD

**Issue by emicklei** [dop251/goja#554]
In several cases in the `Runtime`, e.g. detecting a ReferenceError, the Go `panic` function is called by the `Runtime`. 

In my use case , I would like to have more control on how to handle these situations ; not using the  Go `recover()` on the whole execution.

I propose to introduce a `SetPanicHandler(func(error))` function on `Runtime` that allows for a custom implementation of handling the panic cases.  To keep backward compatibility, the `Runtime` can be created with the default behaviour which just panics.

I am happy to provide a PR if the idea is accepted.

thx for creating goja

**Comment by dop251** [comment]
Hi. There should be no need for this. In all cases I can think of there is a way to catch the panic and turn it into a returned `error` value. Can you provide some code to illustrate?

**Comment by emicklei** [comment]
hi, thank you for the response.

Trying to put together an example, I realised that indeed, also in my case, it is possible to catch the panic and proceed with an error. 

```
function join(data){
    console.log(data);
    foo();
    console.log("after foo");
}
_on("playerJoined",join);
console.log("before foo")
foo();
console.log("after foo");
```

Running this will return a `ReferenceError` from the program because of the bottom `foo` call and will panic in the call to `join` because that function also calls the undefined `foo`.  
I was able to put a `recover` in  the event handling code that calls back into Javascript.

thx

**Comment by dop251** [comment]
You don't even need to do the recover. If you're using a typed function (which I suspect you do), just add `error` as the second return value and any exception thrown in the javascript code will be returned as `*Exception`.

**Comment by dop251** [comment]
See https://github.com/dop251/goja/issues/528 for more details.

**Comment by emicklei** [comment]
thank you for these suggestions @dop251 , will check them
