### ISSUE TITLE
Is the Web Platform in scope?

### ISSUE THREAD

**Issue by brodo** [dop251/goja#559]
I've implemented half of a PR to add `TextEncoder` to Goja for a k6 extension. Would such a PR be welcome, or are the web platform APIs out of scope?

**Comment by dop251** [comment]
I'd like to keep this project limited to the [ECMAScript specification](https://tc39.es/ecma262/). Additional modules could be added to [goja_nodejs](https://github.com/dop251/goja_nodejs) or even released as separate projects.
