### ISSUE TITLE
Support for setting a Promise as handled to true

### ISSUE THREAD

**Issue by joanlopez** [dop251/goja#565]
On certain scenarios, like for instance when adding support for Streams API (more specifically to [`ReadableStreamReaderGenericInitialize`](https://streams.spec.whatwg.org/#readable-stream-reader-generic-initialize)), a mechanism to mark a Promise as handled is required, as per spec's requirements:

_(from the link above)_
```
...
    // 2. Set reader.[[closedPromise]] to a promise rejected with stream.[[storedError]].
    // 3. Set reader.[[closedPromise]].[[PromiseIsHandled]] to true.
```

That method I guess would not only set `Promise.handled` to `true`, but also do any other operation related with the handling of the Promise.

In Deno, for instance, there's a [`setPromiseIsHandledToTrue`](https://github.com/denoland/deno/blob/main/ext/web/06_streams.js#L173-L176) function, used specifically for that.

**Alternatively,** would be nice to have a more generic set of handlers for Promises management, which would also be handful for this specific use case.

Thanks!

**Comment by dop251** [comment]
Setting [[PromiseIsHandled]] to true is a byproduct of setting a handler on the promise using `then`. If you look at the code for [setPromiseIsHandledToTrue](https://github.com/denoland/deno/blob/main/ext/web/06_streams.js#L173-L176) you'll see that it's doing exactly that.

**Comment by joanlopez** [comment]
> Setting [[PromiseIsHandled]] to true is a byproduct of setting a handler on the promise using `then`. If you look at the code for [setPromiseIsHandledToTrue](https://github.com/denoland/deno/blob/main/ext/web/06_streams.js#L173-L176) you'll see that it's doing exactly that.

Doesn't it look like it's handling the "then" with an undefined fulfillment handler? 
Like, marking it as handled (internally), without actually doing anything 🤔

**Comment by dop251** [comment]
Have you actually tried it?
