### ISSUE TITLE
Export JS array to Go slice

### ISSUE THREAD

**Issue by jimafisk** [dop251/goja#573]
Goja is an awesome project, thank you for the tremendous work you've put into it!

I was hoping get an array of values from a JS script and iterate over them in Go, but I'm not sure exactly how to do that. I was trying (unsuccessfully) something along these lines:
```go
vm := goja.New()       
r, _ := vm.RunString(`["cat", "dog", "whale"]`)
v, _ := r.Export().([]string)
for i, a := range v {
  fmt.Println("index:", i)
  fmt.Println("animal:", a)
}
```

In following along on a [similar issue](https://github.com/dop251/goja/issues/368), it seems like [exportToSlice](https://github.com/dop251/goja/commit/f3aaa50fcbc264858f4ebe1b2866f8b7e3873b25#diff-e228ec624c9fede7001fef8fd0fb890b56b265fecd11c9aaeeceea77fe838fabR510) might be exactly what I'm looking for. I don't see this in [the documentation](https://pkg.go.dev/github.com/dop251/goja#section-documentation), is this currently available or still a work in progress?  

I also tried using `.ForOf` which has a great example in the docs (https://pkg.go.dev/github.com/dop251/goja#Runtime.ForOf), but I still only seem to be able to get it to iterate character by character over the array as a string.

I would love to see an example of how to export a JS array to a Go slice if it's something you could point me to or demonstrate without too much difficulty. Thank you!

**Comment by dop251** [comment]
You should use [ExportTo](https://pkg.go.dev/github.com/dop251/goja#hdr-Array_types)

**Comment by jimafisk** [comment]
Thank you @dop251, that was exactly what I needed! This example was super helpful for me: https://pkg.go.dev/github.com/dop251/goja#example-Runtime.ExportTo-ArrayLikeToSlice

Updating my initial example:
```go
vm := goja.New()

v, err := vm.RunString(`["cat", "dog", "whale"]`)
if err != nil {
   log.Fatal(err)
}

var r []string

err = vm.ExportTo(v, &r)
if err != nil {
   log.Fatal(err)
}

for i, a := range r {
   fmt.Println("index: ", i)
   fmt.Println("animal: ", a)
}
```
