### ISSUE TITLE
how to register custom object into goja like before?

### ISSUE THREAD

**Issue by yundiz** [dop251/goja#583]
hi,
  i want to register    custom object like before,
1) define object class type in runtime,and init register it.
2) write builtin_custom_object,define property and function 
how to upgrade my code to new version?
<img width="1250" alt="image" src="https://github.com/dop251/goja/assets/81137426/e038dd25-7272-4bf4-ad0a-45b599c10be6">

**Comment by dop251** [comment]
What you're describing sounds like it should be possible to do with the public API. If not, please provide more details.

Using the internal API is not recommended as there is no compatibility guarantee whatsoever, your code may break (including silently) with each new release.

**Comment by yundiz** [comment]
the following code,show why i need internal api , i write ContextObject which include parameter map, 
i need the script write just like this

context["name"]="a";
context["qty"]=1;

in the backend goja side, i will write the added parameters into my context.parameter map object, if using public api, how to do it .

the following is my internal api code 

<img width="1323" alt="image" src="https://github.com/dop251/goja/assets/81137426/4e9d8636-d759-4274-8253-107b349b885f">
