### ISSUE TITLE
Circular References Memory Leak

### ISSUE THREAD

**Issue by Hyhyx** [dop251/goja#587]
![5dbe7c14-f386-498f-9788-92427f6efa46](https://github.com/dop251/goja/assets/17903322/2ac082dd-c85d-4f85-85ca-ea4f45ea61ac)

There are many anonymous functions in my program, and during batch runs, I found that memory keeps growing. Currently, I have found that the functions have circular references. How do I optimize them?

![359a6ea8-fe4f-46d5-b23b-b1202e455c63](https://github.com/dop251/goja/assets/17903322/5567eed6-e13c-4729-b102-85484a9e5c08)

**Comment by dop251** [comment]
Circular references in Go do not cause memory leaks unless you define a finalizer on any if the involved objects (which goja doesn't do).
