### ISSUE TITLE
BUG: String.split on an empty string may produces unexpected results

### ISSUE THREAD

**Issue by Kr328** [dop251/goja#588]
### Description

In Chrome, String.split with a limit on an empty string returns an array containing an empty string, but goja returns an empty array.

### Reproduce
Goja:
```js
"".split("#", 2) // result == []
```

### Excpeted Result
Chrome:
```js
"".split("#", 2) // result == [""]
```

### Possible Solution
Maybe add a minimum value at https://github.com/dop251/goja/blob/eb1f15ee67d22593a0760c3df624da2ea4e41cb6/builtin_string.go#L830-L832

**Comment by dop251** [comment]
Thanks for reporting!
