### ISSUE TITLE
Object.keys with map[int]any will return <int Value>

### ISSUE THREAD

**Issue by onionwyl** [dop251/goja#590]
When i pass a map[int]any to  js function and use Object.keys() to get keys of it, it will return `["<int Value>"]`
The code is as following.
```go
func main() {
	registry := require.NewRegistry()
	vm := goja.New()
	registry.Enable(vm)
	console.Enable(vm)
	_, e := vm.RunString(`
        function call(data) {
            console.log(JSON.stringify(Object.keys(data)))
            return data;
        }
        `)
	if e != nil {
		log.Fatalln(e)
	}
	ff, ok := goja.AssertFunction(vm.Get("call"))
	if !ok {
		panic("abc")
	}

	resp := map[int]any{1: 123, 2: 456}

	data := vm.ToValue(resp)
	rr, err := ff(goja.Undefined(), data)
	if err != nil {
		panic(err)
	}
	fmt.Println(rr.Export())
}
```
Then as I debug the code, i found that the impl of stringKeys use String() of a reflect.Value, which can't convert int or any other types to a correct string
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/df626886-74df-4c2a-9eb4-b25ee85bcd00">

**Comment by dop251** [comment]
Thanks for reporting!

**Comment by onionwyl** [comment]
Thanks! The fix works
