### ISSUE TITLE
limit resource usage

### ISSUE THREAD

**Issue by aybabtme** [dop251/goja#6]
I feel this might not be possible, but something missing in `otto` is being able to somehow limit how much memory a VM is allowed to use, or CPU (there's a time based interrupt thingy), and so on.

It would be pretty cool if this package allowed strict control over these.

Nice work, love to see more language interpreters!

**Comment by slinkydeveloper** [comment]
I would love to see this feature :heart_eyes:

**Comment by Riku32** [comment]
I would like this added too

**Comment by sohaha** [comment]
It appears that there aren't any viable solutions.

**Comment by dop251** [comment]
Not in scope I'm afraid. Tracking memory usage would be particularly tricky and should be something provided by the Go runtime.
