### ISSUE TITLE
Null() returns _undefined instead of _null

### ISSUE THREAD

**Issue by jakebailey** [dop251/goja#60]
The `Null()` function actually returns `_undefined` instead of the canonical `null` value. https://github.com/dop251/goja/blob/034fb74b51e65bc4a5a9f4d56aa1839699413f67/runtime.go#L1445-L1447

A quick git blame shows that this bug has been present since the initial commit, but it has probably gone unnoticed since nothing appears to call/test `Null()`.

For example:
```go
fmt.Println("IsNull(Null()):          ", goja.IsNull(goja.Null()))
fmt.Println("IsUndefined(Null()):     ", goja.IsUndefined(goja.Null()))
fmt.Println("IsNull(Undefined()):     ", goja.IsNull(goja.Undefined()))
fmt.Println("IsUndefined(Undefined()):", goja.IsUndefined(goja.Undefined()))
```
Outputs:
```
IsNull(Null()):           false
IsUndefined(Null()):      true
IsNull(Undefined()):      false
IsUndefined(Undefined()): true
```

`IsNull(Null())` and `IsUndefined(Undefined())` being true should probably have a tiny test each to prevent goofs like this. :smile:

**Comment by dop251** [comment]
Thanks for reporting this. It was added as part of the public API mostly for completeness...
