### ISSUE TITLE
some modules cause the exception`GoError: Invalid module`

### ISSUE THREAD

**Issue by dogil-minsu** [dop251/goja#607]
hello, everyone.
I recently started use benthos sink with javascript processor.
And it's implemented using this library, goja.
And I figured out that when I run some JS modules like below
```
const request = require('request');
```
I got an error that `GoError: Invalid module`.
Some modules work well like (lru-cache, ua-parser-js, ...), but there are problems with some modules like request/axios/http/fetch...

**Comment by dop251** [comment]
Hi. This library does not implement any modules, nor even the `require` function. I think opening an issue with benthos would be a good starting point.
