### ISSUE TITLE
Nested []any should be addressable

### ISSUE THREAD

**Issue by dop251** [dop251/goja#620]
### Discussed in https://github.com/dop251/goja/discussions/618

<div type='discussions-op-text'>

<sup>Originally posted by **pgundlach** October  8, 2024</sup>
The following code prints `[]`. How can I add the word "Hello" to the slice? The slice is a `[]any` slice. 

I can of course add a "addToSlice" method, but I'expect a `.push()` to work. 

```go
package main

import (
	"fmt"
	"os"

	"github.com/dop251/goja"
)

type document struct {
	Items []any
}

func (d *document) Check() {
	fmt.Println(d.Items)
}

func main() {
	runtime := goja.New()
	runtime.Set("newdoc", func() *document { return &document{} })

	_, err := runtime.RunString(`
var d = newdoc();
d.Items.push("Hello");
d.Check();
`)
	if err != nil {
		fmt.Println(err)
		os.Exit(-1)
	}

}
```
</div>

**Comment by dop251** [comment]
This is actually a bug. The field should be addressable, but it doesn't work for 'simple' slices (i.e. `[]any`). If you change it to `[]string` it will work, so this needs to be fixed.

**Comment by pgundlach** [comment]
Thank you very much, it works nicely in my real-world use case.
