### ISSUE TITLE
Interrupting while resolving a promise from go looks like nothing went wrong

### ISSUE THREAD

**Issue by mstoykov** [dop251/goja#623]
If you have a promise that gets resolved on the event loop, and that resolve leads to an interrupt, this is never reported.

This is due to three specific things within goja/Sobek.

But first some general background: JS is single threaded and at any point only 1 js code is being executed. This also means that if you have a resolution of a promise (among anything else) it will wait until there is nothing and then it will be ran. This is done in goja in different places, but usually after any other running of js code (for a very wide definition of code) goja will check if it needs to run any resolutions.

This all is great, but the three specific things are that:
1. [resolving a promise](https://pkg.go.dev/github.com/dop251/goja#Runtime.NewPromise) does not return an error. In practice it actually specifically will [eat](https://github.com/dop251/goja/blob/21e33551e7539f4e1f98715e0df2b5188aaf4a08/builtin_promise.go#L601) the error for both in resolution and rejection.
2. the resolve of a promise will trigger actually running it resolves if the js stack is empty - which it will be unless you call it within a js function.
3. the interrupt will be cleared when it is returning to an empty stack

So at this point if you interrupt goja and this happens during a resolve from go, that was queued on an event loop, *UNLESS* that resolve was called within some other js code execution:
1. you will not get the interrupt error
2. the interrupt error will be cleared and consequently even running something will not help you.

A fairly small example test to illustrate this.
```go
func TestInterruptWithPromises(t *testing.T) {
	rt := New()
	rt.SetMaxCallStackSize(5)
	// this test panics as otherwise goja will recover and possibly loop
	rt.Set("abort", rt.ToValue(func() {
		// panic("waty")
		rt.Interrupt("abort this")
	}))
	var queue = make(chan func(), 10)
	rt.Set("myPromise", func() Value {
		p, resolve, _ := rt.NewPromise()
		queue <- func() {
			resolve("some value")
		}

		return rt.ToValue(p)
	})

	_, err := rt.RunString(`
		let p = myPromise()
		p.then(() => { abort() });
	`)
	if err == nil {
		t.Fatal("expected error but got no error")
	}
	f := <-queue
	f()
	t.Log(err)
	var soErr *InterruptedError
	if !errors.As(err, &soErr) {
		t.Fatalf("Wrong error type: %T", err)
	}
}
```

I did start with goja_nodejs's eventloop, but it has absolutely no way of reporting errors from the event loop, so that seemed pointless. But it works with it as well.

Now at this point again you either need to do 

```go
rt.Set("actuallyDoTheResolve", resolve)
_, err := rt.RunString(`actuallyDoTheResolve()`)
```

Or some other similar thing in order to have js stack to prevent `resolve` to be the thing running the resolution and consequently eating the interrupt.

#### Doing the above without running js code

I tried `Try` and I tried `AssertFunction`  on a `ToValue(func() {resolve()})`. Both of those skip creating a js stack so both will not stop `resolve` from running the resolution.

### Not clearing interrupt
I tried making the interrupt not getting cleared, but that basically requires that you also run additional code after every resolve/reject. To potentially check if something was interrupted. I also have not tried any example in which there were multiple promise resolution jobs queued which might make this even worse.

### panicking in resolve
Doing a direct `panic` in the `wrapPromiseReaction` + `AssertFunction` on a `ToValue(func() ... resolve())`. This worked best and I can argue I can do it as part of an event loop.  Using `Try` did not work, but I expect that is because I literally just called `panic`, so that might the better way, making it work with `Try` 

### resolve and reject returning errors 

That will mean that any code using it will need to return an error, which might be cleaner 🤷‍♂

But also will require more work and will not be obvious something is broken for older codebases.

But might be the more correct and obvious way to go with.

edit: [PR](https://github.com/grafana/k6/commit/a8c96a18e17d1d218350fc8040c1a387f0829fa7) with one of the solutions hacked on top of k6 as part of a testing what is going on.

**Comment by dop251** [comment]
Hi.

Resolving a `Promise` , as you said, happens on the loop, `Interrupt()` on the other hand, is meant to be called in another goroutine to interrupt the vm. Why do you need to call it during resolving? If you instead panic with a `Value`, that should be returned as the error either from a function call, or from one of the `Run*` methods, depending on how you run the JS code.

**Comment by mstoykov** [comment]
@dop251 I don't think that is relevant. 

The interrupt is captured during the resolve. Calling from within or outside, it still will have the same problem when it is captured and propagated during a resolve.

On the concrete why we use interrupt instead of a panic ... well this mechanism is supposed to stop the execution in k6, and interrupt is the way to stop a runtime, so it seems perfectly fitting. We also already handle interrupts for different reasons, while we do not panics. Goja does as part of its normal execution - yes, but does never go up to k6.

**Comment by dop251** [comment]
`Interrupt` was never meant to be 'captured' or 'propagated'. It solves a specific problem: how to interrupt a currently running VM from the outside. When you're _inside_ you're already controlling the execution flow and have other means to stop it.

**Comment by dop251** [comment]
Looking further into this, the reason why `wrapPromiseReaction` ignores the error is because 'normal' exceptions thrown in a handler are never propagated, instead they cause the promise to be rejected. 

However, this applies to 'normal' exceptions, not to uncatchable ones, such as `StackOverflowError` or `InterruptedError`. This makes it a strong case for making the `resolve` and `reject` of `NewPromise` return an error. I wouldn't mind it, even though it would break existing code. But the refactoring is trivial and thanks to Go modules the change won't be sudden and disruptive.

Another piece of the puzzle would be adding an ability to construct UncatchableErrors from Go code, for instance by adding `Runtime.NewInterruptedError()`. It should then be used instead of calling `Interrupt()`.

**Comment by mstoykov** [comment]
> However, this applies to 'normal' exceptions, not to uncatchable ones, such as StackOverflowError or InterruptedError. This makes it a strong case for making the resolve and reject of NewPromise return an error. I wouldn't mind it, even though it would break existing code. 

This sounds okay. Do you want me to make a PR with that? There doesn't really seem to be any questionable thing there apart from whether to also return errors on "normal" extensions or not.

Given that there is mechanism to catch "normal" exceptions in async code that seems like the thing that should be left.

**Comment by dop251** [comment]
Yes please, raise a PR. The function should just return whatever error is returned from the wrapped function. Normal exceptions are already handled and turned into Promise rejections.
