### ISSUE TITLE
A question about numerical values

### ISSUE THREAD

**Issue by iveryo** [dop251/goja#632]
Access the MYSQL database, and the return value is processed by goja.
Since the ID definition in the database is of bigint(20) type, it was found that the value was modified when returned.

Later tested in function:
return 89758002686993883;
The value I got from golang is 89758002686993890

Thank you so much for the effort you put into this project!

**Comment by shiroyk** [comment]
`89758002686993883 ` exceeds JavaScript's safe integer range (`2^53 - 1`), leading to precision loss. To handle large integers beyond the safe range, you can use the `BigInt` type.
```go
func main() {
	runtime := goja.New()
	value, ok := new(big.Int).SetString("89758002686993883", 0)
	if !ok {
		return
	}
	runtime.Set("value", value)
	result, _ := runtime.RunString(`value - BigInt('89758002686993883');`)
	fmt.Println(result.Export().(*big.Int))
}
```

**Comment by iveryo** [comment]
@shiroyk Great, there is already support for BigInt.
I found that I need to update goja.

Thank you so much!
