### ISSUE TITLE
Interrupt based on work done/concept of "ticks"

### ISSUE THREAD

**Issue by archisgore** [dop251/goja#64]
I have a rather strange use-case. I run a few goja instances in parallel, along with some other goroutines.

This can cause CPU contention. For me, the timeouts are to ensure injected code isn't running an infinite-loop, rather than having a fixed wall-clock bound.

Under high load though, a goja VM might not get around to doing much, thus running out the Wall Clock allotted time.

I'm happy to do the work, but I wanted to field the idea of "ticks". Each time Goja does some work, a tick is updated. The tick doesn't have to be precise, or meaningful, so long as it is monotonic and increments itself periodically as things get executed.

It would do two things:
1. I would be able to measure the inner-JS for ticks and compare two implementations which can report into performance metrics. This would help identify which scripts can be improved and when they are improved, that they really did improve.

2. I would be able to set an interrupt after "ticks", so under contention or maybe because the code is blocked on some input, it wouldn't expire due to the wall clock. Yet, I can guard against infinite loops.

**Comment by dop251** [comment]
I think it could be useful in some cases, so I will consider merging this as long as it does not break existing API, implemented as an option (disabled by default), and when disabled does not have any performance impact.

**Comment by zupa-hu** [comment]
@archisgore - curious, did you implement this?

**Comment by archisgore** [comment]
Sorry no, never did. We moved away from this and in the future, likely to use a WASM runtime to host 3rd party code. Closing the issue.

**Comment by zupa-hu** [comment]
@archisgore yes makes sense. Thanks!
