### ISSUE TITLE
Is goja thread safe?

### ISSUE THREAD

**Issue by stephen-kruger** [dop251/goja#70]
One of the reasons we need to move off Otto is it's inherent inability to support concurrent script executions : 
https://github.com/robertkrimen/otto/issues/246

Did goja inherit the same limitations from otto, or it's possible to write a scaleable general purpose JS execution platform?

many thanks

**Comment by zengming00** [comment]
I have an interesting project,  Based on the goja
https://github.com/zengming00/go-server-js

**Comment by stephen-kruger** [comment]
Interesting (I think - I couldn't understand any of the docs), but for our use case we cannot afford the latency-expensive decoupled web service call to a dedicated server (if we could we'd just use AWS Lambda instead).

**Comment by dop251** [comment]
Goja is single threaded as most javascript engines. Javascript traditionally uses a different concurrency model based on event loop. There is a nodejs-style implementation for goja (https://github.com/dop251/goja_nodejs/tree/master/eventloop)

**Comment by stephen-kruger** [comment]
Thanks for the response,
I'm fine with a single thread (or goroutine I would hope) per script execution, but what I'm asking is can a single go program execute more than 1 script in parallel, without cross-effecting each other, or goja effectively gates all scripts to be run sequentially?

**Comment by dop251** [comment]
You can do that as long as the scripts are running in different Runtimes. Also you cannot pass an Object from one runtime to another. You could however expose a specially written Go structure and use it for communication.
