### ISSUE TITLE
Help with structs values in and out

### ISSUE THREAD

**Issue by gus2286** [dop251/goja#78]
Great job.

I'm new on this, and I try to understan how I can set and get structs inside and outside of the VM, for example:

    type person struct {
        name string
        age  int
    }
    var msgIN person
    var msgOUT person

    msgIN.name = "Phil"
    msgIN.age = 30

    vm := goja.New()
    vm.Set("msgIN", msgIN)
    vm.Set("msgOUT", msgOUT)
    vm.RunString(`
    msgOUT=msgIN; 
    msgOUT.age = 22;
        `)
    fmt.Println(msgIN)
    fmt.Println(msgOUT)

    outputValue := vm.Get("msgOUT")
	outputInterface := outputValue.Export()
	fmt.Println(outputInterface)

And this is the output:

    {Phil 30}
    { 0}
    {Phil 30}

In the example, it is like the assign msgOUT=msgIN is doing it fine but I can't change the value for the .age, I try to use msgOUT["age"] but it is the same.

If anyone can help me to make this basic example work I really appreciatte it.

Cheers
Gus

**Comment by gus2286** [comment]
Thanks Dmitry, but now I have a panic error:

    type person struct {
        Name string
        Age  int
    }
    var msgIN person
    var msgOUT person

    msgIN.Name = "Phil"
    msgIN.Age = 30

    vm := goja.New()
    vm.Set("msgIN", msgIN)
    vm.Set("msgOUT", msgOUT)
    vm.RunString(`
    msgOUT=msgIN; 
    msgOUT.Age = 22;
        `)
    fmt.Println(msgIN)
    fmt.Println(msgOUT)

    outputValue := vm.Get("msgOUT")
    outputInterface := outputValue.Export()
    fmt.Println(outputInterface)

And the error is:

```
panic: reflect: reflect.Value.Set using unaddressable value [recovered]
        panic: Panic at 6: reflect: reflect.Value.Set using unaddressable value [recovered]
        panic: Panic at 6: reflect: reflect.Value.Set using unaddressable value

goroutine 1 [running]:
github.com/dop251/goja.(*Runtime).RunProgram.func1(0xc000071d38)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/runtime.go:880 +0xa2
panic(0x8d3840, 0xc000141910)
        C:/Go/src/runtime/panic.go:513 +0x1c7
github.com/dop251/goja.(*vm).try.func1(0xc00005cc30, 0x0, 0xc000071c38, 0x0, 0x0, 0x0, 0xc000071c90)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:364 +0x460
panic(0x8b1ec0, 0xc0001418f0)
        C:/Go/src/runtime/panic.go:513 +0x1c7
reflect.flag.mustBeAssignable(0x82)
        C:/Go/src/reflect/value.go:234 +0x15e
reflect.Value.Set(0x8b1440, 0xc000154690, 0x82, 0x8b1440, 0xc000058908, 0x82)
        C:/Go/src/reflect/value.go:1397 +0x36
github.com/dop251/goja.(*objectGoReflect)._put(0xc0003381b0, 0xc00008881f, 0x3, 0x9f8d00, 0xc0001442c0, 0xc000071b00, 0x841d0d)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/object_goreflect.go:184 +0x1de
github.com/dop251/goja.(*objectGoReflect).putStr(0xc0003381b0, 0xc00008881f, 0x3, 0x9f8d00, 0xc0001442c0, 0x0)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/object_goreflect.go:171 +0x76
github.com/dop251/goja.setProp.exec(0xc00008881f, 0x3, 0xc00005cc30)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:1047 +0xe5
github.com/dop251/goja.(*vm).run(0xc00005cc30)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:288 +0x64
github.com/dop251/goja.(*vm).run-fm()
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:375 +0x31
github.com/dop251/goja.(*vm).try(0xc00005cc30, 0xc000071c98, 0x0)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:370 +0x113
github.com/dop251/goja.(*vm).runTry(0xc00005cc30, 0x98a7b8)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/vm.go:375 +0x55
github.com/dop251/goja.(*Runtime).RunProgram(0xc000048600, 0xc0000deae0, 0x0, 0x0, 0x0, 0x0)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/runtime.go:891 +0x1be
github.com/dop251/goja.(*Runtime).RunScript(0xc000048600, 0x0, 0x0, 0x97b9e4, 0x31, 0x6, 0x9f8800, 0xc0001547a0, 0xc000154700)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/runtime.go:870 +0xa2
github.com/dop251/goja.(*Runtime).RunString(0xc000048600, 0x97b9e4, 0x31, 0x903480, 0xc000154780, 0xc00006dda0, 0x9f1920)
        D:/Users/Gustavo/Documents/Proyectos Go/src/github.com/dop251/goja/runtime.go:859 +0x4e
```

You have any idea on how to do what I want? I'm open to do it in any way where I can access the struct from the javascript.
Thank you very much

**Comment by dop251** [comment]
And that is because you passing your structs as values, not as pointers. You need to change it to
```go
	vm.Set("msgIN", &msgIN)
	vm.Set("msgOUT", &msgOUT)
```
However, bear in mind that when you do msgOUT=msgIN in your javascript code that will make msgOUT (js variable) point to msgIN (your go structure), so in go msgIN.Age will be 22 and msgOUT.Age will be 0.

If you want to achieve what I think you are trying to achieve you need to move ```msgOUT = msgIN``` to the go code.

The panic is a separate issue, I should probably just treat it as a non-writable property, I'll take a look at that.

**Comment by gus2286** [comment]
Yes, works, thank you very much

Cheers
Gus
