### ISSUE TITLE
Is it possible to create an anonymous function?

### ISSUE THREAD

**Issue by deinspanjer** [dop251/goja#80]
I'd like to do something like this:
```
funcVal, err := vm.RunScript("myFunc", `
  function(name) {
    alert("Hello "+name);
  };
`)

funcCallable, _ := goja.AssertFunction(funcVal)
// ...
retVal, err := funcCallable(nil, vm.ToValue("Person"))
println(retVal.ToString())
```

But when I try, I get an error that the `(` in `function(name)` is illegal.  I also tried `vm.RunString(...)` with the same result.  Grasping straws, I also tried prepending a `return` to the function() statement, but that gives `Illegal return statement` which is what I'd expect since it isn't in the context of a method.

**Comment by Macil** [comment]
Try wrapping the function in parentheses. (I'm not familiar with goja, but that will be the answer if vm.RunScript is consistent with javascript's eval.)

**Comment by dop251** [comment]
Yes. ```function(x) {}``` is a function declaration which does not return any value, whereas ```(function(x) {})``` is a function expression which does return the function.

**Comment by deinspanjer** [comment]
D'oh.  JS fail on my part. that works just fine.  I didn't think to wrap it in parenthesis because I was thinking about the line `var foo = function(x) {}` and just stripping off the `var foo =` part.
