### ISSUE TITLE
Create lazy objects/arrays and watch for native props changes

### ISSUE THREAD

**Issue by nitrotm** [dop251/goja#83]
It would be nice to have more control how a go struct is exposed to javascript. In particular, I would be interested in:
* watching for property creation/modification/removal
* exposing a potentially big data structure in a lazy fashion (creating it on the fly when it's accessed from javascript)

JavaScript example (exposing myObj as a global object from go):
```
// I would like to re-implement put(), putStr(), for example to keep track of changes during exec
myObj.someProp = 5;

// same as above
myObj.thisIsNew = 42;

// I would like to re-implement delete(), deleteStr()
delete myObj.someOtherProp;

// Fetching corresponding data on the fly, and wrapping each generated
// value as a 'lazy value' in case of objects or arrays
// I would like to implement get(), getStr(), getProp(), getPropStr(), hasProperty(), etc 
username = myObj.row[8555].subItem[9999].user.friends[friendId].name;
```

Would it be possible to expose some type akin to baseObject/objectImpl to external packages? It could be a sub-type only for external object maybe?

**Comment by dop251** [comment]
I think you need ES6 Proxy (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy).

@noctarius was doing some work on it (https://github.com/relationsone/goja/tree/es6-proxy) but I haven't heard from him for a while. It would be nice to have this in goja as this is quite useful and can't be polyfilled.

**Comment by vanackere** [comment]
Hi, commenting here to say that I have the same need. 
Since the ES6 Proxy work looks both complex and stalled... how about reopening/merging https://github.com/dop251/goja/pull/62 ? In my opinion It looks straightforward to use and would give all the necessary low-level control on the go side.

**Comment by dop251** [comment]
Proxy functionality has now been added to the `es6` branch. I see no reason for having two mechanisms doing the same thing.
