### ISSUE TITLE
Support for custom "Marshalling" like json's MarshalJSON 

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#84]
In [k6](https://github.com/loadimpact/k6) we currently use [FieldNameMapper](https://godoc.org/github.com/dop251/goja#FieldNameMapper) with some [custom code](https://github.com/loadimpact/k6/blob/master/js/common/bridge.go#L56) to read method names from a tag `js`. This does some of the work and we have thrown more workarounds on top for other corner cases. But ultimately we came to a point where we have a struct with an anonymous struct in it and we don't want the whole internal anonymous struct to be accessible with a name but only it fields. Which is currently not possible. 

```
type OuterType struct {
InnerType
SomeField string
}
type InnerType struct {
AnotherField string
}
```
If we "Marshall" OuterType to goja's VM we currently get three fields `["inner_type", "some_field", "another_field"]` but we only want `["some_field", "another_field"]`. 

I couldn't find this being discussed previously and given that I probably miss some crucial info I would like to know if this has been thought about and whether a PR for this will be welcome. Also any pointers to pitfalls /ideas are also welcome :)

**Comment by dop251** [comment]
Have you tried setting the `js:"-"` tag on the InnerType? I can't test right now but according to your code this should hide it.

**Comment by MStoykov** [comment]
Yes but it also hides all it fields which is what we don't want :(

**Comment by dop251** [comment]
Ok, I have finally got time to have a look and I see what you mean. Going to push a fix shortly after which it will no longer remove the InnerType fields, only the InnerType itself.
