### ISSUE TITLE
Is this safe for sandbox usage?

### ISSUE THREAD

**Issue by vincent-163** [dop251/goja#85]
I'm looking for a scripting engine that executes untrusted code and wondering if I can expect goja to execute untrusted code safely.

It would be nice to provide at least some documentation regarding the following issues so I can tell how safe it would be:
* Resistance against resource consumption (memory usage, cpu usage, etc.)
* The existence of any builtin modules/functions that allows the script to interact with anything outside the program.
* Whether malformed scripts could crash the compiler/runtime and tear down the whole program.
* Best practices for executing untrusted code, like how to perform sanity checks properly.

After all, thanks for the nice work!

**Comment by zupa-hu** [comment]
I'm also interested in this, so let me chip in.

## My understanding of resource usage limits

- you can NOT limit memory consumption
- you CAN limit the execution time
- while you can't limit cpu utilization, but JS programs will be executed by a single goroutine, thus cpu usage is by default limited to a single cpu

## Interaction with the outside world

I went through the code as of 1b2d25ba9a8d6531a82840e337600f36795743cf and found 2 issues #94 and #95.

After patching #94 and #95, I would say it is safe to run untrusted code, just make sure to limit execution time. (And of course do not extend it with unsafe functionality..)
