### ISSUE TITLE
Using UTF16 characters messes up indexOf function

### ISSUE THREAD

**Issue by hirshbergshachar** [dop251/goja#86]
When we have a string with UTF16 characters, indexOf returns -1 when the searched substring is at the very end of the string.

Code to reproduce:
```
package main

import (
	"github.com/dop251/goja"
)

func main() {
	vm := goja.New()
	// here we have a space after "END", works properly
	v, err := vm.RunString("'case 字 END '.indexOf('END');")
	if err != nil {
		panic(err)
	}

	if num := v.String(); num != "7" {
		panic("First check, index should be 7 but it is: " + num)
	}
	// here we don't have a space after "END", doesn't find the string
	v, err = vm.RunString("'case 字 END'.indexOf('END');")
	if err != nil {
		panic(err)
	}

	if num := v.String(); num != "7" {
		panic("Second check, index should be 7 but it is: " + num)
	}
}
```
Output: `panic: Second check, index should be 7 but it is: -1` 

Actual behavior:
Returning -1

Expected behavior:
Return right location (7)

Might be related to https://github.com/dop251/goja/issues/59 ?

**Comment by dop251** [comment]
Hi @hirshbergshachar,

Are you sure you're using the latest version, it's not vendor locked or something? ```'case 字 END'.indexOf('END')``` returns 7 for me.

**Comment by hirshbergshachar** [comment]
@dop251 you are right checked with the latest version and it doesn't occur there. Will update, thank you for your time.
