### ISSUE TITLE
Passing/registering function from javascript to go

### ISSUE THREAD

**Issue by xor-gate** [dop251/goja#9]
I digged through the docs, tests and implementation but could not figure out how to "register" a function from javascript to go. This to create a callback-style application.

Something like this:

```js
function myfunc() {
  mygofunc();
}

// Register function with id 1234 for go
registerfunc(1234, myfunc);
``` 

I am aware of the Callable type but I have no idea how this should be used.

**Comment by xor-gate** [comment]
I have figure it out, sort of. It seems goja passes `myfunc` argument as a string to Golang. So then I am able to run `RunString` on this.

**Comment by dop251** [comment]
Passing functions hasn't been really implemented yet. I'm working on it now, hopefully it will be done within the next few days.

**Comment by xor-gate** [comment]
That sounds awesome, I really like your implementation and maybe I'm going to use it in a project to extent it with a scripting engine. Currently I'm digging through the code and it seems there is a global state where all the registered objects are stored. It would be nice to have a public API where the application can register custom Object/ObjectPrototypes.

**Comment by dop251** [comment]
This is what Runtime.Set() for... As for your original question, in the meantime you could do something like this:

```go
func TestRuntime_ExportToFunc1(t *testing.T) {
	const SCRIPT = `
	function f(param) {
		return +param + 2;
	}

	r(f);
	`

	vm := New()

	var fn Callable

	r := func(call FunctionCall) Value {
		if f, ok := AssertFunction(call.Argument(0)); ok {
			fn = f
		} else {
			panic(vm.NewTypeError("Not a function"))
		}
		return nil
	}

	vm.Set("r", r)
	_, err := vm.RunString(SCRIPT)
	if err != nil {
		t.Fatal(err)
	}

	if res, err := fn(nil, vm.ToValue("40")); err != nil {
		t.Fatal(err)
	} else {
		if !res.StrictEquals(vm.ToValue(42)) {
			t.Fatalf("Unexpected value: %v", res)
		}
	}
}
```

This of course means all your functions are exported as Callable and you need to convert all arguments into Value's and export result which is probably not what you want...

**Comment by xor-gate** [comment]
That is a lot of typing but now I understand.

**Comment by dop251** [comment]
I've added exporting into go func, let me know if it helps

**Comment by xor-gate** [comment]
Your addition and tests look good! I will close this now as it has been added. When there are any problems I will open a new issue (but probably won't). 

Thank you!
