### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by zupa-hu** [dop251/goja#90]
Hi Dmitry,

Thanks for your work on this project, it is awesome!
I think the error reporting could be improved, though I'm not sure if this is defined in the spec.

For a call to a function `foo()`, position `B` appears in the stack trace instead of `A`:
```
foo()
^  ^
A  B
```

Test case:
```
loooooooooooooooooooong = function() { undef() }
loooooooooooooooooooong()
```

Expected error:
```
ReferenceError: undef is not defined
    at example.js:1:40
    at example.js:2:1
```

Actual error:
```
ReferenceError: undef is not defined
    at example.js:1:45
    at example.js:2:24
```

I'd be happy to take a look if you were willing to merge a PR with that change.

Thanks,
Tibor

**Comment by dop251** [comment]
Hi @zupa-hu 

Stacktraces themselves are not part of ECMAScript 5.1, let alone reported positions... However, I would be happy to consider a PR that brings them into line with current best practices.

**Comment by zupa-hu** [comment]
Ok, thanks!
