### ISSUE TITLE
Out of memory crash

### ISSUE THREAD

**Issue by zupa-hu** [dop251/goja#94]
There is an `os.Open()` call in the sourcemap parsing logic [here](https://github.com/dop251/goja/blob/1b2d25ba9a8d6531a82840e337600f36795743cf/parser/statement.go#L576).

Referencing a large file that doesn't fit in memory, possibly an infinitely large one like `/dev/urandom` will crash the process with an out of memory error.

Code to reproduce:

```
goja.New().RunString("\n//# sourceMappingURL=/dev/urandom")
```

I'd like to propose using dependency injection for the sourcemap loading logic via:

```
type SourceMapLoader func(url string) ([]byte, error)

func (r *Runtime) SetSourcemapLoader(SourceMapLoader)
```

Turning on access to the local filesystem by default is risky, so the default setting should be inline only (data:application/json). The current implementation could be provided by the package as `func SourceMapLoaderFromLocalFilesystem`.

I'm happy to vonunteer submitting a PR if it is welcome.

**Comment by dop251** [comment]
goja is not meant for running completely untrusted code. There are many ways you can exhaust memory, for example:
```go
for(var x="X",a=[];;a.push(x+=x));
```

Besides, implementing what you've suggested could break people's code, so I'd be inclined to say no.

**Comment by zupa-hu** [comment]
I have tested your example, and having a limited execution time (say 1sec) solves the issue - while I have to admit it is not an ideal solution..

Can you think of any other issue?

**Comment by zupa-hu** [comment]
Alternatively, what if the current implementation remains default but one can disable it?

**Comment by dop251** [comment]
That would be ok.
