### ISSUE TITLE
Forgotten log.Printf()

### ISSUE THREAD

**Issue by zupa-hu** [dop251/goja#95]
The [following line](https://github.com/dop251/goja/blob/master/vm.go#L361) feels like a debug entry left in by accident; could we disable it to avoid cluttering up stderr?

```
vm.prg.dumpCode(log.Printf)
```

Because the `log` package saves a reference to os.Stderr at init time, it is impossible to override it. Because of that, I can not provide a simple testcase that catches the dump. Instead, run the following code and observe the output on the console.

# Example code

```
func TestLog(t *testing.T) {
	// Catch expected panic
	defer func() {
		_ = recover()
	}()

	r := New()
	r.Set("fn", func(v Value) {
		panic(1)
	})

	_, err := r.RunString(`
		try {
			fn()
		} catch (e) {
			// ignore
		}
	`)
	if err != nil { t.Fatal(err) }
}
```

Then run `go test -run TestLog`.

# Expected output:
```
PASS
ok  	github.com/dop251/goja	0.004s
```

# Actual output:
```
2019/06/10 19:28:30 values: []
2019/06/10 19:28:30  0: goja.try({8 0 true})
2019/06/10 19:28:30  1: goja._loadUndef({})
2019/06/10 19:28:30  2: goja.getVar1Callee(fn)
2019/06/10 19:28:30  3: goja.call(0)
2019/06/10 19:28:30  4: goja._pop({})
2019/06/10 19:28:30  5: goja._halt({})
2019/06/10 19:28:30  6: goja.jump(4)
2019/06/10 19:28:30  7: <nil>(<nil>)
2019/06/10 19:28:30  8: goja.enterCatch(e)
2019/06/10 19:28:30  9: goja._halt({})
2019/06/10 19:28:30  10: goja._loadUndef({})
2019/06/10 19:28:30  11: goja._halt({})
PASS
ok  	github.com/dop251/goja	0.004s
```

Can this be commented out or removed?

**Comment by dop251** [comment]
Well, it's been helpful in debugging bugs in the compiler. I appreciate it's probably shouldn't be there, just need to find a better way of doing it.
