### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by zupa-hu** [dop251/goja#96]
Running `test ./...` from the project root (after removing `./goja/main.go`), I get the error below.

It is not yet obvious for me what the issue is (ie. how to fix it).
Once it is fixed, I'd like to propose Travis integration to keep green lights on.

Also, I'd like to move `./goja/main.go` to the [goja_nodejs](https://github.com/dop251/goja_nodejs) repo.

```
ok  	github.com/dop251/goja	97.812s
?   	github.com/dop251/goja/ast	[no test files]
?   	github.com/dop251/goja/file	[no test files]
?   	github.com/dop251/goja/goja	[no test files]
--- FAIL: TestParserErr (0.00s)
	testutil_test.go:16: Error at parser_test.go:443: (anonymous): Line 1:7 Unexpected token }(*parser.Error) != <nil>(<nil>)
FAIL
FAIL	github.com/dop251/goja/parser	0.008s
?   	github.com/dop251/goja/token	[no test files]

real	1m40.044s
user	5m27.020s
sys	0m4.832s
```

For now, just noting the issue.

**Comment by zupa-hu** [comment]
Are you sure the test cases were broken here and not the code? `{a: 1, b: 2}` seems valid to me.

Thanks for the quick reply, sorry for my being slow to react. I wanted to verify it but didn't have the time yet.

**Comment by dop251** [comment]
Yes. It is interpreted as a block statement in this context.

**Comment by zupa-hu** [comment]
All right, thanks.
