### ISSUE TITLE
Runtime.Interrupt() never succeeds

### ISSUE THREAD

**Issue by zupa-hu** [dop251/goja#97]
During my integration tests, a Runtime.Interrupt() call did not succeed and so Goja was hung using the processor at 100%. 
I could reproduce it by adding an `fmt.Println()` to `TestInterruptInWrappedFunction()` and running it indefinitely via:

```
go test -run TestInterruptInWrappedFunction -count 10000
```

It always hangs after a few seconds. Digging into the issue, it seems the Go scheduler makes the goroutine that should do the interrupt wait for the main loop of Goja to finish - making the interrupt deadlock. That's weird because I'm running the tests on 4 cores.

I'm submitting a PR that solves the issue by periodically yielding the processor, causing a ~1% slowdown of Goja.

I understand this is the most critical function of Goja. I have read #14 and #16 and created a benchmark to explicitly test the main loop. Putting the interrupt check outside the inner loop didn't affect performance in a measurable way, so I left it in the inner loop to keep interrupts quick.

Benchmark results BEFORE:

```
root@boomla-vm:/home/zupa/p/goja-interrupt/src/github.com/dop251/goja# go test -bench BenchmarkMainLoop -run X -benchtime 100s
goos: linux
goarch: amd64
pkg: github.com/dop251/goja
BenchmarkMainLoop-4   	    2000	 106004138 ns/op
PASS
ok  	github.com/dop251/goja	222.874s
```

Benchmark results AFTER:

```
root@boomla-vm:/home/zupa/p/goja-interrupt/src/github.com/dop251/goja# go test -bench BenchmarkMainLoop -run X -benchtime 100s
goos: linux
goarch: amd64
pkg: github.com/dop251/goja
BenchmarkMainLoop-4   	    2000	 107030083 ns/op
PASS
ok  	github.com/dop251/goja	225.234s
```

**Comment by dop251** [comment]
Yeah, looks like running an infinite loop inside js creates a tight loop without preemption points so GC cannot stop it when it needs to. I incorrectly assumed that the function call within the loop would create such a point but apparently it doesn't. See https://github.com/golang/go/issues/10958 for further enlightenment.

**Comment by zupa-hu** [comment]
Thanks for the fix and the link! Interesting discussion.
